### ISSUE TITLE
Implement merkle tree position determination for the issue_license call

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1039]
#### Summary
Currently, position in a merkle tree is being sent as a parameter of an `issue_license` call. Yet license provider, when sending a license via `issue_license`, does not have a way what the position should be. Hence, the pos parameter needs to be eliminated and the contract should be able to determine position itself.

#### Possible solution design or implementation
Contract should check the tree for a first available free position. This could be done, for example, by taking the tree size L, and then checking f position (L+i) is taken, for i=1,2,... This way the first available position could be determined.

#### Additional context
Reference implementation of a license provider in a Moat project will be affected by this change.

**Comment by herr-seppia** [comment]
Closed by #1053
