### ISSUE TITLE
Add merkle tree positions as return values of the get_licenses call

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1040]
#### Summary
Currently, `get_licenses` method of the licenses contract returns a collection of serialised licenses. It should also return the corresponding merkle tree positions as they will be needed by the user in order to obtain merkle tree openings for calculating proofs.

#### Possible solution design or implementation
Extend the data returned by the `get_licenses` call to include a collection of pairs (Vec<u8>, u64) rather than a collection of  Vec<u8>. 

#### Additional context
This functionality needs to be tested from a Moat reference user implementation.

**Comment by herr-seppia** [comment]
Closed by #1053
