### ISSUE TITLE
Panic in use_license if license is already nullified

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1051]
#### Summary
use_license should panic if a given license is already nullified

#### Possible solution design or implementation
In license contract, session id plays a role of the nullifier. use_license should check if a given session id exists in a set of session ids, and if it does, it should panic, as that means the license has been used up.

#### Additional context
In the long term, we should make sure that panic message is correctly conveyed to the user.

**Comment by herr-seppia** [comment]
Closed by #1053
