### ISSUE TITLE
Add state information query to the license contract

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1052]
#### Summary
In order to have control in the long run over the state of the contract, we need a way to know how many licenses and session ids are held by it.

#### Possible solution design or implementation
A method returning sizes of licenses, tree and sessions collections should be added to contracts' methods.

#### Additional context
The method should not reveal too much information as it could potentially be used for malicious purposes. Security impact of this method needs to be monitored.

**Comment by herr-seppia** [comment]
Closed by #1053
