### ISSUE TITLE
license contract (get_licenses) - use the feeder query when returning collection of elements

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1054]
#### Summary
In license contract, method `get_licenses`, feeder query could be used to return collection of elements. This would improve performance and flexibility of such queries.

#### Possible solution design or implementation
Use `leaves_from_pos` in transfer contract as an example.

#### Additional context
For privacy reasons, potentially, many licenses could be returned via `get_licenses`, hence the need for this issue is related to security and privacy.

**Comment by herr-seppia** [comment]
Closed by #1053
