### ISSUE TITLE
Implement Future Vote Exclusion

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1060]
#### Summary

To enhance the stability of consensus, the "Future Vote Exclusion" feature is proposed. This feature aims to exclude future block generators from participating in the voting process, mitigating the risk of them voting NIL or abstaining, which could have an adverse effect on consensus.

#### Possible solution design or implementation

This feature will involve modifying the voting eligibility criteria to exclude future block generators. A future block generator needs to be identified and their vote excluded.

**Comment by herr-seppia** [comment]
N/A
