### ISSUE TITLE
Make Timeouts Consistent

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1064]
#### Summary

The current implementation of separate timeouts for each step does not seem to mitigate what it is meant to mitigate, dealing with network congestion. When a timeout expires, only the timeout for the step that did the timeout gets increased. 

#### Possible solution design or implementation

An iteration timeout could be introduced to replace the separate timeouts for each step. This iteration timeout would increase whenever any step times out.

**Comment by herr-seppia** [comment]
Addressed with #1170
