### ISSUE TITLE
Support Protocol Upgrades

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1073]
#### Summary

To ensure that the network can be changed in the future and as support for governance voting, we need to support protocol upgrades. This feature will enable the network to be upgradable and pave the way for protocol upgrade voting.

#### Possible solution design or implementation

What needs to be done:
1. **Formalize an upgrade process**: Develop a process for proposing, scrutinizing and approving changes to the protocol. Discussions are on-going [here](https://github.com/dusk-network/dips/issues/1).
2. **Stakeholder approval mechanism**: Implement a mechanism to seek and verify approval from stakeholders for proposed upgrades.
3. **Upgrade handling**: Implement a mechanism to propagate upgrades once they've been approved.

**Comment by herr-seppia** [comment]
Just to note down
Current wire frames properly encode the `VERSION_PROTOCOL`

https://github.com/dusk-network/rusk/blob/42c99669eb4232dcd5fff0abaf0d4dbacb3f02a3/node/src/network/frame.rs#L11


However, this value is not checked yet against the receiving messages.

We should add a sort of semver_req where we can specify which `VERSION_PROTOCOL`s are supported, and eventually change the business logic according to that

**Comment by HDauven** [comment]
Related DIP can be found here: https://github.com/dusk-network/dips/issues/6
