### ISSUE TITLE
Adjust license contract tests to Citadel 0.5.0

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1082]
#### Summary
Once Citadel 0.5.0 is released, license contract tests can be simplified by using more generic tests utilities present in Citadel 0.5.0.

#### Possible solution design or implementation
Remove duplicated test utilities and use the ones from Citadel 0.5.0

#### Additional context
This can be done only after Citadel 0.5.0 becomes available.

**Comment by herr-seppia** [comment]
Closed by #1096
