### ISSUE TITLE
node: Optimize  transaction execution upon block acceptance

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/rusk#1084]
#### Summary
Upon conducting a local network test with a fixed 2 sec delay for any VM call (VST, EST, Accept, Finalize), it was observed that the execution of `accept/finalize` runs for 4 sec sporadically.

#### Root cause
Both `verify_state_transition` and `accept/finalize` VM calls are guarded with the same non-async mutex. This implies that while a node is accepting a new block it may need to wait for an overlapping VST/EST call to complete.

#### Possible Solution (optional)
As it was suggested by @ureeves, we may consider a mutex removal by introducing different branches.

**Comment by HDauven** [comment]
@goshawk-3 can we close this? Given #1500
