### ISSUE TITLE
Single vote for iteration

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#1109]
#### Summary
When a provisioner timed-out while receiving a block for iteration lower than `RELAX_ITERATION_THRESHOLD`, it should not vote for that iteration neither if the block arrive later on.

#### Possible solution design or implementation
N/A

#### Additional context
See also #1108

**Comment by goshawk-3** [comment]
> It is acceptable to continue gathering votes from previous iterations, but a provisioner shall not vote for an iteration that it has already voted as a timeout

As per the above statement, could we clarify the following scenarios:

**Example Scenario_1:**

1. Provisioner A runs `1st reduction` at 5th iteration.
2. Provisioner A receives the candidate block of the selection of 4th iteration.
3. Currently, if Provisioner A is a committee member of any of the reductions of 4th iteration, it casts a vote per a reduction.

   According to the proposed change `Single vote for iteration`, we should not cast a vote for that candidate as Provisioner_A has already timeout-ed on 4th iteration. Correct? @herr-seppia 

**Example Scenario_2:**

1. Provisioner_B runs `2nd reduction` at 5th iteration.
2. Provisioner_B receives the candidate block of the selection of 5th iteration
3. Should Provisioner_B cast a vote for `1st reduction`, if it's a committee member?  @herr-seppia

**Comment by herr-seppia** [comment]
I changed the issue description according to latest discussion

**Comment by fed-franz** [comment]
As per new directives, the Provisioner should cast a Timeout vote (which can't be replaced in the future even if the block is received).

**Comment by fed-franz** [comment]
Please take into account that, after `RELAX_ITERATION_THRESHOLD` it is still possible to vote for former candidates and to reach quorum on previous iterations
