### ISSUE TITLE
Enrich Rusk ABI and License Smart Contract with a method to provide PLONK setup

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1119]
#### Summary
Citadel users need a way to obtain a PLONK setup, in order to generate proofs and ask the contract to verify the proof.

#### Possible solution design or implementation
We need to extend `rusk::abi` with a call to obtain PLONK setup, and then extend the license contract to have a method that would return this setup to the caller. We could include the setup data in contract code (to avoid changing the ABI), but that would be costly in terms of memory - it would require ca. 190 pages of memory. Thus, it is better to have an ABI function providing the required data.

#### Additional context
This is needed in order to implement a Citadel wallet for the Dusk blockchain.

**Comment by herr-seppia** [comment]
If `PLONK setup` means the `CRS`, that can be provided through HTTP API.

If this is the case, feel free to assign this issue to me

**Comment by miloszm** [comment]
Yes, by PLONK setup it is meant CRS, assigned this issue to @herr-seppia. Moat issue 35 depends on the implementation of this issue.
