### ISSUE TITLE
Consensus: accept block from single Agreement

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1148]
#### Summary

Allow nodes to accept a block when receiving a valid Agreement message.

#### Detailed Description

Currently, nodes wait for a "quorum" of Agreement messages in order to accept a block.
This behavior has been shown to be unnecessary and can be easily bypassed by a malicious actor.

#### Relevant Context 

A previous PR from @goshawk-3 (#1020)  was rejected, probably due to a misunderstanding.
@herr-seppia, please let us know if we can now introduce this change or there's still something missing to be done.

---
Note: If implemented, this change should be reflected in the docs.

**Comment by herr-seppia** [comment]
IIRC creating block from single agreement was leading too many nodes out of sync.
Hence my suggestion to introduce this feature later on, after the new finality feature rollout 

If that's not the case, I'm ok for implementing that right now
