### ISSUE TITLE
consensus: Initialize second step with `None`

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#1165]
It is so because this is a default block that always has an empty hash. If not set as default, second reduction will not vote NIL.

_Originally posted by @goshawk-3 in https://github.com/dusk-network/rusk/pull/1137#discussion_r1410582623_

**Comment by goshawk-3** [comment]
@herr-seppia   This is not needed anymore after implementing #1201 . Now we always initialize Ratification step with the Validation output or keep it default in case of `No Quorum`

**Comment by herr-seppia** [comment]
Close as not required anymore
