### ISSUE TITLE
consensus: Implement adaptive timeout

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1170]
#### Summary

The consensus timeout is currently inconsistent between rounds:  if a round takes N>1 iterations to succeed (because of network congestion or an increase in the network size), this will not be reflected in the following round. However, a network congestion is likely to occur over the span of multiple rounds. Additionally, changes in the network size can generate long-lasting increases in the network latency.

The timeout is also inconsistent between steps. For instance, if the timeout expires on the First Reduction, and we only adjust the First Reduction timeout, the next iteration will timeout at the Second Reduction (whose timeout wasn't updated). As a consequence, we might need two iterations to adapt to a surge in the network latency.

A more adaptive and consistent timeout that better adjusts to variations in the network latency.
The goal of this timeout system is to have each node set this timeout so as to be able to reach consensus on the first iteration.

#### Possible solution design or implementation

Proposed design guidelines:

- Define the following values:
  - Step Timeouts: each phase has a timeout value: (GENERATION_TIMEOUT, REDUCTION1_TIMEOUT, REDUCTION2_TIMEOUT); when a phase timeout expires, the phase terminates.
  - STEP_BASE_TIMEOUT: this value serves as reference for the step timeouts; at the beginning of a new round (Iteration=0) it is set to ROUND_BASE_TIMEOUT; 
  each step timeout at the beginning of the step based on STEP_BASE_TIMEOUT:
    - the calculation should take into account the expected number of messages to be received. For instance, since the Generation phase only requires one message to be received, we can set GENERATION_TIMEOUT=STEP_BASE_TIMEOUT; instead, for the voting phases, which require several messages to be received, we can set REDUCTION1_TIMEOUT=3*STEP_BASE_TIMEOUT.
    - if a step timeout expires, STEP_BASE_TIMEOUT is increased. This means that if the First Reduction timeout expires, the Second Reduction starts with a increased timeout value.
  - ROUND_BASE_TIMEOUT: it indicates the value of STEP_BASE_TIMEOUT at the beginning of a round. This value is set at the end of a round based on the number of the winning iteration (or even better based on the winning iteration of the last N rounds). The goal is to reach a value that adjust as much as possible to the current network latency. For instance, if the last 5 rounds consistently reach consensus at the third iteration, we should probably set ROUND_BASE_TIMEOUT to the value of STEP_BASE_TIMEOUT at the third iteration. Similarly, if we always reach consensus at the first iteration, we should consider reducing ROUND_BASE_TIMEOUT. To that purpose, we could store the elapsed time between the beginning of a step and when the quorum is reached. Let's say we see GENERATION_ELAPSED_TIME has been lower than ROUND_BASE_TIMEOUT/2 for 5 rounds, we should probably set ROUND_BASE_TIMEOUT=ROUND_BASE_TIMEOUT/2. 

 - A suitable MAX_STEP_TIMEOUT should be chosen as the maximum value of STEP_BASE_TIMEOUT

- As suggested by @autholykos, the timeout increase could be logarithmic, with the biggest increases occurring at the first iterations.

**Comment by goshawk-3** [comment]
@fed-franz  Currently, we increase (double step timeout) in an event of `NilQuorum` when encountering a NilQuorum event, despite the fact that the step does not actually reach a timeout. 

See also: https://github.com/dusk-network/rusk/blob/16cd2d58b6f75ec7051fc1c99d0e1a8deae5564a/consensus/src/validation/handler.rs#L137 

Should we increase the `step_base_timeout` in this case too?

**Comment by fed-franz** [comment]
> @fed-franz Currently, we increase (double step timeout) when encountering a NilQuorum event, despite the fact that the step does not actually reach a timeout.
> 
> See also:
> 
> https://github.com/dusk-network/rusk/blob/16cd2d58b6f75ec7051fc1c99d0e1a8deae5564a/consensus/src/validation/handler.rs#L137
> 
> Should we increase the `step_base_timeout` in this case too?

I think we shouldn't. 
Nil votes denote timeouts of other committee members on the Proposal step, so they are not related to the Validation timeout (nor to our timeouts in general).

**Comment by goshawk-3** [comment]
>  the timeout increase could be logarithmic, with the biggest increases occurring at the first iterations.

@fed-franz , do you have any suggestions what should be the math formula to calculate a logarithmic increase?

**Comment by goshawk-3** [comment]
>   This value is set at the end of a round based on the number of the winning iteration (or even better based on the winning iteration of the last N rounds)

@fed-franz Could you clarify what should be the exact algorithm for adjusting ROUND_BASE_TIMEOUT?

- How do we use the winning iteration to adjust ROUND_BASE_TIMEOUT ?
-  Should we use winning iteration number from last N rounds and how ?

**Comment by fed-franz** [comment]
This should be designed carefully. Let me come up with a more precise algorithm and then we can discuss it together.
