### ISSUE TITLE
consensus: Sync: Stop consensus while syncing

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1173]
#### Summary

Recent changes in the code made the synchronization process restart the consensus loop with each block that is accepted into the chain.
This is very inefficient when the node is syncing multiple blocks from a peer.

#### Detailed Description

`try_accept_block` is always invoked with `enable_consensus = true`, which means the consensus loop is always restarted after accepting the block. 
As a consequence, when syncing with a peer the consensus loop will be stopped and restarted for each received block.

#### Possible Solution

Restore previous logic as follows:

 - when in OutOfSync mode, if a valid TIP+1 is received from the syncing peer, the consensus loop is stopped;
 - the consensus loop would be restarted when receiving the `target` block of the sync process, or when the sync timeout expired.

Alternatively, the consensus loop can be kept halted when accepting consecutive blocks from the block pool: when a block is received from the syncing peer, the consensus loop is first stopped; then, all consecutive blocks are accepted; then the consensus loop is restarted. This eliminates the stop/restart issue at least when accepting consecutive blocks.

**Comment by goshawk-3** [comment]
Reverting this change, as it was stated a few times, will reopen a highly concerning vulnerability. Not sure how was this reported again without highlighting the importance of https://github.com/dusk-network/rusk/issues/1083

> This is very inefficient when the node is syncing multiple blocks from a peer.

Just for the record, the so called `inefficiency`  introduced the ability for an attacker to drop the entire network by flooding the network with a batch of tampered blocks.

Also for the record, we use `abort` in `tokio.rs` which is highly efficient and recently a benchmark proved that it's not a bottleneck. 

Please, do not implement this without having https://github.com/dusk-network/rusk/issues/1083

**Comment by fed-franz** [comment]
> Reverting this change, as it was stated a few times, will reopen a highly concerning vulnerability. Not sure how was this reported again without highlighting the importance of #1083

This would not happen if changes were properly documented.

In the former implementation, the attacker would still need to provide a valid TIP+1 to make the node stop the consensus loop. So sending a block with height=MAX would not be sufficient to make the consensus loop stop.

Either way, stopping and restarting the consensus loop when accepting consecutive blocks from the pool is not helpful with regard to the attack, and is most definitely inefficient.

> Also for the record, we use `abort` in `tokio.rs` which is highly efficient and recently a benchmark proved that it's not a bottleneck.
The inefficiency has been indirectly confirmed by a noticeable slower synchronization process (this has been reported by @herr-seppia, but I might have misunderstood). 
Maybe the bottleneck is in the restart of the consensus loop.

> Please, do not implement this without having #1083
As stated there, I'm in favor of this change.

Also, we should probably disconnect (or at least penalize with a reputation system) misbehaving peers.

**Comment by goshawk-3** [comment]
> In the former implementation, the attacker would still need to provide a valid TIP+1 to make the node stop the consensus loop. So sending a block with height=MAX would not be sufficient to make the consensus loop stop.

The so called former implementation is also imperfect as it enables an attacker to easily transition any node state from "InSync" to "OutSync." and that is highly unacceptable.

> Either way, stopping and restarting the consensus loop when accepting consecutive blocks from the pool is not helpful with regard to the attack, and is most definitely inefficient.

What is its overhead compared to major bottlenecks, any data?

**Comment by goshawk-3** [comment]
> Also, we should probably disconnect (or at least penalize with a reputation system) misbehaving peers.

Reputation system is much broader concept that we have not refined yet. Simple blacklisting would also be beneficial. 

Anyway, I don't see why the concept from #1083 (which we discussed with @herr-seppia ) is not considered instead of reintroducing imperfect old solutions.

**Comment by fed-franz** [comment]
> > Also, we should probably disconnect (or at least penalize with a reputation system) misbehaving peers.
> 
> Reputation system is much broader concept that we have not refined yet. Simple blacklisting would also be beneficial.
> 
> Anyway, I don't see why the concept from #1083 (which we discussed with @herr-seppia ) is not considered instead of reintroducing imperfect old solutions.

As I said, I'm in favor of #1083, but I don't think it is in contrast with re-introducing the previous logic of stopping consensus when in sync. 
#1083 defines a security check for entering out-of-sync mode.
This defines an optimization over the synchronization procedure itself (namely, to stop consensus while syncing).

**Comment by goshawk-3** [comment]
> This defines an optimization over the synchronization procedure itself (namely, to stop consensus while syncing).

If that the case, then please change the title and the description to reflect the actual idea instead of proposing to reintroduce an imperfect previous logic as per:

```
Restore previous logic as follows:

when in OutOfSync mode, if a valid TIP+1 is received from the syncing peer, the consensus loop is stopped;
the consensus loop would be restarted when receiving the target block of the sync process, or when the sync timeout expired.
```

**Comment by autholykos** [comment]
Renamed as requested so as to clarify the issue
