### ISSUE TITLE
consensus: Transform Second Reduction into Ratification

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1177]
#### Summary

Change the consensus protocol to make the Second Reduction a ratification over the First Reduction's quorum (or lack of it) rather than a mere second validation of the candidate block.

#### Possible solution design or implementation

> Note, as describe in #1178, we use Validation instead of First Reduction, and Ratification instead of Second Reduction.

The Ratification committee will not vote on the validity of the block but on whether or not they saw a quorum of votes on it.
The result of the Validation will be the input to Ratification: if, at the end of the Validation, a quorum of votes has been received, the Ratification committee member will cast a Ratification vote with "Quorum = true"; otherwise (the timeout expired without a quorum), they will vote "Quorum = false". 

The Ratification vote must include the aggregated Validation votes to be considered valid (in other words, a Ratification vote must include a the Reduction quorum itself in the message as a proof).

If a quorum of Ratification votes is received, a Quorum message is produced with the aggregated signatures (similar to the current Agreement message). This message can be produced by any node receiving such a quorum (as it only needs to aggregate the votes).

#### Additional context

This modification to the consensus protocol has two main goals:
 - de-duplicating the validation process: currently the two Reduction steps are simply a duplicated validation of the block which has no reason to be split into two phases (or even to have two committees)
 - reducing fork events: a quorum on the Ratification phase now represents the confirmation of a subset of provisioners over the result of the Validation phase (instead of being an independent duplicate validation of the candidate block)

**Comment by goshawk-3** [comment]
@fed-franz May I ask you to update the description so that you use  only the new terminology as per #1178?

**Comment by fed-franz** [comment]
> @fed-franz May I ask you to update the description so that you use only the new terminology as per #1178?

Done

**Comment by goshawk-3** [comment]
On collecting a ratification message, before counting it as a valid vote a provisioner must ensure:

- `candidate hash` is non-empty 
- its `Validation aggregated_signature + bitset`  has full quorum.


Could you confirm/extend this @fed-franz?
