### ISSUE TITLE
consensus: Remove round and iteration from the block

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1182]
#### Summary

Currently, we have `round` and `iteration` numbers included both in the block structure and in the NewBlock message.
This is redundant, as only one is needed to be signed.
Additionally, the inclusion of round and iteration in the block structure makes the block hash dependent on them, preventing optimizations like the one proposed in #1180.

#### Possible Solution

We should evaluate the option of removing these fields from the block structure and solely rely on the message signatures.
In practice, information on round and iteration can be easily inferred from all the signatures (for instance, when receiving a Block, we can check its round and step from the Certificate)

**Comment by goshawk-3** [comment]
Currently, we don't have  round/step in Certificate struct definition. Do you mean to `move` round and step from Block::Header to `Certificate` struct instead?

```
pub struct Certificate {
    pub first_reduction: StepVotes,
    pub second_reduction: StepVotes,
}

pub struct StepVotes {
    pub bitset: u64,
    pub aggregate_signature: Signature,
}

pub struct Signature(pub [u8; 48]);
```

**Comment by goshawk-3** [comment]
>  iteration in the block structure makes the block hash dependent on them.

That was added  time ago in order to address https://github.com/dusk-network/dusk-blockchain/issues/1500 with the idea `To avoid proposing blocks for different iteration with the same block hash when the proposer is the same` . Now we are removing this?

**Comment by fed-franz** [comment]
> Currently, we don't have round/step in Certificate struct definition. Do you mean to `move` round and step from Block::Header to `Certificate` struct instead?

Yes, that's indirectly what I meant. If we remove them from the block we would need to indicate them in the Certificate so it can be validated.

**Comment by fed-franz** [comment]
> > iteration in the block structure makes the block hash dependent on them.
> 
> That was added time ago in order to address [dusk-network/dusk-blockchain#1500](https://github.com/dusk-network/dusk-blockchain/issues/1500) with the idea `To avoid proposing blocks for different iteration with the same block hash when the proposer is the same` . Now we are removing this?

I don't think this should be an issue anymore. What's your take on this?
@herr-seppia do you think this is still relevant?

**Comment by fed-franz** [comment]
Besides, candidate and vote messages are still signed with the Iteration number (in the message header), so votes can still be distinguished. The only effect of this change would be allowing a generator to re-use a block generated for a previous iteration (failed_iterations could be left empty and still be valid, although is not convenient for the generator), which I don't think is a concern. In fact, we're even planning on fostering this behavior (block re-use) so as not to waste a valid block that doesn't reach agreement due to timeout.

I think this change is safe to be implemented

**Comment by autholykos** [comment]
Closing out of resigning to the idea that we will never do this (and it is not really a problem, but whatever)
