### ISSUE TITLE
consensus: Ignore candidate with wrong prev_block_hash

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1183]
#### Summary
Currently, if we receive a candidate block with `prev_block_hash` different from our tip's hash, we consider the block as invalid and hence vote Invalid for it.
However, it might be the case that the block generator is actually on a fork (and happens to be the generator for the same round and iteration) and hence produces a block on top of a different tip.

#### Possible solution design or implementation
Instead of voting Invalid, a candidate with a wrong `prev_block_hash` can be simply discarded (as it's not on our chain).
A Provisioner participating in the block validation would then timeout instead of voting Invalid.

#### Additional context
If we implement slashing and apply it to generators producing invalid blocks, we might mistakenly punish the block producer just for being on a fork.

**Comment by autholykos** [comment]
I also do not like to vote NIL here. since it might contribute to create an attested block on a fork the node is not partaking into

**Comment by herr-seppia** [comment]
> if we receive a candidate block with prev_block_hash different from our tip's hash, we consider the block as invalid and hence vote Invalid for it

Can you show the code that does this?
Seems to me that if a VTS fails, the message is simply ignored

**Comment by fed-franz** [comment]
> > if we receive a candidate block with prev_block_hash different from our tip's hash, we consider the block as invalid and hence vote Invalid for it
> 
> Can you show the code that does this? Seems to me that if a VTS fails, the message is simply ignored

Apparently the header is only checked when receiving a block... plus, as you say, a failure on VST makes the provisioner ignore the candidate... does this mean we don't vote for an invalid candidate?

**Comment by herr-seppia** [comment]
In addition to the skip of the proposal phase. Should we skip every "present" message with prev_block_hash different from our chain tip?
If so, should we skip the repropagation too?

**Comment by fed-franz** [comment]
> In addition to the skip of the proposal phase. Should we skip every "present" message with prev_block_hash different from our chain tip? If so, should we skip the repropagation too?

IMO, yes and yes.
