### ISSUE TITLE
consensus: Update Certificate and Committee-related terminology

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/rusk#1208]
#### Summary
With the introduction of failed-iteration "certificates", the following naming system will be employed:

Certificates:
- **Attestation**: is the collection of Validation and Ratification votes attesting the result of an iteration
  - A **Valid Attestation** is an Attestation containing a quorum of Valid votes
  - A **Failed Attestation** is an Attestation containing a quorum of non-Valid votes
- **Certificate**: it is a Valid Attestation of a block included in a child block
  - It is produced by the block generator to certify the previous block

Voting Committees: 
- Each committee member is assigned one or more **credits** (votes that can be cast)
- _Committee Size_ (the number of votes in the committee) is replaced by **Committee Credits**

MRB:
- Rename mrb (most recent block) to tip to be consistent with the rest of the blockchain space.

#### Context
This issue is addressing second half of [#1178](https://github.com/dusk-network/rusk/issues/1178)

**Comment by fed-franz** [comment]
I've updated the description to be in line with recent changes
