### ISSUE TITLE
Create error transaction when user tries to unstake for the only active node

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#1215]
Right now we allow unstaking from the default address and if you try to stake again no blocks are produced

Throw an error tx if its the only active node in the cluster and you try to unstake

**Comment by autholykos** [comment]
It's fine to record this issue, but it is definitely not a priority right now. This is a situation that cannot happen irl because there will always be at least one Provisioner that will keep the Dusk network running. Changing the status to minor
