### ISSUE TITLE
Preverify ZK proofs 

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1228]
#### Summary
Zero-Knowledge Proof (ZKP) verification, although linear in proving time, are computationally expensive and executed sequentially with a transaction.

This issue proposes a mechanism to preverify ZK proofs in our protocol to improve throughput substantially. 

#### Possible solution design or implementation
Proof verification is independent of the smart contract execution, given the verification happens on the host. Preverification would mean proving could happen in parallel.

The main idea is to shift proof verification away from the transaction execution phase, and preverifying proofs where the result is stored in a memtable after a transaction gets accepted in the mempool. 

The existing verify host function would then simply have to do a lookup instead of executing the verification computation during transaction execution. 

#### Considerations

* Test the increased throughput. It will be an easy xx% increase, but would be awesome to bench how much.
* Integrity and security of transactions needs to be maintained.
* Make sure there's no side-effects to memory in the VM. Theoretically it shouldn't.

**Comment by autholykos** [comment]
I like the idea very much. It would considerably decrease the latency of Execute State Transition and the Verify State Transition in the consensus
