### ISSUE TITLE
transfer-contract: implement a data-holder companion contract and a proxy

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1235]
#### Summary
Currently, transfer contract holds all the data it uses within its state. This is suboptimal for upgradability. The reason is that after an upgrade contract's data is not readily accessible, data migration is required and data root changes. In addition, to keep transfer contract id stable and to make it possible for a different logic depending on the block height, we need a proxy transfer contract, which will front for transfer contract calls and redirect them to the logic contract.

#### Possible solution design or implementation
To allow upgradability of transfer contract's logic without affecting its data, a data-holder companion contract needs to be implemented and deployed. Data-holder contract won't be affected by transfer contract upgrades, thus it will be able to maintain continuity of data across transfer contract upgrades. In addition, a proxy transfer contract needs to be implemented and deploy. Hence the overall setup should look as follows:
[transfer-proxy-contract] <==> [transfer-logic-contract] <==> [transfer-data-contract]

#### Additional context
This issue involves adding new genesis contracts named `transfer-data` and `transfer-proxy`, and converting the current transfer contract to make it stateless and to make it use transfer-data contract methods via ICC (Inter-Contract Calls) rather than maintaining its data structures locally. `transfer-proxy` contract will call methods of the current transfer contract, which becomes a transfer logic contract. All parties that currently use transfer contract will switch to use the new transfer proxy contract.

**Comment by HDauven** [comment]
Closing due to finding it is not performant enough.
