### ISSUE TITLE
Refactor DUSK contract gadgets

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/rusk#124]
Following an in person review with @toghrulmaharramov and a telephone consultation with @ZER0, it has been decided that something on the DUSK contract circuits ought to be changed. 

The first required change is the hashing method for the preimage circuit. Currently, the preimage gadget hashes the value commitment, position and stealth address within the note. This will be replaced by hashing more fields from the note, these will be the encrypted data, the R within the stealth address, the nonce and the note type.

The second needed feature is a schnorr gadget, which allows the user to prove the DLP of a signature given a public key pair.

**Comment by autholykos** [comment]
What is the reason to input more fields in the hash? Protection from malleability?

**Comment by Bounce23** [comment]
As without it, there is no likability between a note and its hash. At the moment, only the note owner can prove the existence of pre image.

**Comment by Bounce23** [comment]
As this issue will encompass a couple of extra things, I have made its namesake fit better. 

There extra things are: 
- Refactor the Execute so it removes secret key and nullifier and replaces with Schnorr Gadget 
- Refactor the other circuits so they include the Schnorr gadget

**Comment by Bounce23** [comment]
This branch will be merged into the circuits_refactor branch so that it can be worked in with the DUSK execute circuits whilst the dependencies are being stabilised.
