### ISSUE TITLE
Consider non-deflationary slash

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1259]
Current slash implementation is deflationary, since the slashed amount is burnt.
We should consider unwanted consequences and evaluate possible alternatives like assigning the slashed amount to provisioners.

_See comment by @ureeves in https://github.com/dusk-network/rusk/pull/1257#discussion_r1455852730_

**Comment by herr-seppia** [comment]
I believe we can close this, right?

**Comment by fed-franz** [comment]
Yes, Dusk Economics have been thoroughly analyzed [here](https://github.com/dusk-network/dusk-protocol/tree/main/economics). Future modifications should refer to that section
