### ISSUE TITLE
Display public key or staking key of the user and allow the user to copy it

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#1281]
Display the public/staking key of the user and allow the user to copy it in the staking section

**Comment by kieranhall** [comment]
This issue is getting stale.  Has there been any updates here @laremas @nortonandreev?

Is the OP issue been satisfied by other changes @Daksh14?

**Comment by nortonandreev** [comment]
> This issue is getting stale. Has there been any updates here @laremas @nortonandreev?
> 
> Is the OP issue been satisfied by other changes @Daksh14?

cc: @ZER0 what's the expectation here? Thanks!
