### ISSUE TITLE
Implement importing wallet using a DAT file

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1286]
Currently, there is a "Choose file" on the /login route that should let the user upload a .DAT file. However, this is currently disabled, as the functionality is missing.

**Comment by Daksh14** [comment]
> > @kieranhall it will probably be implemented this week and would need to be worked on this week so lets keep it here
> > I'm actively working on the rust side to put the behaviour of the wallet.dat file in a rust crate so it can be used in wallet-cli and wallet-core together
> 
> Any update on this, @Daksh14?

I have published a `dusk-wallet-dat` crate on crates.io which I can easily hook wallet-core and expose a function on dusk-wallet-js, but I need to discuss it further with @ZER0. We still need an encrypted file which the users can use to access both the wallet-cli and web-wallet and have `SAVE LOGIN` functionality.

**Comment by nortonandreev** [comment]
As mentioned on the planning session the other day, I think we also need to ensure that the Export Wallet function in the Settings is implemented and enabled at the same time with the release of the Import Wallet functionality.

 I guess it's still possible for user to export from the wallet-cli and import to the web wallet, however, I feel like it's good to have parity and release these two features on the web wallet at the same time. Of course, the work for exporting the wallet can be captured in another issue, but we need to track the releases and release them at the same time.

**Comment by nortonandreev** [comment]
And, after today's call, it seems like we have to decide if we want to have the .DAT file import at all or not.

**Comment by nortonandreev** [comment]
Closing, as we won't support .DAT import/export for the time-being.

See more https://github.com/dusk-network/rusk/issues/1498
