### ISSUE TITLE
Add gap options for the `Card` component

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#1295]
#### Summary
The Card component adds a bottom margin of `.5em` to its header.

Depending on where the card is used we may want different gaps.

#### Possible solution design or implementation

Add a gap property which can have fixed values (e.g. `"small" | "normal" | "double"`) and style it to use the already defined gaps in CSS variables.

#### Additional context

We may want to update the login page when we tackle this, as its gaps are way smaller than the design on Figma.

**Comment by laremas** [comment]
What should i do? i think @ascartabelli already answered.

**Comment by nortonandreev** [comment]
Spoke with @laremas, will go with the following options for the time-being:

small: 8px
default: 10px
medium: 20px
large: 30px;

We can revisit this once the updated design system is in place.
