### ISSUE TITLE
Community: Show a different page or make the wallet unusable when the global sync is happening

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#1306]
Instead of the sync loading bar at the bottom, show a different page or hide wallet operations

Even when the dusk-wallet-js library is as optimized as it can be, the sync will till take time and only grow with the network so we should just make the user wait until the global sync is happening or if the sync takes more than lets say, 2 seconds

This will be possible to implement once the library is using worker js

**Comment by Fulviuus** [comment]
We will add a throbber in the UX to make it more clear that the UX is updating.

**Comment by nortonandreev** [comment]
Personally, something that I don't like is that the throbber appears in the components while sync is happening – leaving the impression that two operations are happening at the same time, which is not the case. The sync has to be performed first, before the another one can proceed. In that sense, I think that showing two process indicators at the same time is misleading and confusing – also can be distracting, as the sync, which is the main operation, appears smaller on the bottom, compared to the throbber, which is prominent in the middle of the screen.

<img width="553" alt="Screenshot 2024-02-29 at 14 47 34" src="https://github.com/dusk-network/rusk/assets/34094428/7cea039d-eabf-4194-b1df-b527dd7f07ab">
<img width="526" alt="Screenshot 2024-02-29 at 14 47 29" src="https://github.com/dusk-network/rusk/assets/34094428/159f0000-4906-403d-94e0-760496b37277">

cc: @laremas @Fulviuus
