### ISSUE TITLE
Creating a Wallet (sometimes) returns the user to the ToS step

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1310]
On Safari, sometimes I am seeing a bug where after creating a Wallet, I am being returned to the ToS step.

From what I have seen so far, it happens the first time after trying to create a new wallet from a clean state.

Kieran has experienced the same on Chrome, although I couldn't reproduce it there.

I haven't yet tested the Restore flow, but I assume similar thing might be happening there.

**Comment by Fulviuus** [comment]
Seems to not be happening anymore, closing
