### ISSUE TITLE
Exception handling for disabled contracts

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1317]
Currently, it's possible that a user will end up with no contracts enabled (if they're all disabled in the `env`).

I think it's good to introduce some error page / empty state for when no contracts have been enabled, giving some useful information to the user (I guess it would be mostly the developer in this case).

Generally, it feels like it will be more of a developer's error if this situation occurs, so it's perhaps a low-priority item, but I think it's nevertheless useful to have (for example, neither Alex, Dash or I knew about the addition of the env variables and were met with an empty page).

**Comment by laremas** [comment]
I would add a support mail or a documentation link with something that let the user follow up the process on how to enable the required functions.

**Comment by nortonandreev** [comment]
> I would add a support mail or a documentation link with something that let the user follow up the process on how to enable the required functions.

Yeah, I was thinking to make the "our support team" a link that opens the mail client to message the support. Do we have a support email for such matters? I can't seem to find anything support-related in the Gmail's contact book. And then, probably it would be better to have a link that explains these settings, instead of overloading someone from the team with such mails.
