### ISSUE TITLE
Hardcode different variations of transfer contract

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/rusk#132]
The dusk token contract is complete therefore all the possible variations of the contracts must be hardcoded so that they can be preprocessed. 

This will include: 
- 12 Variants of the execute contract
- Send to contract obfuscated 
- Send to contract transparent
- Withdraw from obfuscated to contract
- Withdraw from obfuscated

**Comment by CPerezz** [comment]
Closed via #136
