### ISSUE TITLE
Update the scroll-blocking events to use passive event listener (Tabs component)

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1320]
<img width="971" alt="Screenshot 2024-01-29 at 18 27 48" src="https://github.com/dusk-network/web-wallet/assets/34094428/f65fae36-5a02-44e0-bae4-56915a475b6f">

**Comment by ascartabelli** [comment]
@nortonandreev I think we can use [`overscroll-behavior-x: contain;`](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior-x) as Safari, who was the one late to the party, supports it since 2022.
