### ISSUE TITLE
Remove `indent_size` for general files in `.editorconfig`

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#1329]
**Describe the bug**
We should remove the [`indent_size`](https://github.com/dusk-network/rusk/blob/master/web-wallet/.editorconfig#L5) from the `[*]` section of our [`.editorconfig` file](https://editorconfig.org/): as we are using tabs for indentation, the indent size should be a personal preference and not fixed for everyone.

**Comment by Fulviuus** [comment]
closing
