### ISSUE TITLE
Alter in circuit single key schnorr

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/rusk#134]
The schnorr proofs with single key variant require a different in circuit constraint. 

The most simplistic way is to continue the gadget with private inputs and constrain the pk to be equal to the private schnorr pk, as all `notes` contain the pk anyway.

**Comment by CPerezz** [comment]
I belive this is closed with #133 right @Bounce23 ?

**Comment by Bounce23** [comment]
This is now closed. Correct!
