### ISSUE TITLE
Tests don't pickup the ResizeObserver assignment within the Vite Setup

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1351]
**Describe the bug**
The ResizeObserver has been mocked in the `vite-setup.js`, however, seems like tests are not picking this up and require manual assignment within the test files. 

**Expected behaviour**
Developers shouldn't need to assign the ResizeObserver to the Global object within the tests, as it has been done in the `vite-setup.js`.

**Comment by ascartabelli** [comment]
Closing as no longer relevant
