### ISSUE TITLE
web-wallet: Add notice on login if local storage is about to get reset (ITN)

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1360]
#### Summary
When logging in to a wallet, the local data gets cleared if the new wallet does not match the most recent one the user has used. This leads to longer waiting times for resync to happen. Furthermore, users might not be aware that running two wallets at the same time on the same browser is not supported.

We should introduce a notice during log-in, in case local data exists and will get deleted, due to the user using another wallet to log in.

This should be included in the restore flow, as well as on the main login page.

**Design:**
[Figma](https://www.figma.com/file/ImsgL6Xf0R31HFUIw2xxnw/Wallet-Extension-(FEB-08)?type=design&node-id=3264%3A80830&mode=design&t=iKsNUnm1GF5ZKUhz-1)

<img width="396" alt="Screenshot 2024-02-09 at 14 00 51" src="https://github.com/dusk-network/rusk/assets/34094428/0b19dbac-1ce4-457b-9dbf-d543b1c7f437">

**Comment by laremas** [comment]
Button text update to match the right action.
![img updated](https://github.com/dusk-network/rusk/assets/1636833/157aca0c-4a9f-4b2c-8552-589d7c29727a)
