### ISSUE TITLE
Fix Makefile

### ISSUE THREAD

**Issue by Bounce23** [dusk-network/rusk#137]
The makefile within the rusk library is broken, as it allowed the tests of PR #132 to pass on the GitHub server when they full `cargo test --release`, failed on my machine. 

This ought to be fixed to ensure no discrepancies are seen between the machines and servers.

**Comment by CPerezz** [comment]
I don't think this is a real issue TBH. The Makefile works correctly. So IMO this should be closed. @Bounce23 any thoughts?

**Comment by Bounce23** [comment]
The reason this was raised is because the CI passed the change to the Schnorr gadget about 4 weeks ago, but the library failed in another subcrate. It was most likely due to the use of completely different fn's from different versioning, outside the scope of the analyser. Due to the merged PR, everything should be fixed and if you're happy that its compiling on all levels then this issue can be closed.

**Comment by CPerezz** [comment]
Will take a deeper analysis and check wether it is doing everything it should.
