### ISSUE TITLE
Restoring wallet - browser prompts Wait or Exit page

### ISSUE THREAD

**Issue by Mzer0ni** [dusk-network/rusk#1389]
**Describe the bug**
Restoring wallet - page not responding. 
Entire viewport is not responding and after some time browser prompts user to Wait or Exit page. 
In some cases you get one step further in the wizard before it freezes and in rare occasions you get to the actual wallet view. In all cases the entire UI is not responsive and never gets responsive before browser prompt appears. Similar experience with creating new wallet. 

**To Reproduce**
wallet.dusk.network or https://web-wallet-staging-oxs3z.ondigitalocean.app
[RESTORE WALLET]
*Paste Seed: lesson south habit police into economy toy will tent gasp very version
[NEXT]
![NEXT]
![NEXT]

**Logs/Screenshot**
![image](https://github.com/dusk-network/rusk/assets/70016833/3cca4b94-db82-4114-b68f-3b72ef3aa570)

**Platform**
Fill as appropriate
 - OS: MacOS, Windows, iOS
 - Browser: Chrome, Safari, Edge

**Comment by ascartabelli** [comment]
Thanks for reporting the issue!
This will be solved by #1315 which will be part of today's release.

I'll close this as a duplicate for now.
