### ISSUE TITLE
Investigate `checkValidity()` DOM method

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1391]
#### Summary

`checkValidity()` is being used to check the amount that has been typed in the input fields of the `Send` , `Stake`  and `GasControls` components.

While writing validation for these components we have noticed that we have to wait for the next tick in the svelte app for the validity of the inputs fields to be calculated while being used in a reactive statements.

This might indicate that there is an issue between svelte reactive statements and the `checkValidity()` method and as such the way we deal with validation might need to be refactored to remove the use of `checkValidity()`

**Comment by ascartabelli** [comment]
@nortonandreev opened https://github.com/dusk-network/rusk/issues/1398 to remove its usage in the stake flow
