### ISSUE TITLE
Node got slashed?

### ISSUE THREAD

**Issue by BoboTiG** [dusk-network/rusk#1415]
**Describe the bug**

First, I might just have misunderstand what slashing means here (it is the fact that the node is seen as unhealthy or acting bad). So maybe this is a newbie issue and a simple explanation will clear things out :)

This morning I setup a node, and a few hours later I looked at the logs to check if my node was picked up at some point. And it seems so, one time, but it was then slashed.

**To Reproduce**

I did follow the documentation https://docs.dusk.network/itn/node-running-guide.

The only action done outside of the guide (but it should not impact the behavior, right?) is:

```console
$ ufw allow ssh \
    && ufw allow 8080/tcp \
    && ufw allow 9000/udp \
    && ufw enable
```

So that proper ports are opened, and everything else is closed. But in the installation script I saw that ports range 9000-9005 is opened, it is still the case as I didn't want to change the behavior.

**Expected behaviour**

No slashing.

**Logs/Screenshot**

A more complete log file is attached, and here are relevant lines (lines 127 & 128 in `blocks.log`):

```console
$ grep -A 100 -C 100 'execute_state_transition' /var/log/rusk.log | sed -r 's/\x1B\[([0-9]{1,3}(;[0-9]{1,2};?)?)?[mGK]//g' > blocks.log
2024-02-16T11:01:19.009334Z  WARN node::chain::acceptor: event="missed iteration" height=26612 iter=1 generator="prV8r1A5oHHyMGuq"
2024-02-16T11:01:19.009412Z  INFO node::chain::acceptor: Slashed mvF5VaJPCjyUN1tupsbXC9zh95zqPc8xobah1kbBTpWEYD...biMkBYuekmPEtuDfXnANB5URJufTvT9
2024-02-16T11:01:19.009436Z  INFO node::chain::acceptor: Slashed prV8r1A5oHHyMGuqvsyVP4eMfaqbYYtzKvfV6phwHMBNKa...NqKtisEAnVjBj46iDJdQ7ck4vGs69Td
```

As you can see, 2 nodes were slashed, the first one being mine (I do not know the second one).

On the bright side, my tokens are still staked:
```console
$ rusk-wallet stake-info
✔ Please enter wallet password: · [hidden]
2024-02-16T12:57:01.023672Z  INFO rusk_wallet::io::status: status="Opening notes database"
2024-02-16T12:57:01.688526Z  INFO rusk_wallet::io::status: status="Fetching stake..."
2024-02-16T12:57:01.921549Z  INFO rusk_wallet::io::status: status="Stake received!"
Staking address:
mvF5VaJPCjyUN1tupsbXC9zh95zqPc8xobah1kbBTpWEYD...biMkBYuekmPEtuDfXnANB5URJufTvT9
1010
```

And the balance did not change a bit:

```console
$ rusk-wallet balance
✔ Please enter wallet password: · [hidden]
2024-02-16T12:57:51.294054Z  INFO rusk_wallet::io::status: status="Opening notes database"
2024-02-16T12:57:51.969169Z  INFO rusk_wallet::io::status: status="Getting cached note position..."
2024-02-16T12:57:51.969502Z  INFO rusk_wallet::io::status: status="Fetching fresh notes..."
2024-02-16T12:57:52.078342Z  INFO rusk_wallet::io::status: status="Connection established..."
2024-02-16T12:57:52.080321Z  INFO rusk_wallet::io::status: status="Streaming notes..."
6.99950568
```

The password is correctly set:

```console
$ cat /opt/dusk/services/dusk.conf
DUSK_CONSENSUS_KEYS_PASS=REDACTED
```

**Platform**

 - Architecture: AMD64
 - OS: Linux Debian 12 (bookworm)
 - Browser Firefox

**Additional context**

I did no action outside of the node: nothing with the wallet, I just setup the thing and get back to other unrelated stuff.

It seems there are a bunch of slashing occuring, with duplicate accounts being targeted, that why I think I misunderstood how this works):

```console
$ grep Slashed /var/log/rusk.log | wc -l
1087
```

**Comment by BoboTiG** [comment]
[blocks.log](https://github.com/dusk-network/rusk/files/14311707/blocks.log)

**Comment by herr-seppia** [comment]
Yes it was slashed
Didn’t produce block in time according to other validators.
Anyway don’t worry.
Slash only remove amount from the accrued rewards (so not from the staked amount)
When those rewards are empty, network timeout the node from partecipating into consensus moving its eligibility to the next epoch

**Comment by BoboTiG** [comment]
> Slash only remove amount from the accrued rewards

Out of curiosity, 100% of rewards will be lost?

**Comment by TMiNus** [comment]
It is just the emission amount for that block height.

Slash occurs here:
```
    let slash_amount = emission_amount(block_height);

    for to_slash in slashing {
        session.call::<_, ()>(
            STAKE_CONTRACT,
            "slash",
            &(*to_slash, slash_amount),
            u64::MAX,
        )?;
    }
```

Emission amount:
```
    match block_height {
        1..=12_500_000 => dusk(16.0),
        12_500_001..=18_750_000 => dusk(12.8),
        18_750_001..=25_000_000 => dusk(9.6),
        25_000_001..=31_250_000 => dusk(8.0),
        31_250_001..=37_500_000 => dusk(6.4),
        37_500_001..=43_750_000 => dusk(4.8),
        43_750_001..=50_000_000 => dusk(3.2),
        50_000_001..=62_500_000 => dusk(1.6),
        _ => dusk(0.0),
    }
```

**Comment by BoboTiG** [comment]
Thank you both for those interesting answers 👍🏻
