### ISSUE TITLE
Web-wallet doesnt allow claim rewards without active stake

### ISSUE THREAD

**Issue by Rikkie82** [dusk-network/rusk#1422]
**Describe the bug**
After ITN issues and the request to unstake i did an unstake via cli-wallet. This did not auto-claim rewards.
When trying to claim rewards via webwallet got an error:
![Schermafbeelding 2024-02-18 010008](https://github.com/dusk-network/rusk/assets/160413395/3b312ecb-54c9-4824-b194-e7bad99a914a)
![Schermafbeelding 2024-02-18 005944](https://github.com/dusk-network/rusk/assets/160413395/23942c8b-bac7-4a3e-b686-c47aa68c925b)
Claiming rewards via CLI-wallet worked afterwards

**To Reproduce**
1) unstake from cli-wallet
2) check staked amount is zero but reward value is still showing up (both in webwallet and CLI wallet
3) try to claim via webwallet.

**Expected behaviour**
Would expect an unstake action to autoclaim rewards. If this not happens would expect to be able to claim rewards via web-wallet as well

**Logs/Screenshot**
see above screenshots

**Platform**

Windows 11 laptop W23H2
Chrome: Versie 121.0.6167.185 (Officiële build) (64-bits)

**Additional context**
N/A

**Comment by Daksh14** [comment]
This error gets thrown from here https://github.com/dusk-network/dusk-wallet-js/blob/main/src/contracts/stake.js#L267

**Comment by herr-seppia** [comment]
> This error gets thrown from here https://github.com/dusk-network/dusk-wallet-js/blob/main/src/contracts/stake.js#L267 

Just remove the "has_stake", since makes no sense

**Comment by Daksh14** [comment]
> > This error gets thrown from here https://github.com/dusk-network/dusk-wallet-js/blob/main/src/contracts/stake.js#L267
> 
> Just remove the "has_stake", since makes no sense

removing has_staked is okay but that's not the culprit for sure because other people are able to withdraw while they were unstaked. I think it mostly might be a cache issue or the node not being able to return the stake-info correctly

**Comment by ichbindas** [comment]
Same situation for me, I’m just gonna add my case wether it helps or not:
I unstaked from the cli-wallet and did not receive my rewards automatically. What’s also weird is once I opened the cli-wallet again I still had the option to unstake! Don't want to mess around with that right now, so I'll leave it be
![Bildschirmfoto 2024-02-19 um 09 46 21](https://github.com/dusk-network/rusk/assets/54631150/0f5be3e4-eebf-48c6-97f1-2308b3c569ad)

 I can see my rewards in the web-wallet, I try to claim them which takes a few seconds but transaction fails. 

![Bildschirmfoto 2024-02-19 um 09 52 55](https://github.com/dusk-network/rusk/assets/54631150/58adf5d9-a547-415f-9df1-5bb679d89c16)
![Bildschirmfoto 2024-02-19 um 09 53 08](https://github.com/dusk-network/rusk/assets/54631150/284d84cd-9803-4cb5-95b4-a9faf3b33595)

I tried to login to the cli-wallet again to check if Unstake is still there and now I get this error:
 ```
thread 'main' panicked at 'Invalid cache IO error: While lock file: /root/.dusk/rusk-wallet/cache/LOCK: Resource temporarily unavailable', src/bin/main.rs:86:35
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ichbindas** [comment]
Oh I'm sorry I thought rewards were automatically withdrawn with the unstake transaction. My fault, I misremembered this.

> That means that you have multiple rusk-wallet instance running at the same time

Thanks, I should've known better.

**Comment by autholykos** [comment]
Sorry to be that guy, but can we correct the typo? It is "consensus" not "concensus"

**Comment by nortonandreev** [comment]
> Sorry to be that guy, but can we correct the typo? It is "consensus" not "concensus"

Seems like the error has been removed altogether. [Reference](https://github.com/dusk-network/dusk-wallet-js/pull/73/files#diff-8490164a54526d02f2a7087dc377c19383a63fa0fee00f1e1ad6a9e6a875d330)

**Comment by Rikkie82** [comment]
True, not releases yet, on new testnet issue is still present on web-wallet. Would expect it to throw a gas required action since we don’t have ndusk yet, but it will shows the “no active stake” error.

**Comment by nortonandreev** [comment]
Can this issue be closed now? cc: @Daksh14 @herr-seppia
