### ISSUE TITLE
Create NFT Marketplace on DUSK Network

### ISSUE THREAD

**Issue by 0xalmiron** [dusk-network/rusk#1436]
#### Summary
> The creation of an NFT (Non-Fungible Token) marketplace running on the DUSK network serves as a crucial addition to the decentralized ecosystem. By leveraging DUSK's privacy-focused blockchain, we can provide users with a secure and anonymous platform to buy, sell, and trade NFTs. This marketplace will cater to artists, collectors, and enthusiasts seeking a decentralized and privacy-centric solution for their NFT transactions.

#### Possible solution design or implementation

Smart Contract Development:
Develop smart contracts on the DUSK network to handle the creation, ownership, and transfer of NFTs.
Implement functionalities such as minting, burning, and transferring NFTs securely and efficiently.
Ensure privacy features are integrated into the smart contracts to uphold the privacy standards of the DUSK network.

User Interface:
Design and develop a user-friendly interface for the NFT marketplace, allowing users to easily browse, buy, and sell NFTs.
Include features for artists to mint their NFTs, set royalties, and track sales.
Implement wallet integration for seamless transactions within the DUSK network.

Integration with DUSK Network:
Integrate the NFT marketplace with the DUSK network to leverage its privacy features and scalability.
Ensure compatibility with DUSK's consensus mechanism and network architecture for secure and efficient operations.
Implement off-chain solutions for scalability while maintaining privacy and security standards.

Governance and Community Involvement:
Establish governance mechanisms for the NFT marketplace to ensure community participation and decision-making.
Encourage community involvement through voting mechanisms for feature enhancements, protocol upgrades, and marketplace policies.
Foster a vibrant community of artists, collectors, and developers to contribute to the growth and sustainability of the NFT marketplace on the DUSK network.

#### Additional context
> This initiative aligns with the growing demand for decentralized and privacy-focused solutions in the NFT space.

Thank you

**Comment by Mzer0ni** [comment]
Sound like a community initiative and not a work item for DUSK core team.  Propose to change title to 'Write docs and roadmap for NFT Marketplace on DUSK Network'
IMO it is possible some of the features are already present in the protocol others are yet to be implemented to enable this use case.

**Comment by HDauven** [comment]
Would love to see the effort take place, but unrelated to Rusk. Closing for that reason.
