### ISSUE TITLE
Implement migration code for the stake contract optimisation

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#1448]
#### Summary
As per issue #1447, stake contract needs to be optimised. In order for this optimisation to take effect, the contract needs to be migrated, as otherwise stake data would be lost.

#### Possible solution design or implementation
Before a block is finalised, the block height should be checked against some assumed height, and if it matches, say block height is 20000, a migration is performed, using the migrate method of Session object.

#### Additional context
We need to take care of the ownership of the new contract - see Piecrust issue 336

**Comment by HDauven** [comment]
Resolved by #1464
