### ISSUE TITLE
Release and add tests for raspberry pi 

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#1450]
#### Summary
> 💡 Add a clear and concise description of **the reason why** this needs to be worked on. Focus on the big picture rather than implementation details. What use case does it support? What is the expected outcome?

The raspberry pi is a compact but powerful computer which can be used as a node setup as its small and less costly.

The node seems to not take a substantial amount of resources but we're considering 4gb RAM at least

#### Possible solution design or implementation
> 💡 Add clear and concise description of concrete solutions you've considered. Include possible drawbacks. Add diagrams, pictures, description, code-snippets, or anything else that might help solving the issue. Consider adding different implementation alternatives with tradeoffs.

1. Test `aarch64-unknown-linux-gnu` target on the CI.

2. Create a script which compiles the rusk binary, `recovery-key`, LRS cache, anything that needs to be generated on a much powerful computer, _faster_ will be done on the host computer (MacOS or windows)

I was able to compile using the following workflow
```
cargo install cross --git https://github.com/cross-rs/cross
rustup toolchain install aarch64-unknown-linux-gnu

cross build -r -p rusk --target aarch64-unknown-linux-gnu 

scp ./target/aarch64-unknown-linux-gnu/release/rusk root@raspberrypi:~/bin
```
In the future we can also just bundle `aarch64-unknown-linux-gnu` in our releases so no need to install cross and cross-compile

Additional Context:

If you get the dreaded libssl.so error, then create a Cross.toml in the project root dir and use this config

```toml
[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update && apt-get install --assume-yes libssl-dev:$CROSS_DEB_ARCH"
]
```

Only if openssl was written in rust and used a vendored version of the library, life would be easier

**Comment by HDauven** [comment]
@Daksh14 I think we can consider closing this for the time being. Github is running a closed beta for [ARM64-Linux](https://github.blog/changelog/2023-10-30-accelerate-your-ci-cd-with-arm-based-hosted-runners-in-github-actions/) action runners. 

We applied for the beta. Let's see what happens.

I can confirm that it is possible to compile almost everything in this repository as is and run a node successfully, except for contracts compiled through the [DuskC](https://github.com/dusk-network/rust) compiler. If we would target ARM64-Linux with DuskC too, it should work out of the box.
