### ISSUE TITLE
Add `eslint-plugin-vitest` dependency

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#1486]
#### Summary
By adding a dependency to [eslint-plugin-vitest](https://www.npmjs.com/package/eslint-plugin-vitest), we can reduce our own overrides configuration.

**Comment by ascartabelli** [comment]
Maybe we could add this to our [eslint config repo](https://github.com/dusk-network/eslint-config) as an additional config that we can import?

**Comment by kieranhall** [comment]
Closing in favour of that option.
