### ISSUE TITLE
Remove the explorer dependency on `get_provisioners`

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#1491]
#### Summary

The explorer performs calls to `get_provisioners` from the VM. This causes the explorer to block. Until the events are in place, we need to serve the same information from the chain rather than the VM, so as to prevent blocking.

#### Possible Solution

The proper solution would be to have the Explorer consuming events. However, until solving #948 a temporary solution would be to serve the Provisioner number from the chain without hitting the VM

**Comment by herr-seppia** [comment]
Mitigated by #1500
