### ISSUE TITLE
consensus: Implement filtering of equivalent messages

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#1492]
#### Summary
The current implementation of the duplication map (dupemap) only eliminates identical message duplicates but does not stop processing and repropagation of equivalent messages with variations (e.g. a quorum messages for the same iteration but with different sets of voters). This is one of the sources of unnecessary network traffic, as each variation in the Validation Quorum and Ratification Quorum results in a new message being propagated across the network.

#### Possible solution design or implementation
Before repropagating a validation or ratification quorum, the node would need to check whether it has already propagated an equivalent message (in which case it would simply ignore it).

#### Additional context
An inventory of possible equivalent or redundant messages should probably be created. For example, it might be that it would be undesirable to repropagate a vote for an iteration where a quorum has already been propagated.

**Comment by goshawk-3** [comment]
Does this imply that if we encounter two Quorum messages for the identical future round/iteration but from distinct voters, we broadcast the first arrived and discard the subsequent one? If this is the case, how can we ensure that the first arrived quorum is entirely valid and not tampered with? Would this scenario potentially allow someone to broadcast invalid quorum messages, thereby obstructing the broadcasting of valid quorums?

NB. Currently, a quorum message for future round/iteration is being rebroadcast without validation.

**Comment by goshawk-3** [comment]
Bandwidth collected for 40s on a cluster with 30 provisioners (32 nodes).

```
--------------------------------------------------------------------------------------------
Total send rate:                                     4.50Mb     5.04Mb     5.36Mb
Total receive rate:                                  5.33Mb     4.14Mb     4.36Mb
Total send and receive rate:                         9.83Mb     9.18Mb     9.72Mb
--------------------------------------------------------------------------------------------
Peak rate (sent/received/total):                     8.44Mb     5.40Mb     13.8Mb
Cumulative (sent/received/total):                    27.2MB     22.4MB     49.6MB
============================================================================================
root@cluster0320-node-0:~# 


--------------------------------------------------------------------------------------------
Total send rate:                                     1.59Mb     2.39Mb     2.56Mb
Total receive rate:                                  1.89Mb     2.57Mb     2.82Mb
Total send and receive rate:                         3.48Mb     4.96Mb     5.37Mb
--------------------------------------------------------------------------------------------
Peak rate (sent/received/total):                     3.84Mb     3.79Mb     7.23Mb
Cumulative (sent/received/total):                    12.8MB     14.3MB     27.0MB
============================================================================================
root@cluster0320-node-10:~# 

--------------------------------------------------------------------------------------------
Total send rate:                                     6.28Mb     4.53Mb     4.68Mb
Total receive rate:                                  5.15Mb     4.02Mb     4.21Mb
Total send and receive rate:                         11.4Mb     8.54Mb     8.90Mb
--------------------------------------------------------------------------------------------
Peak rate (sent/received/total):                     6.69Mb     5.53Mb     12.1Mb
Cumulative (sent/received/total):                    24.0MB     21.5MB     45.5MB
============================================================================================
root@cluster0320-node-20:~# 
```

**Comment by fed-franz** [comment]
This issue is still present.
The current implementation only filters out Quorum messages if they are for the current tip (i.e., current_round - 1). 
This means we forward all other Quorums, being them for past rounds, current round, or future rounds.

Note that this also exposes the network to a replay-DoS attack with past Quorum messages: if a node spams past Quorum messages, they will all be forwarded by all nodes.

The proper way to fix this is:
- Only forward one Quorum message per ConsensusHeader (prevblock/round/iteration)
- Only forward one Candidate per ConsensusHeader
- Only forward one Vote per Provisioner per ConsensusHeader

**Comment by autholykos** [comment]
Closing as this will be tackled by solving #2301 and #2171
