### ISSUE TITLE
Change `ByteHash` parameter for kelvin-related functions to Poseidon once Blake2b is phased out

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/rusk#15]

**Comment by CPerezz** [comment]
@julesdesmit  is this still something we need to work on?

Can you update on that?

**Comment by julesdesmit** [comment]
@CPerezz It depends on if we still plan to switch over from Blake2b to Poseidon for hashing kelvin structures (which I think we are). If it has already been implemented we can close it, otherwise just keep it open.

**Comment by CPerezz** [comment]
Ye, the migrationbis fully done. But just for the trees that will require ZKProofs.

**Comment by CPerezz** [comment]
This is outdated and we will need to refactor everything anyway. So closing this issue.

**Comment by CPerezz** [comment]
This is outdated and we will need to refactor everything anyway. So closing this issue.

**Comment by CPerezz** [comment]
This is outdated and we will need to refactor everything anyway. So closing this issue.
