### ISSUE TITLE
Add `format` to CI and `checks` script

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#1504]
To ensure that formatting is being adhered to exactly, the CI should be updated to check the format of the code.  Additionally, the `checks` script should perform the `format` check too.

Note that we appear to also be missing a `devDependency`: `eslint-config-prettier`.  NPM will install this `peerDependency` directly, but it might be better to more closely control the version by adding the dependency to our package.

**Comment by ascartabelli** [comment]
Maybe it's better to move the `eslint-config-prettier` bit to a separate issue?
