### ISSUE TITLE
Web-wallet: typos

### ISSUE THREAD

**Issue by omahs** [dusk-network/rusk#1511]
<img width="1140" alt="typos" src="https://github.com/dusk-network/rusk/assets/73983677/5aefc7b5-8c40-4479-a407-1ea5300846cf">
Spotted a few typos in those files:

- consensus/README.md
- web-wallet/README.md
- web-wallet/src/lib/dusk/components/__tests__/Card.spec.js
- web-wallet/src/lib/dusk/components/__tests__/__snapshots__/Card.spec.js.snap

**Comment by AyeMinPhyo584** [comment]
![Uploading VID_20240306_183715_exported_0.jpg…]()
