### ISSUE TITLE
web-wallet: remove box shadow from button component

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1519]
#### Summary
Remove box-shadow from the focus/hover and active state of the button component.

**Comment by deuch13** [comment]
@laremas The box-shadow style used on the button is also used on the switch, the checkbox, the select and the textbox components. Do you want it removed from these components as well?

**Comment by kieranhall** [comment]
This will probably be needed in Duskit too @deuch13

**Comment by laremas** [comment]
the point is to remove the shadow/glowing effect since we are not using it in any other part of our desing. So yes, please remove it form these components as well.
