### ISSUE TITLE
Throbber and ProgressBar appearing at the same time

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#1545]
Personally, something that I don't like is that the throbber appears in the components while sync is happening – leaving the impression that two operations are happening at the same time, which is not the case. The sync has to be performed first, before the another one can proceed. In that sense, I think that showing two process indicators at the same time is misleading and confusing – also can be distracting, as the sync, which is the main operation, appears smaller on the bottom, compared to the throbber, which is prominent in the middle of the screen.

<img width="553" alt="Screenshot 2024-02-29 at 14 47 34" src="https://github.com/dusk-network/rusk/assets/34094428/7cea039d-eabf-4194-b1df-b527dd7f07ab">
<img width="526" alt="Screenshot 2024-02-29 at 14 47 29" src="https://github.com/dusk-network/rusk/assets/34094428/159f0000-4906-403d-94e0-760496b37277">

cc: @laremas @Fulviuus

_Originally posted by @nortonandreev in https://github.com/dusk-network/rusk/issues/1306#issuecomment-1971073774_

**Comment by laremas** [comment]
I would show a text in the tab component rather than the throbber.
A simple text could be:
Wait for sync to start operating the wallet.

The bar at the bottom should take the whole width of the screen.

**Comment by ascartabelli** [comment]
> Personally, something that I don't like is that the throbber appears in the components while sync is happening – leaving the impression that two operations are happening at the same time, which is not the case. The sync has to be performed first, before the another one can proceed. In that sense, I think that showing two process indicators at the same time is misleading and confusing – also can be distracting, as the sync, which is the main operation, appears smaller on the bottom, compared to the throbber, which is prominent in the middle of the screen.

Although keep in mind that the "main operation", from the user's perspective, it's not the sync, but rather what he's trying to do.

Then, to add more context, situations like the ones you posted as an example are in a promise like (in pseudo-code): `sync().then(performAction)`. In these examples `sync().then(getTransactions)` and `sync().then(getStakeInfo)`.
Other operations that perform a state change instead are `sync().then(performAction).then(sync)`.

So, even if the "action" will effectively run after the sync, it depends on it.

All of this to say that in the end the "extra" throbber is not lying.
