### ISSUE TITLE
Transfer contract - Specify the `Message` structure

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#155]
Out documentation refers to the message as the input for `sendToContractObfuscated` and `withdrawFromObfuscated`.

But, the structure of this message is underspecified and cannot be implemented now. It should reflect the properties of a Crossover. However, the zk-friendly provable encryption scheme is not defined and this is a key part of the circuit to prove it.

It may have implications on `phoenix-core` API because it relies on `r` to prove the encryption inside of a zk circuit. The fee/crossover tuple can only be created by obfuscated notes, and the `Note::obfuscated` API will not allow the user to pass the inner randomness of the note `r` - this is only possible via `Note::deterministic` API that will accept both transparent and obfuscated notes.

**Comment by ZER0** [comment]
Notice that as we discussed, the `Message` structure itself "exists", it's exactly the same as the `Crossover`; the only difference is how we build it. So Basically, to generate a `Crossover` we have:

```rust
    let blinding_factor = JubJubScalar::random(rng);
    let note = Note::obfuscated(rng, &psk, value, blinding_factor);
    let (fee, crossover): (Fee, Crossover) = note.try_into()?;
```

Where to generate a `Message`:
```rust
    let blinding_factor = JubJubScalar::random(rng);
    let r = JubJubScalar::random(rng);
    let nonce = JubJubScalar::random(rng);

    let note Note::deterministic(NoteType::Obfuscated, &r, nonce, psk, value, blinding_factor);
    let (_, message): (Fee, Crossover) = note.try_into()?;

   // use `r` for the proof
```

This is something that is working *already* without changing the APIs.

Therefore we have the following approach we can take to have a better API.
1. Duplicate `Crossover`, having two distinct types.
2. Having a type that is a newtype (wrapper) over the others (e.g. `Crossover` wraps `Message`)
3. Having only one generic type that is dev responsibility to use as a `Message` or as a `Crossover`.
