### ISSUE TITLE
web-wallet: Change copy on "Reset Wallet" tooltip while syncing

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1552]
#### Summary

<img width="771" alt="Screenshot 2024-03-17 at 15 45 41" src="https://github.com/dusk-network/rusk/assets/34094428/447e09aa-5f27-4e1f-ba8c-ffdf77a0f246">

Not really liking the usage of "impossible".

Maybe something like "Not allowed to reset while syncing" or "Can't reset while syncing".

I don't have a strong preference, just feel like the "impossible" is a bit too harsh / not too user-friendly. 😅

What do you think, @laremas?

**Comment by laremas** [comment]
We def need a better text
