### ISSUE TITLE
Rusk Profile - VerifierKey corrupted

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#159]
The tests implemented for the transfer circuits had to recompile the circuit to generate the proper verifier key.

If the extracted key from the Rust Profile is used, the verification will fail.

https://github.com/dusk-network/rusk/blob/master/contracts/transfer/circuits/src/send_to_contract_transparent.rs

The prover key is working correctly.

**Comment by CPerezz** [comment]
Has this recieved any updates?

**Comment by vlopes11** [comment]
Since we are refactoring the bytes serialization, its likely the `dusk-bytes` implementation will fix this error. If not, we should take the analysis from there since there is no point in fixing a code we will no longer use

**Comment by ZER0** [comment]
According to @vlopes11 dusk-network/plonk#332 should fix this as well. He's currently investigate it.

**Comment by vlopes11** [comment]
Fixed, as proven in https://gist.github.com/vlopes11/818509500cb5264392ec1367bc770038
