### ISSUE TITLE
Add proper Bid Contract constants once they're set by research + bussines team

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#160]
In https://github.com/dusk-network/rusk/pull/146 we have included randomly picked values to the constants:
```rust
/// t_m in the specs
const MATURITY_PERIOD: u64 = 0;
/// t_b in the specs
const EXPIRATION_PERIOD: u64 = 10;
/// t_c in the specs
const COOLDOWN_PERIOD: u64 = 0;
```

Once this constants are known @toghrulmaharramov would be nice to leave them here so that the contract can be updated with the correct ones.

This update will require also an update of the tests since the constants are not exported, and some tests depend on them. 
It might be a good point to also orchestate better this fact.

**Comment by ZER0** [comment]
If those constants might change over the time, it could be a possible approach having another contract that store them in the store, and the bid contract calling it to retrieve them.

To be precise we might have a `genesis-settings` contract, that have such settings saved in the store, for all the genesis contract settings that can be updated over time.

**Comment by toghrulmaharramov** [comment]
Constants merged on GitBook
