### ISSUE TITLE
web-wallet: Change "normal" size to "default"

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1623]
I have seen that we have a few size types, namely `ButtonSize`, `GapSize`, and `IconSize`, defined with a "normal" size option. I think that we should change this to "default", as "normal" seems slightly ambiguous. Adopting "default" over "normal" also aligns with widely accepted software development naming conventions.

**Comment by nortonandreev** [comment]
cc: @ascartabelli @kieranhall @deuch13

**Comment by kieranhall** [comment]
I agree with this.  It's also (potentially) non-inclusive language, which we should avoid - and which is currently being drafted into our guidelines.
