### ISSUE TITLE
Zeroize leaves once Bids are withdrawn from the BidTree

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#164]
As it was discussed with @toghrulmaharramov @ZER0 and @vlopes11  there are currently no benefits from zeroizing data in the tree once a `Bid` is withdrawn since:

1) In terms of space, zeroize does not provide any storage space benefits nor any faster root hashing computations in our current setup and with our current tree structures implementations.
2) In terms of security, the `KeyToIdx` map that is stored inside of the Bid contracts acts like a filter where nothing can be done if the PublicKey is not linked to a Bid index on the tree. 
Every time a Bid is withdrawn, the map entry is removed. And with it, any capabilities of using the bid at the index stored before. Even if we try to bid again with the same One-time identity/key, we will be linked to a new index and a new Bid.

Therefore, until our data structures don't provide a storage benefit of zeroizing data or they enable removal of leaves, implementing this feature will only add more complexity and tests to do in https://github.com/dusk-network/rusk/pull/146, but no utility in the real world. 

Therefore this issue is left here so that when we can focus on this kind of things, we address/improve these details.

**Comment by ZER0** [comment]
We don't have bid contract anymore
