### ISSUE TITLE
State corrupted after restart

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#1640]
**Describe the bug**
Sometimes, after a restart, rusk is not able to start due to corrupted state

**To Reproduce**
This is not easy to reproduce, but after multiple try it happens

`service rusk restart`

**Expected behaviour**
Rusk should start properly

**Additional context**
I suspect the culprit is this part of code 

```rust
        let commit = session.commit()?;
        self.set_base_and_delete(commit);

        let commit_id_path = to_rusk_state_id_path(&self.dir);
        fs::write(commit_id_path, commit)?;
```

Indeed the new commit_id is written only after the deletion.

The problem is that, if rusk is restarted between `self.set_base_and_delete(commit);` and `fs:write`, when it restart it still points to old commit that was in the middle of a deletion, resulting into a corrupted state

**Comment by HDauven** [comment]
@herr-seppia does this solve #1482 as well by any chance?

**Comment by herr-seppia** [comment]
> @herr-seppia does this solve #1482 as well by any chance?

Yes it does
