### ISSUE TITLE
consensus: re-introduce timestamp logic for block acceptance

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1649]
> ! THIS ISSUE IS A DRAFT

#### Summary

Introduce time boundaries for new blocks.

#### Detailed Description

While a strict timestamp logic should be avoided (which is why it was removed by PR #1244), it makes sense to reject blocks whose timestamp is way out of our timeline.

#### Possible Solution

Discard blocks that are more than one day in the past or the future

**Comment by autholykos** [comment]
The introduction of timestamps for block acceptance is not strictly needed. The use of timestamps is useful to reduce attack surface on multiple voting and we shall limit its use to that use case when we will get around to implement it.

**Comment by autholykos** [comment]
Obsoleted by #1494
