### ISSUE TITLE
Use direct conversion from `rpc::DecryptedNote` to `NoteVariant` in `new_transaction`

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/rusk#17]
Depends on https://github.com/dusk-network/phoenix/issues/37

**Comment by julesdesmit** [comment]
This issue is no longer relevant, as the logic of `new_transaction` will change - Rusk will instead fetch the inputs by itself, and no longer receive them from the Go process.

**Comment by CPerezz** [comment]
Thanks a lot @julesdesmit for taking a look! <3
