### ISSUE TITLE
Redesign: Smart Contracts Tabs

### ISSUE THREAD

**Issue by laremas** [dusk-network/rusk#1707]
We need to update the contracts tab to be vertical instead using the current horizontal tabs.

The new design will be using a vertical accordion.

**Comment by laremas** [comment]
@ZER0 [here](https://www.figma.com/file/ImsgL6Xf0R31HFUIw2xxnw/Wallet-Extension-(MAY-7th)?type=design&node-id=3894%3A27546&mode=design&t=hZ2lhXi6oP1APUCQ-1) is the new design.

Please make comments on the file.

**Comment by nortonandreev** [comment]
I guess this one can now be closed? @kieranhall
