### ISSUE TITLE
explorer: DataAlert should occupy all available space

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1725]
#### Summary
Currently the `DataAlert` component has it's height fixed to 400px with css. It is not an ideal solution thus an investigation must be made to see how the component can be refactored so it occupies all the available space.

**Comment by nortonandreev** [comment]
It doesn’t, though. The height is set to a minimum of 400px, which is different from having a fixed height of 400px. This means the element can grow beyond 400px if needed, but it will not shrink below this height.
