### ISSUE TITLE
explorer: refactor `onNetworkChange`

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1726]
#### Summary

- [ ] `onNetworkChange` handles retriggering the data fetch if the network is changed. Currently only one function can be passed to it. 
This case creates repeated code as `onNetworkChange` must be called repeatedly if there is more than one function fetching data from API endpoints.
- [ ] `onNetworkChange` should only be triggered when a new value for the `network` is detected in the `appStore`. Currently this hook calls the functions passed to it when the network value goes from `undefined` to a node address

**Comment by ascartabelli** [comment]
I've thought about it and maybe it's better if we stick to how native lifecycle methods are (they accept just a single callback).
So instead of:

```js
onNetworkChange(fn1);
onNetworkChange(fn2);
onNetworkChange(fn3);
```

We can: 
```js
onNetworkChange(network => {
    fn1(network);
    fn2(network);
    fn3(network);
});
```

**Comment by deuch13** [comment]
Closing this issue as the `onNetworkChange` hook will be retired.
