### ISSUE TITLE
explorer: Design a proper application error state page

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1744]
### Description:

We need to design a user-friendly and informative error state page for our application. This page will be displayed when users encounter errors such as 404 (Not Found), 500 (Internal Server Error), and other similar issues. The goal is to ensure users understand what went wrong and provide them with options to navigate back to a functional part of the application.

### Requirements:

1. Error Message:
    - Display a clear and concise error message.
    - Include error codes (e.g., 404, 500) for reference.

2. Visual Design:
    - Create a visually appealing layout that aligns with the application's overall design language.
    - Use appropriate colors, images, or illustrations to convey the error state.

3. Navigation Options:
    - Include a link to the help/support page.

4. Additional Information:
    - Briefly explain what might have caused the error (optional but helpful).
    - Provide contact information or a feedback form for users to report the issue if necessary.

5. Responsive Design:
   - Ensure the error page is responsive and looks good on all devices (desktop, tablet, mobile).

___
For reference, this is what currently a 500 error looks like:
<img width="2168" alt="Screenshot 2024-05-14 at 20 35 43" src="https://github.com/dusk-network/rusk/assets/34094428/1d5eb93f-5880-4a36-bdb4-6e5e04fe669d">

cc: @laremas

**Comment by laremas** [comment]
Made an [**Error Card**](https://www.figma.com/design/INYlGpXEc8tIHCEPNlPyfd/Explorer-2.0?node-id=1714%3A26998&t=uwAgEKR8fyoCTtlX-1) that can hold different messages. what do You think?
