### ISSUE TITLE
explorer: Improve the SearchNotification appearance

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1745]
### Current Design:
<img width="2006" alt="Screenshot 2024-05-14 at 20 45 23" src="https://github.com/dusk-network/rusk/assets/34094428/817980ee-2b39-43f7-b5fd-e6155881461c">

### Suggested Design:

<img width="2014" alt="Screenshot 2024-05-14 at 21 00 29" src="https://github.com/dusk-network/rusk/assets/34094428/81d11b19-b8c4-42da-b3dd-7b52e22e802e">

### Rationale:
- No need to have the "Error" – it's clear from the red outline and the exclamation mark (for those who suffer from color blindness)
- The "Error" is also a bit off-putting / scary, also it's not helpful
- I would use a more user-friendly copy – query string is technical jargon
- I don't think there's a need to use a monospaced font, as we already have 3 colors, different font weights, etc, in the error pane, so it becomes a bit taxing with so much variations
- The contact us needs to link to an email, whatever we decide

That's open for discussion and could perhaps be tweaked a bit further.

**Comment by laremas** [comment]
Fine to me, @fullstackjade we need a proper and more friendly copy to hendle errors. 

I have no informations related to the exact e-mail address to link. (@Fulviuus do You know?)

Design has been updated.
Removed mono text and "Error" from top.

**Comment by fullstackjade** [comment]
I FEEL LIKE SUCH A DEV GETTING GITHUB NOTIS
