### ISSUE TITLE
explorer: Sometimes home page tables don't take full width

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1746]
<img width="2056" alt="Screenshot 2024-05-14 at 21 30 27" src="https://github.com/dusk-network/rusk/assets/34094428/b87427a4-ba61-46b7-9951-45de8502b40f">

Not sure what causes the issue, needs investigating.

**Comment by deuch13** [comment]
@nortonandreev I haven't been able to recreate this under any circumstance. Does it still happen on your machine?

**Comment by nortonandreev** [comment]
> @nortonandreev I haven't been able to recreate this under any circumstance. Does it still happen on your machine?

I will close this for the time being. It has happened recently again, but I'm thinking it might be a thing with Svelte's cache or something, as it works file after a refresh. And I think it happens only when I run the server the first time.

Haven't seen it on prod and others haven't experienced it either, so I think we can close it.

@deuch13
