### ISSUE TITLE
Give visual feedback after a "show more" click

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#1748]
#### Summary
After a click on the "show more" buttons the user has no visual feedback that something happened, as more records are just appended to the bottom of the existing table.

#### Possible solution design or implementation
One possible solution is to display the amount of loaded elements in the header of the card containing the table.

(cc @laremas )

**Comment by nortonandreev** [comment]
The easiest fix would be to scroll to the bottom of the page, ie. adding 

```
window.scrollTo({
  top: document.body.scrollHeight,
  behavior: "smooth",
});
```

in the `loadMoreItems` method.

https://github.com/dusk-network/rusk/assets/34094428/2ef9f1b8-a6a7-404b-b338-ca07a05c4eae

However, this demonstrates a drawback of the Show More button being located on the top of the page – the user has to scroll up so to click the button and load more entries.

**Comment by laremas** [comment]
What do You think of this solution?

![Image](https://github.com/dusk-network/rusk/assets/1636833/70c8701a-fa9e-44a9-b681-5dd89548310a)

Clicking the button will prompt the load of # more items, table will be scrollable and after the added items in the list a new "load more" button will appear at the bottom.

**Comment by ascartabelli** [comment]
> What do You think of this solution?

[...]

> Clicking the button will prompt the load of # more items, table will be scrollable and after the added items in the list a new "load more" button will appear at the bottom.

With the current layout (which I'd like to change) the button can be out of the viewport, which is bad.

The table is already scrollable, but the problem is that:

1. we're polling, so new elements appear on the top
2. added elements will be appended to the bottom

Not really getting how this solution will solve these.

**Comment by ascartabelli** [comment]
I wouldn't write the number alone though, but something like "showing x items" (or "entries").
