### ISSUE TITLE
web-wallet: Low contrast for links

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1765]
We need to change the color used for links, as currently we are not passing neither WCAG AA/AAA, nor APCA WCAG 3.

Some examples of links used across our apps:

**Explorer:**
<img width="251" alt="Screenshot 2024-05-13 at 15 02 41" src="https://github.com/dusk-network/duskit/assets/34094428/78ee7a7d-9492-45e5-985a-7f98ba409934">

**Wallet:**
<img width="543" alt="Screenshot 2024-05-13 at 15 02 44" src="https://github.com/dusk-network/duskit/assets/34094428/62953592-ce0c-46f7-8bb0-05917741f019">

<img width="756" alt="Screenshot 2024-05-13 at 15 03 20" src="https://github.com/dusk-network/duskit/assets/34094428/4ddaaf2a-fae5-4864-9958-605db51f7d8e">
<img width="733" alt="Screenshot 2024-05-13 at 15 03 14" src="https://github.com/dusk-network/duskit/assets/34094428/8c76a216-8874-48af-9188-9f3618cdde44">

The situation is even worse on hover, as the blue becomes even lighter.

___
Related Duskit issue https://github.com/dusk-network/duskit/issues/88

**Comment by laremas** [comment]
We organized this in dm @nortonandreev, closing it for now.
