### ISSUE TITLE
explorer: design loader

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1769]
#### Summary
A design for a loader type component is needed which will comply with the brand and the look of the application.

**Comment by laremas** [comment]
Made this draft to evaluate internal feedbacks. 
what do You think?
[**Prototype**](https://www.figma.com/proto/INYlGpXEc8tIHCEPNlPyfd/Explorer-2.0?page-id=1504%3A42085&node-id=1754-47483&viewport=79%2C526%2C0.17&t=GFFsrCoFVli1knHR-1&scaling=min-zoom)
[**Design**](https://www.figma.com/design/INYlGpXEc8tIHCEPNlPyfd/Explorer-2.0?node-id=1504-42085&t=4IrmU8rCq7NX6rvx-1)

**Comment by kieranhall** [comment]
I like it, it's subtle, but clearly indicates a loading state.

One question is, how would you reuse this pattern in other parts of the UI?  What I mean is, that this loading indicator is tightly coupled with the Table component.  In other loading scenarios, we might not have the table, however, we would want to use the same pattern.

Note, this would also be a development consideration.

**Comment by laremas** [comment]
i was thinking to use the same bar that is being used in the bottom syncing area.
<img width="426" alt="Screenshot 2024-06-10 at 14 37 20" src="https://github.com/dusk-network/rusk/assets/1636833/50b2cefd-1122-4c53-8b1a-95ced664b62c">
but with the accent color.

**Comment by laremas** [comment]
**Update:** [Loader](https://www.figma.com/proto/INYlGpXEc8tIHCEPNlPyfd/Explorer-2.0?page-id=1504%3A42085&node-id=1754-48324&viewport=475%2C-1263%2C0.2&t=f8SuVww2YcZFkCvK-1&scaling=min-zoom&content-scaling=fixed) 
here is the combination between 2 different approach:

**1** - bar on the table header: very cool but not 100% reusable on others components. 

**2** - timeglass on card header before title. that will cover most of the use cases, but less attractive.

What do you think?

**Comment by laremas** [comment]
about the option **1** [here](https://www.figma.com/proto/INYlGpXEc8tIHCEPNlPyfd/Explorer-2.0?page-id=1504%3A42085&node-id=2059-40801&viewport=-315%2C-6639%2C0.63&t=21uUGb0HGIpQmX3T-1&scaling=min-zoom&content-scaling=fixed) is the mobile preview as well.
