### ISSUE TITLE
Refactor transfer contract

### ISSUE THREAD

**Issue by moCello** [dusk-network/rusk#1779]
#### Summary
Refactor the transfer-contract.

#### Detailed Description
This refactor will include:
- [x] merge transfer-types and stake-types into a single library that also re-exports phoenix-core types and functionality as well as other keys and signature types #1780 
- [x] remove the transfer-circuits as they moved to `phoenix-circuits` and integrate to `phoenix-core` v0.28 #1809 and #1810
- [x] refactor the transfer contract after those changes

#### Relevant Context
[phoenix #175](https://github.com/dusk-network/phoenix/issues/175)
[phoenix #169](https://github.com/dusk-network/phoenix/issues/169)

**Comment by HDauven** [comment]
Closing, resolved by #1822
