### ISSUE TITLE
Execute circuit - Signed message

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#178]
Currently, the signed message for the execute circuit is not defined in the documentation.

The code is using a constant scalar `1`. After the content is defined, the circuit should be updated

**Comment by toghrulmaharramov** [comment]
Merged on GitBook: https://app.gitbook.com/@dusk-network/s/specs/specifications/smart-contracts/genenesis-contracts/dusk-contract/non-spurious-methods-part-3
