### ISSUE TITLE
explorer: Define the use of the `Back` button on detail pages

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#1782]
#### Summary
Currently the `Back` button action sends the user back to the `Blocks` or `Transactions` page depending if it's a Block Details page or a Transaction Details page.

In some cases this is not correct as `Back` refers to where the user navigated from. But if this is the case the button becomes redundant as it emulates the browser back button.

As an example the user could have navigated to a details page from the home page or he could have used the arrows to navigate through the block height in the block details page.

Either we remove the button completely or we give it a new and clear purpose.

**Comment by laremas** [comment]
I would go back to either transaction or block page renaming the button "latest transaction" and "latest blocks", if possible. Text could be to long for mobile views. 

I am open to other solutions, let's discuss this.

**Comment by laremas** [comment]
After a new discussion we understood that having this button, while the user can do the same action both with back button on browser or just clicking on the blocks/transaction page link in the navbar, is redundant. 

**So they are now Removed from the table.**
