### ISSUE TITLE
Propagate the block height to the VM

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#179]
The contracts needs to be able to access to the block height given by the node via gRPC (see: https://github.com/dusk-network/rusk-schema/blob/master/rusk.proto#L16).

That would means that `Rusk` needs to pass down to the VM this value, so that the VM can make it accessible via a global host function (e.g. `dusk_abi::block_height()`)

See: dusk-network/rusk-vm#128

**Comment by ZER0** [comment]
This was solved by dusk-network/rusk-vm#128
