### ISSUE TITLE
Inconsistencies Between Explorer and Web Wallet Applications

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1792]
### Description

There are several inconsistencies between the Explorer and Web Wallet applications, specifically in the Transactions sections. These inconsistencies include:

- Placement and labeling of the CTA: "View All Transactions" vs. "All Transactions".
- Usage of the Dusk logo vs. the word "Dusk" in the details showing the value in Dusk.
- Padding on the containers: In the Explorer, the white pane starts from the container's edge, whereas in the Wallet, there is padding around it.
- Section heading styling: In the Explorer, the "Transactions" section heading is lowercased and bold, whereas in the Wallet, it is uppercased and default width.

### Proposed Solution

1. Compare the Transactions sections in both the Explorer and Web Wallet applications.
2. Identify areas where unification makes sense and implement changes to align the design and functionality.
3. Ensure consistency in the placement and labeling of the CTA.
4. Standardize the usage of the Dusk logo or word "Dusk" in the transaction details.
5. Adjust the padding on the containers to have a consistent look and feel.
6. Unify the styling of the section headings to ensure consistency across both applications.

### Steps to Implement

1. Review the current design and layout of the Transactions sections in both applications.
2. Propose design changes to align the two views where appropriate.
3. Implement the changes in both the Explorer and Web Wallet applications.
4. Test the changes to ensure consistency and usability across both platforms.

### Additional Information

- Aim for a consistent user experience across the Explorer and Web Wallet applications.
- Focus on unifying elements such as CTA placement and labeling, padding, and section heading styling.

### Screenshots

<img width="575" alt="Screenshot 2024-05-25 at 16 39 54" src="https://github.com/dusk-network/rusk/assets/34094428/ba885978-b720-4426-ae2d-86c86f269383">
<img width="545" alt="Screenshot 2024-05-25 at 16 39 44" src="https://github.com/dusk-network/rusk/assets/34094428/4116d1f1-1728-4ddb-a9ea-df73d50183cb">

**Comment by laremas** [comment]
Updates:

- Table header style + header buttons
- Container padding
- Dusk symbol/word fixed. removed the ticker and move the "DUSK" on the table items, instead the table header, in the mobile view (for spacing reasons).

**Comment by nortonandreev** [comment]
I will shortly create new issues to cover the outcome of @laremas' work.
