### ISSUE TITLE
explorer: Consider Making Badges Uniform in Width on Transactions List View

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1795]
### Description

In the Transactions List view, the badges for type, status, and type appear to have varying widths. For a cleaner and more uniform appearance, it would be beneficial to make these badges the same width.

### Suggested Changes

- Ensure the type badge, status badge, and type badge are of the same width.
- Update the CSS or styling rules to enforce this uniformity.

### Benefits

- Enhanced visual consistency.
- Improved readability and user experience.

### Screenshots

<img width="650" alt="Screenshot 2024-05-25 at 17 02 27" src="https://github.com/dusk-network/rusk/assets/34094428/3d0b49f5-e2cf-4487-9cc9-6c97db09a883">

**Comment by laremas** [comment]
Updated
