### ISSUE TITLE
explorer: Inconsistent Data Presentation in Blocks and Transactions Views

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1797]
### Description

There are inconsistencies in the way data is presented across the blocks and transactions views, both on the “All Blocks” / “All Transactions” pages and on their respective details pages.

### Proposed Changes

1. On the Blocks Table, change the header from “# BLOCK” to “Block.” The current label is unclear as to whether the “#” stands for “Hash” or “Number.” Additionally, this will align with the Transactions Table, which does not use the “#” symbol.
2. On the Block Details page, rename “Block Hash” to “Hash.” Since this label is under the Block Details card, it is clear that it refers to the block.
3. On the Block Details page, move the height above the hash. This change reflects the user’s action of clicking on the block height in the table/list of all blocks. Moreover, it is the only interactable entry on the Details pane.
4. On the Transaction Details page, rename the “ID” label to “Hash” to match the Transactions Table/List view.

These changes will improve consistency and clarity in the presentation of data across the blocks and transactions views.

### Visuals
<img width="876" alt="Screenshot 2024-05-25 at 18 29 37" src="https://github.com/dusk-network/rusk/assets/34094428/3c58f74a-743c-40be-8906-3ea4b295e12e">
<img width="308" alt="Screenshot 2024-05-25 at 18 29 34" src="https://github.com/dusk-network/rusk/assets/34094428/a41444f0-2660-4aee-8fb5-c157456b637f">

<img width="960" alt="Screenshot 2024-05-25 at 18 29 42" src="https://github.com/dusk-network/rusk/assets/34094428/533a011e-c9ea-4a87-8f77-38e5782afa32">
<img width="234" alt="Screenshot 2024-05-25 at 18 29 31" src="https://github.com/dusk-network/rusk/assets/34094428/dcb80275-ffe7-4ad5-9e9f-31fdebed98ff">

**Comment by laremas** [comment]
Agree, i reflected all the suggestions to figma.

**Comment by deuch13** [comment]
@laremas There is one inconsistency between what we display in the Transactions Tabel and the Transaction Details.
In the Transactions Tabel we show the transaction `Hash` but not the `ID` and in the Transaction Details we show the `ID` but not the `Hash`. I am not sure which one is more important in this context, but we need to have this unified.

**Comment by laremas** [comment]
I am not sure too, let's agree on what to display, maybe @herr-seppia knows?

**Comment by herr-seppia** [comment]
Use ID for both page

**Comment by laremas** [comment]
Updated.
