### ISSUE TITLE
Make `rusk-profile` a stand alone crate / repo

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#182]
Currently `rusk-profile` is a subcrate of `rusk`.
It should be moved as separate crate, at least temporary, so that `rusk-vm` can import it without requires `rusk` as dependecy.

> **Note**: a git dependency is more than enough for the time being, we shouldn't publish it yet on crates.io

**Comment by CPerezz** [comment]
This can be already handled without needing any movement to another repo. See:

`rusk-profile = {git = "https://github.com/dusk-network/rusk/", branch = "master"}`
