### ISSUE TITLE
Add contract deployment transaction

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#1882]
#### Summary
To enable users to deploy contracts, we need to create a contract deployment transaction. Such a transaction must contain:

- The owner of the transaction, identified by a BLS Public Key.
- The contract, as defined in the [Contract Format in the wiki](https://github.com/dusk-network/rusk/wiki/Contract-File-Format).
- The constructor arguments.

#### Possible solution design or implementation

To implement this one will likely touch the  `execution-core` crate to modify the `Transaction` type to include a new variant, possibly with the name `ContractDeploy` or just `Deploy`. 

#### Additional context
This is in the context of [Add Contract Deployment System](https://github.com/dusk-network/rusk/issues/1071).

**Comment by ureeves** [comment]
It might be useful to check if it makes sense to add the expected `ContractId` to the transaction as well. This would be to allow people to have a transaction fail, together with the deployment, if this is not matched (nice in certain dev situations). However, this might be too cumbersome.

**Comment by HDauven** [comment]
This issue should also include the ABI work.
cc: @miloszm @ureeves @ZER0

**Comment by ZER0** [comment]
ABI are not included actually, and currently they don't need to.
