### ISSUE TITLE
Charge for a contract deployment transaction

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#1883]
#### Summary
An "extra" charge should be levied when deploying contract. Such a charge should likely be proportional to the amount of bytes of the contract's bytecode, and be charged to the transaction in gas points. A transaction that cannot pay for this amount should be considered invalid and fail.
Preverification should also be employed, yet the main mechanism should be on block acceptance - if a transaction can't possibly pay for itself, it should never be executed, and the block considered invalid.

#### Possible solution design or implementation
After implementing #1882, it should be possible to do this, charge amount calculation being based entirely on the contents of the new deployment transaction type.  

#### Additional context
This is in the context of contract deployments https://github.com/dusk-network/rusk/issues/1071.

**Comment by miloszm** [comment]
Proposed approach is based on the bytecode length - the charge is equal bytecode length in bytes times the GAS_PER_DEPLOY_BYTE constant (set to 100 at the time of writing) times the current price of gas.
