### ISSUE TITLE
Trigger non-contract and consensus-related events

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1897]
#### Summary
Consensus should emit events so clients can listen to them and act accordingly.

#### Possible solution design or implementation
Blocks should emit events on:
- Block accepted
- Block statechange

Transaction events:
- Transaction included
- Transaction removed

**Comment by ZER0** [comment]
Keep in mind that regarding the events, there is no distinction between what's the internal component that emits it, but more on the target / category (see https://github.com/dusk-network/rusk/wiki/RUES-(Rusk-Universal-Event-System)#event-target-specification).

So the list it makes more sense to be split by `blocks` and `transactions` (see the example in the wiki above) more than `node` and `mempool`.
