### ISSUE TITLE
Do not vote Invalid on "timestamp is higher than local time"

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1909]
#### Summary

Current validation logic returns an Error if the block timestamp is higher than local time. 
However, this check is node-dependent and could not be "validated" (e.g., if we intend to check for wrong votes in the future).
The safest option in this case is to simply discard the candidate (i.e., vote NoCandidate). 

#### Possible Solution

If the block timestamp is higher than local time, discard the block.

**Comment by herr-seppia** [comment]
Can we close this?

**Comment by fed-franz** [comment]
I think this is still a valid issue. We still have a check against the local timestamp (although we now have a margin of error).
My opinion is that we should discard the block rather than voting Invalid.

**Comment by autholykos** [comment]
Solved by #2449
