### ISSUE TITLE
Do not vote Invalid on candidate from fork

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#1910]
#### Summary

In the current implementation, provisioners vote Invalid if the Candidate block has a previous_block_hash different than the current tip. However, it might be the case that this block actually belongs to a fork (hence the different parent hash).
WRT to the fork, the node should simply not participate, so the safest choice here is to discard the block.

Also note, that, if the provisioner if the committee of both branches, voting Invalid on the block from the fork could actually make it miss the block of the branch it's in.

#### Possible Solution

If candidate_block.prev_block_hash is different from the tip, discard the candidate

**Comment by herr-seppia** [comment]
Can we close it as obsolete, right?

**Comment by fed-franz** [comment]
This is also still an issue. We do vote invalid for wrong prev_block_hash. 
While this can only be a problem if the same provisioner is in the same committee in both branches, I believe we should discard the block rather than voting invalid.

**Comment by autholykos** [comment]
Solved by #2449
