### ISSUE TITLE
WithdrawFromTransparentToContract - Wrong documentation

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#198]
There seems to be an error on the documentation. The specification implies we can use different values to withdraw and add, which doesn't make sense.

**Comment by toghrulmaharramov** [comment]
Fixed and merged on GitBook: https://app.gitbook.com/@dusk-network/s/specs/specifications/smart-contracts/genenesis-contracts/dusk-contract/non-spurious-methods-part-1
