### ISSUE TITLE
Investigate Moonlight TX throughput

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#1984]
#### Summary
Given the findings by @ureeves about the Moonlight transaction throughput, based on the modified AST benchmark, we want to understand why these are the way they are.

**Comment by ureeves** [comment]
I've been investigating a little further on this, and apart from changing the signature scheme to single - which we should also do for the stake contract - any change will be pretty incremental. The signature cache already gives us quite a speedup.
