### ISSUE TITLE
Improve Moonlight mempool handling

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#1993]
The handling of Moonlight transactions by the mempool could be made better by abstracting nullifiers and nonces. Perhaps there could be a way of ensuring that transactions originating from the same Moonlight account get picked in sequence as well, to allow for easily predictable bulk transaction processing. 

>But we should address mempool properly in a following PR
>
>Maybe abstracting away the nullifiers to accommodate the MoonlightTx needs
>
>_Originally posted by @herr-seppia in https://github.com/dusk-network/rusk/pull/1930#discussion_r1684331873_

**Comment by herr-seppia** [comment]
Resolves by https://github.com/dusk-network/rusk/pull/2237
