### ISSUE TITLE
Remove scale transition from icon buttons  

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#1996]
Was omitted as part of the work on https://github.com/dusk-network/rusk/issues/1606.

The scale is no longer needed for icon buttons.

**Comment by ascartabelli** [comment]
I would close this unless @laremas had a change of mind as the scaling we agreed upon (with him) was fixed in [this commit](https://github.com/dusk-network/rusk/commit/452bc2971177e584a2ef13b4b947d1521abe6aef).

**Comment by laremas** [comment]
nothing to add
