### ISSUE TITLE
Use incremental nonces rather than just sequential

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#2007]
#### Summary

We should use incremental nonces, rather than just monotonically increasing (sequential), in both the transfer and stake contracts. This will avoid the following:

- With incremental nonces only one transaction at a time is valid in a given block, whereas with sequential nonces there are multiple possibilities, meaning we must introduce the concept of ordering - an undesirable consequence.
- Possible client-end issues with nonce exhaustion

#### Possible Solution

All that needs to change will be the in-contract checks for the nonce. A transaction/call should only be valid if the nonce is the current value +1.

**Comment by ZER0** [comment]
Please, add the module as prefix or as label to identify what this issue is targeting – this is a monorepo.
