### ISSUE TITLE
External call should not reconstruct state

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#204]
The normal flow of the transactions is `receive parameters -> mutate state -> return tuple (new state, boolean result)`

For the external call of the transfer contract, if we receive the new state, we need to either:

* Concatenate the state of the called function with the state of the contract itself so the host can persist both state transitions
* Receive only the boolean result, assuming the state is already handled by the host

**Comment by autholykos** [comment]
@krl please check this issue and see if it makes sense or it can be closed

**Comment by ZER0** [comment]
This should be fixed in a different way by dusk-network/rusk-vm#164
