### ISSUE TITLE
explorer: Investigate ListView's items alignment

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#2056]
<img width="1355" alt="Screenshot 2024-07-31 at 15 06 16" src="https://github.com/user-attachments/assets/46bc423b-e34f-4e5b-b297-0547236db2bc">

It looks to me like the ID and the type properties are not aligned properly (label and data).

**Comment by ascartabelli** [comment]
After talking with @kieranhall we decided to just put a band-aid here: a proper fix would involve a major reworking of these list components styles, but we wanted to change them entirely so it's not worth it.
