### ISSUE TITLE
Spec the Transfer Contract

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2058]
#### Summary

The Transfer Contract servers as an entry point within Dusk. As such, (external) developers might want to interface with it or build tools around it.

#### Possible solution design or implementation

The objective is to retroactively spec the Transfer Contract by detailing its public API, structure of payloads, and events emitted. These specs need to be published on our [Rusk wiki](https://github.com/dusk-network/rusk/wiki).

**Comment by ureeves** [comment]
Closing since now there is [a wiki]((https://github.com/dusk-network/rusk/wiki/Transfer-Contract-Spec). New comments/critique should use issues to request changes.
