### ISSUE TITLE
web-wallet: Create `AllocationMeter` component

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2073]
Create a new reusable `UsageIndicator` component for the wallet app.  The usage indicator should is a horizontal bar, very similar to a progress indicator, however, the bar is always 100% filled and divided by two regions indicating what percentage the user has allocated something.  In the case of the wallet, it is the percentage allocation is between Phoenix and Moonlight.

The usage indicator must support an icon at start and end of the component, which itself should allow for a tooltip explanation.

Initially the color of the component will be green, however, it would make sense to make this customisable via props.

**Figma preview**
![Image](https://github.com/user-attachments/assets/eb66bec8-933e-4521-9cf6-89b5d86179d8)

**Figma link**
https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6207-159313&t=ESWrbfcHC0L6Z8QG-0

**Also see**
[W3C Meter pattern](https://www.w3.org/WAI/ARIA/apg/patterns/meter/)

**Comment by kieranhall** [comment]
@laremas for the tooltip that will be displayed when the user hovers over the shield and fingerprint icon (which are representing 'phoenix' and 'moonlight' accounts), what should the texts say?  We need to know this, not only to display the correct text, but also to name the properties in the code.

**Comment by laremas** [comment]
Quick [Link](https://www.figma.com/design/AaYwlsqoy1uKOEk5j2y9dz/Dusk-2.0---0----Kit?node-id=4395-64499&t=WOInbTG8AiHtBMde-1) to the component in the ui-kit

**Comment by laremas** [comment]
About the tooltip, we can go without for now, the shield/unshield flow will be enough to let the user understand the icons for this release. 

In the future ones we can decide to add it in case needed.
Maybe the x% of shielded dusk/ x% of unshielded dusk.

**Comment by ascartabelli** [comment]
> About the tooltip, we can go without for now, the shield/unshield flow will be enough to let the user understand the icons for this release.
> 
> In the future ones we can decide to add it in case needed. Maybe the x% of shielded dusk/ x% of unshielded dusk.

I would add them anyway (actually I already put them in).
I just need the correct texts. Are "shielded dusk" / "unshielded dusk" the correct terms? Or is it better to mention "phoenix / moonlight"?

cc @kieranhall

**Comment by laremas** [comment]
Ignore the my last comment.
@ascartabelli 
At the moment we show this as a tooltip:

"You have put ${value}% of your funds in your private account"
"You have put ${value}% of your funds in your public account"

I would change the words "account" to -> "**shielded**" and public to -> "**unshielded**".
