### ISSUE TITLE
web-wallet: Create `DashboardNav` component

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2074]
Create a new `nav` component for the wallet app. The nav should be vertically stacked and allow for an unlimited number of items to be added and follow the w3c recommendations as closely as possible.

**Figma preview**
![Image](https://github.com/user-attachments/assets/78f907f2-40dc-4078-aec3-17bacbcb5a45)

**Figma link**
https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6207-159313

**Comment by laremas** [comment]
[here](https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6207-159313&t=4D5NbbI74hkENwhe-1) is the updated menu component.

![menu](https://github.com/user-attachments/assets/368ed3bb-b494-4919-9e9e-75834fc9ba19)
