### ISSUE TITLE
web-wallet: Update Dashboard screen to use `DashboardNav` navigation

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2075]
Presently the wallet Dashboard uses the `Tabs` component to separate the available contracts to the user.  The design has now been updated to use a menu pattern.

An ideal solution would be to swap the `Tabs` component for a new `DashboardNav` component that navigates the user to specific contracts / operations.

**Figma preview**
![Image](https://github.com/user-attachments/assets/7f80beed-aa0d-4e4f-8a7a-bf7bf77567b9)

**Figma link**
https://www.figma.com/design/z6UnA0BtMBUKIcCXD975um/Wallet-Extension-(JULY-26th)?node-id=6207-159313&t=ESWrbfcHC0L6Z8QG-0

**Comment by laremas** [comment]
component changed slightly. 

![Image](https://github.com/user-attachments/assets/a0f500db-3a25-419b-bf22-f3f04ae1561b)
[https://www.figma.com/design/AaYwlsqoy1uKOEk5j2y9dz/Dusk-2.0---0----Kit?node-id=3865-53777&t=WOInbTG8AiHtBMde-1](url) is the component in the ui-kit

**Comment by kieranhall** [comment]
Note that the splitting of the Transfer contract UI will be done in #2175
