### ISSUE TITLE
Transparent token standard (TC) spec

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#2097]
Add a specification for transparent tokens to be used by third parties. The specification will be non-binding, since contract developers may always depart from the specification, but it is nevertheless useful to ensure there is a basis contract developers can use to develop around.

An implementation accompanying the standard would be a good addition, and potentially function as a jumping off point for contract developers wishing to deploy their own.

**Comment by HDauven** [comment]
Completed in the following repository: https://github.com/dusk-network/transparent-token
