### ISSUE TITLE
Launch public devnet Lunare

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2107]
#### Summary

With our latest stack, we currently only run internal devnets. The next step is to open up our new public devnet Lunare.

#### Solution

Launch our new public devnet.

**Comment by HDauven** [comment]
Done by @herr-seppia [here](https://github.com/dusk-network/dusk-deployer/actions/runs/10470721212).

**Comment by fullstackjade** [comment]
@HDauven does this mean it's done and ready?

**Comment by HDauven** [comment]
> @HDauven does this mean it's done and ready?

As discussed, we have a devnet running with the latest stack since Tuesday. Updated the issue on the marketing repo around the release.
