### ISSUE TITLE
Mempool can grow arbitrarily large

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2123]
#### Summary 

In `node/src/mempool.rs`, the function `accept_tx` does not perform any checks on the
number of transactions that are already in the mempool. An attacker could abuse this by
spamming a lot of low-value transactions and overwhelm nodes with these transactions,
which can ultimately lead to a Denial of Service for particular nodes or the whole network.

#### Solution

We recommend introducing an upper limit on the number of transactions in the mempool and
developing eviction rules that prevent cheap attacks. Ethereum clients like geth can be an
inspiration for this implementation, as they contain such a limit and corresponding eviction
rules.

**Comment by goshawk-3** [comment]
Resolved in https://github.com/dusk-network/rusk/pull/2091/commits/22a32de3bc6ba4ca1ecf49f8481d31b46e1ce90e
