### ISSUE TITLE
rusk: refactor `test-wallet` using `wallet-core`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#2130]
We're currently duplicating code from `test-wallet` within `rusk` because the previous `wallet-core` was not usable in this context. However, with the new `wallet-core` now integrated into the same workspace as `rusk`, we can seamlessly utilize it to replace the existing `test-wallet` implementation.

Our long-term goal is to replace `test-wallet` entirely with the Native SDK. In the meantime, refactoring to use the new `wallet-core` will help us achieve functional parity and streamline the codebase.

**Comment by moCello** [comment]
completed by #2135
