### ISSUE TITLE
Hardcoded genesis date can lead to a stuck network

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#2191]
#### Summary

[See (5.) on Node Audit Report]

At node startup, as defined in node/src/chain.rs:276, the genesis block is generated if
the current chain tip is not yet initialized in local storage. However, the genesis date is
hardcoded to March 25, 2024 as can be seen in node/src/chain/genesis.rs:14. Not
only a network based on this particular commit is difficult to be launched, but also this
approach in general poses challenges if the network launch fails and needs rescheduling.
Genesis date modification requires source code modification, followed by recompilation and
distribution of the binary to the node environment. Providing the genesis date via a genesis
config could streamline this process.
More importantly, the genesis date is not validated against the local clock. The timestamp for
the first candidate block, built atop the genesis block, is determined by
consensus/src/proposal/block_generator.rs:122. This timestamp must fall
within a specific time range, relative to clocks of other provisioners in the network. Delay in
block production is a slashable event, so a block timestamp must not be too far in the past.
Delayed blocks are rejected in node/src/chain/header_validation.rs:105. This
means that the next block after the genesis cannot be built without violating the protocol
rules.

At the same time, setting the timestamp of the genesis block too far into the future is also
problematic, as it prevents the block's acceptance by other nodes, see
node/src/chain/header_validation.rs:115.

**Recommendation**

We recommend enabling users to provide the genesis date as well as validating it against the
local clock, aborting the launch if this validation fails. Provisioner instructions should highlight
the need to synchronize node clocks via NTP.

**Comment by autholykos** [comment]
As it seems like there is no longer a risk for the network to get stuck, then this issue is de-prioritized and limited to the extraction of the genesis configuration to a configuration matter. Also, the hard-coded date shall be removed

**Comment by fed-franz** [comment]
> As it seems like there is no longer a risk for the network to get stuck, then this issue is de-prioritized and limited to the extraction of the genesis configuration to a configuration matter. Also, the hard-coded date shall be removed

I'm going to create a separate issue so we can close this one

**Comment by fed-franz** [comment]
Closing as this issue does not appear to exist
