### ISSUE TITLE
Introduce Rusk Versioning

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#2197]
#### Summary
To properly enable a network, where nodes can have different versions of the node, we need to integrate a version labeling system which entails both releasing binaries tied to a specific commit (see `tags`) and handling data and peers using older (or newer) versions of the protocol.

Also see https://github.com/dusk-network/dips/issues/6

**Comment by autholykos** [comment]
This is pretty important to have so that we can manage versions and avoid unduly slashing caused by invalid blocks that are simply following an older version of the protocol.

**Comment by fed-franz** [comment]
Also we should release the protocol as version 1.0.0
