### ISSUE TITLE
Migrate HTTP topics to RUES dispatch

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2203]
#### Summary

We currently have both the old HTTP system and RUES mixed together in our code. This issue focuses on migrating all old HTTP events over to RUES, so everything is standardized.

#### Possible solution design or implementation

The solution involves changing old HTTP routes into RUES event dispatches. Each task below represents a specific query that needs to be migrated to RUES:
- [ ] `propagate_tx`
- [ ] `alive_nodes`
- [ ] `info`
- [ ] `gas`
- [ ] `prove_execute`
- [ ] `preverify`
- [ ] `crs`
- [ ] `provisioners`
- [ ] `gql`

**Comment by ZER0** [comment]
As discussed this is the mapping of the RUES event with the proper targets / topics:

| Current URL              | New URL                    |
| ------------------------ | -------------------------- |
| `/on/Chain/propagate_tx`   | `/on/transactions/propagate` |
| `/on/Chain/alive_nodes`    | `/on/network/peers`          |
| `/on/Chain/info`           | `/on/node/info`              |
| `/on/Chain/gas`            | `/on/blocks/gas-price`      |
| `/on/prover/prove_execute` | `on/prover/prove`            |
| `/on/rusk/preverify`       | `/on/transactions/preverify` |
| `/on/rusk/crs`             | `/on/node/crs`               |
| `/on/rusk/provisioners`    | `/on/node/provisioners`*  |
| `/on/Chain/gql`            | `/on/graphql/query`          |

> [!NOTE]
> \* The `/on/node/provisioners` event is considered legacy and will be supersede by direct contract-based event dispatching.
