### ISSUE TITLE
wallet-core: Remove the cast to `u64` when generating the seed for the keys

### ISSUE THREAD

**Issue by moCello** [dusk-network/rusk#2209]
#### Summary
To not re-generate all our test-keys, we currently cast all our keys-indexes from a `u8` to a `u64`. This needs to be changed and the keys used for testing need to be re-generated.

#### Relevant Context
While breaking the test-keys, we can use that as an opportunity to change the static salt to match the actual keys that are being generated (`"SSK"` to `"PSK"` (`PhoenixSecretkey`) and `"SK"` to `"BSK"` (`BlsSecretKey`)).

follow-up issue from #2135

**Comment by autholykos** [comment]
Closing since we are no longer going to change key generation
