### ISSUE TITLE
Prepare for Nocturne genesis for feature freeze

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#2211]
_Based on by @autholykos in https://github.com/dusk-network/rusk/issues/2191#issuecomment-2309751914_

Genesis data should be passed in a configuration file, so that the same node can actually run on separate networks (eg. mainnet and testnet)

**Comment by autholykos** [comment]
This also includes moving to the official CRS, deploy the prover, and check if everything is ok
