### ISSUE TITLE
Introduce a block size limit

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#2223]
#### Summary

The enabling of contract deployments introduces a new need of limiting the possible size of a block.
As of now, it is possible to generate a block with a very large number of large contracts, possibly adding up to several megabytes.
This huge block would be valid and hence propagated and stored by all nodes.

While charging for deployments mitigates the problem (as each deployment must be paid for), a block generator would get back at least 70% of what he's paying.

Limiting the block size is an easy way to prevent any such attack in the future.

**Comment by autholykos** [comment]
The proposal is 1Mb. This would roughly be equivalent to 250 Phoenix transactions. The assumption is that we will never see a contract that even gets close to the 1Mb in size. To be checked with @miloszm
