### ISSUE TITLE
Support memo functionality to the Transfer transactions

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#2264]
From @HDauven :
> It's nice, and can be used for many things to reduce the number of keys generated per wallet for an exchange. This is especially nice in the context of Phoenix, for Moonlight, which exchanges will primarily use, less so

For the moment we can go for updating the Moonlight (and Phoenix?) Transaction by having an optional 512 byte `memo field`. This will ensure that the transactions will have support for the memo but without really implementing anything else atm.

**Comment by HDauven** [comment]
It's fair to say that passing arbitrary data to transactions has many more use cases beyond just the memo functionality.

Everything that does not necessarily need a contract, but where data pay loads can be arbitrarily interpreted could benefit from it. Inscription, memos...
