### ISSUE TITLE
Stake events should emit JSON

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#2266]
This item pertains to "implement stake events changes". To be discussed with @herr-seppia

**Comment by autholykos** [comment]
There is a dependency on what Piecrust can do

**Comment by herr-seppia** [comment]
> There is a dependency on what Piecrust can do

[Piecrust features shipped](https://github.com/dusk-network/piecrust/pull/384) and [imported into rusk](https://github.com/dusk-network/rusk/pull/2272)

**Comment by herr-seppia** [comment]
I don't know it this worth.
Emitting events in JSON add a bit overhead (and code complexity) for json serialization and deserialization.

Furthermore, if we are going to connect consensus to stake events we'are going to introduce deserialization costs (current rkyv events are already deserialized)

**Comment by herr-seppia** [comment]
Closing, as the rkyv/json should be implemented by the archiver (if needed)
