### ISSUE TITLE
Implement storage solutions for events

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#2269]
Serving these events should already be in place. To be discussed with @Neotamandua

**Comment by Neotamandua** [comment]
Status:
- Storage solution should be optional, therefore an additional service got added to the node. The service gets pushed into the service_list depending if the feature is active or not. 
- This service receives all VM events and is meant to act on them by calling an underlying storage solution.

Open questions & Todo:
- Serving the stored events through the HTTP API
- Test that events are correctly received for storage
- Decide which event type to use for storage (RuesEvent, execution_core::Event, node_data::events::Event)
