### ISSUE TITLE
web-wallet: Fix rounding display error in migration amount input

### ISSUE THREAD

**Issue by deuch13** [dusk-network/rusk#2303]
#### Summary
When using the `USE MAX` button to set the amount to the maximum available in the account a rounding error occurs as seen below.
This should not happen and the amount introduced in the input field should be the same as the one displayed in the balance field.

![image](https://github.com/user-attachments/assets/8f9df5c3-35fb-429c-9216-f75c6a0c9741)

**Comment by laalauren1** [comment]
> When using the `USE MAX` button to set the amount to the maximum available in the account a rounding error occurs as seen below.
> This should not happen and the amount introduced in the input field should be the same as the one displayed in the balance field.

@deuch13 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID DUS07638
Please see the link below to our dedicated support line:
[Dusk Network DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
