### ISSUE TITLE
Seedphrase not accepted ("not valid") during node setup when using custom seedphrase 

### ISSUE THREAD

**Issue by fe71ks** [dusk-network/rusk#2327]
#### Summary

Certain(?) valid seedphrases are not accepted ("not valid") during node setup.

#### Detailed Description (optional)

During ITN, I generated my own seed phrase rather than using the address/phrase generated by the web wallet. I can imagine that more users will (want to) do this as a precaution.

The phrase was generated using only BIP39(?) words, all lower case. The phrase was accepted by the web wallet without an issue, but it was not accepted during node setup with a node installed through ITN-installer: an error was displayed ("seed not valid" or something similar) when confirming the input of the phrase in the prompt. I retyped it many times.

#### Possible solution

I don't know the mechanism of the seed phrase validation but it either needs some finetuning or documentation is needed that offers guidance on how to use a custom seed phrase and what the requirements are to pass the validation.

**Comment by laalauren1** [comment]
> Certain(?) valid seedphrases are not accepted ("not valid") during node setup.
> 
> #### Detailed Description (optional)
> 
> During ITN, I generated my own seed phrase rather than using the address/phrase generated by the web wallet. I can imagine that more users will (want to) do this as a precaution.
> 
> The phrase was generated using only BIP39(?) words, all lower case. The phrase was accepted by the web wallet without an issue, but it was not accepted during node setup with a node installed through ITN-installer: an error was displayed ("seed not valid" or something similar) when confirming the input of the phrase in the prompt. I retyped it many times.
> 
> #### Possible solution
> 
> I don't know the mechanism of the seed phrase validation but it either needs some finetuning or documentation is needed that offers guidance on how to use a custom seed phrase and what the requirements are to pass the validation.

@fe71ks You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NOD07638
Please see the link below to our dedicated support line:
[Node DApps Support Ticket Requests](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by HDauven** [comment]
@fe71ks can you expand upon this please? Because it's not clear to me what happened.

Did you try the recovery on the CLI wallet with the same mnemonic? Because both the web wallet and CLI wallet use BIP39 libraries and should accept the same mnemonic, unless there's a bug in the underlying BIP39 library.

Are you sure the seed phrase you generated adheres to BIP39?

**Comment by fe71ks** [comment]
@HDauven apologies for the delay! Double checked the phrase against BIP39 requirements and it seems I did not use a valid menomonic. Will need to double check what exactly went wrong but this would mean the web wallet and CLI use different kinds of validations for the mnemonic. Please close this issue for now, I will open a new one if required.
