### ISSUE TITLE
node: Take genesis data as config

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#2430]
#### Summary

To allow the same node build to work with different networks (e.g. Mainnet, Testnet, and Devnet), we need to introduce a configuration file to be read at runtime.

#### Possible solution

Move the chain settings from rusk.toml to rusk.settings

Those settings should contain:

    Genesis Timestamp (default to UNIX_EPOCH for tests)
    Genesis Seed (default to [0u8;48] for tests
    ChainId (default to 0 for tests)
    Genesis state root (default ask to VM)

**Comment by autholykos** [comment]
Solved by @2427
