### ISSUE TITLE
Add crate for procedural macro for contract writing

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#2438]
We were discussing the possibility of generating the "boilerplate" code we see in `contracts/alice/` through a procedural macro

@Neotamandua and @HDauven had discussion about behavior here https://github.com/dusk-network/dev-tools/issues/1

@HDauven has an example which we can use as 0.1 

https://github.com/HDauven/piecrust-macros

We should start by pushing a 0.1 first and then later figure out how to improve it

I replied to this disccusion here: https://github.com/dusk-network/dev-tools/issues/2

**Comment by HDauven** [comment]
As discussed with @ZER0 before, we do not want to leak dev tooling into this repository. That's why we created the [dev-tools](https://github.com/dusk-network/dev-tools) repository, since everyone is free to build their own set of tools on top of our primitives.
