### ISSUE TITLE
Allocate screen alignment issue

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2439]
Small issue of this not being aligned 
![image](https://github.com/user-attachments/assets/591341ef-1bb3-4269-9781-c864db1cae0c)

_Originally posted by @deuch13 in https://github.com/dusk-network/rusk/issues/2426#issuecomment-2360965749_

**Comment by nortonandreev** [comment]
Also related – https://github.com/dusk-network/rusk/issues/2433

I'm not sure if it's about the same or a different view.

**Comment by nortonandreev** [comment]
Closing as a duplicate of #2433
