### ISSUE TITLE
Failed to get `rusk-vm`

### ISSUE THREAD

**Issue by 3for** [dusk-network/rusk#244]
Run `make test` failed for unable to get `rusk-vm`.
How can I get the `rusk-vm`?

**Comment by ZER0** [comment]
Hi @3for, `rusk-vm` was temporary put as private repo, we're experimenting to improve the development and building time for `rusk`.
Now it should be public again, but you might experience some hiccups in the coming days.

**Comment by 3for** [comment]
Wow, Thanks a lot~
