### ISSUE TITLE
Fetch Plonk Public Input positions

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#245]
With the last update of PLONK (v0.6), when the circuit compiles we expect a Vec containing the public input positions. This Vec will always be used in pair with the verifier key and is mandatory to verify proofs as the public inputs can only be reconstructed through it.

As a suggestion, we may go one of these two ways:

- Serialize the vector of public positions returned by `Circuit::compile` with the verifier key and return it with `rusk_profile::get`, provided the correct ID of the circuit. If we go this way, we need to recheck the methods of rusk-profile to avoid any misleading signature considering it will not handle only keys anymore but also the public inputs.

- Create a new struct in Plonk that will contain the verifier key and the PI positions, and this struct should be stored in rusk-profile instead of the VK.

**Comment by autholykos** [comment]
Fixed via #486
