### ISSUE TITLE
rusk-wallet: fix incorrect balances

### ISSUE THREAD

**Issue by xevisalle** [dusk-network/rusk#2488]
**Describe the bug**
Sometimes the rusk-wallet shows the Phoenix balance to be 0. This can happen randomly without any clear pattern I could identify. It's not solely a UI informative thing, but also affecting the behavior: if sending out a transaction while the balance shows to be 0, it fails due to "Insufficient balance."

For what concerns Moonlight, in some occasions the line in the terminal stating the balance doesn't even show up.

**Comment by miloszm** [comment]
Similar balance related incorrect behaviour:
while testing "Convert Phoenix to Moonlight" and "Convert Moonlight to Phoenix", when the operation ends, moonlight balance is correctly updated, yet phoenix balance stays not updated, and to see the new balance you need to back up and select the address again.
