### ISSUE TITLE
rusk-wallet: Cache shouldn't be global

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#2508]
**Describe the bug**
Currently there is only one global cache despite the network (devnet, testnet) and the wallet's addresses.
That lead to bugs if the users switch network and/or wallet's addresses.

**To Reproduce**
Having cached notes from devnet and then switch to testnet, and / or switch wallet's addresses.

**Expected behaviour**
The cache shouldn't be affected the behavior of switching network or addresses.

**Logs/Screenshot**
N/A

**Platform**
N/A

**Additional context**
N/A

**Comment by Daksh14** [comment]
This issue is old now we dont use microkelvin, we use rocksdb also cache is seperated by network name specified by -n 'network'
