### ISSUE TITLE
rusk-wallet: Prover and State Server should support different IPC methods

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#2516]
**Describe what you want implemented** 
prover and state server should have the capability to have different ipc method.

**Describe "Why" this is needed**
It's possible that users decide to install a local state server (rusk) but not having the machine powerful enough to compute a prove. So the  state server should use uds, where the prover should use tcp.
Currently the method has to be the same for both.

**Describe alternatives you've considered**
As workaround, the user can use tcp also locally.

**Additional context**
This requires a fundamental shift in how the wallet library is designed. So it's not something we want to do for the time being (as said, a workaround it's possible), but I'm still open the issue to keep this in the back of our heads.

**Comment by Daksh14** [comment]
Passing the `-s`or --state url allows you to change the URL of the state same with `--prover`

See rusk-wallet --help

**Comment by herr-seppia** [comment]
Obsoleted
