### ISSUE TITLE
rusk-wallet: Memo transaction doesn't send to anyone

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2525]
**Describe the bug**
When creating a memo transaction, the user is not asked for a receiving address. Nor is the user asked to send funds along.

**To Reproduce**
Simply execute a transaction with memo attached.

```bash
✔ What would you like to do? · Moonlight Transctions
✔ Please select an operation · Attach Memo to transction
✔ Introduce bytes for memo · FE24
✔ Introduce the gas limit for this transaction: · 500000000
✔ Introduce the gas price for this transaction: · 0.000000001

```

**Expected behaviour**
The user should be prompted to provide a receiving/to address and optionally send along funds.

**Logs/Screenshot**
![image](https://github.com/user-attachments/assets/6b33707c-e4b2-4bb4-b57d-9be5e07fa726)

**Comment by Daksh14** [comment]
Do we wanna be able to send an empty Memo transaction or do we wanna "attach" the memo to a transfer? 

Currently we allow the user to create an empty Memo transaction with the `to: null` Is that okay? @ureeves @HDauven
