### ISSUE TITLE
rusk-wallet: wallet exits with "Please reset the cache!" message

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#2577]
#### Summary
After creation of a wallet from scratch, then closing the wallet, opening again, and choosing "Replace your wallet with a lost one using the recovery phrase" and entering some other but valid phrase, there is a crash-like exit with a message "Please reset the cache!" accompanied by some internals which are not helpful to the user.

#### Possible solution design or implementation
The wallet should be able to handle such scenario and if not, it should guide the user saying, for example, switching the phrase is not possible at this moment, or something similar.

#### Additional context
It seems to be a common and realistic scenario that user creates a new wallet and then she/he wants to switch to a seed used in the past.

**Comment by herr-seppia** [comment]
switch to a new seed means means that cache for current wallet needs to be invalidate
We should warn the user about how distructive will be this operation and guide the user in using multiple profiles (if needed)



```
rusk-wallet -p wallet1
rusk-wallet -p wallet2
```
