### ISSUE TITLE
Rusk error occurred: 404 Not Found

### ISSUE THREAD

**Issue by lufa23** [dusk-network/rusk#2598]
**Describe the bug**

After having upgraded rusk to `v0.3.0` and trying to launch any rusk-wallet related command, I get the following log: `Rusk error occurred: 404 Not Found error`.

**To Reproduce**

- Install rusk v0.2.0
- Update to rusk v0.3.0 via the installer: curl --proto '=https' --tlsv1.2 -sSfL https://github.com/dusk-network/node-installer/releases/download/v0.3.0/node-installer.sh | sudo sh
- Restart the node with service ‘rusk start’
- Ensure that the node is running by launching the command `ruskquery block-height` and seeing different and incremental block-heights
- Launch any of the `rusk-wallet` related commands, such as: `rusk-wallet stake-info`
- Look at the logs

**Expected behaviour**
- After launching `rusk-wallet stake-info` I expect to see a log related to a received stake event, similarly to “2024-10-03T13:50:43.701795Z  INFO rusk::http: Received event at /on/contracts:0200000000000000000000000000000000000000000000000000000000000000/get_stake”

**Logs/Screenshot**

- Instead, after launching `rusk-wallet stake-info` I get:

2024-10-03T13:27:24.165709Z INFO rusk_wallet::io::status: status="Opening notes database" 2024-10-03T13:27:24.183552Z INFO rusk_wallet::io::status: status="Fetching stake..." Rusk error occurred: 404 Not Found: <html> <head><title>404 Not Found 404 Not Found nginx/1.18.0 (Ubuntu)

Also, when launching `ruskquery info` I get:

{ "bootstrapping_nodes": [ "68.183.13.32:9000", "165.227.149.253:9000", "137.184.39.26:9000" ], "chain_id": 2, "kadcast_address": "myIPNode:9000", "version": "0.8.0", "version_build": "0.8.0 (68c67a5 2024-10-01)"

And when launching `ruskquery version` I get:
You are using the latest installer version: v0.3.0. rusk-wallet -V Dusk Wallet CLI 0.1.0 

**Platform**
- Architecture: x86_64 (AMD64)
- OS: Ubuntu 22.04

**Additional context**
When launching `rusk-wallet` alone, I can see that I have created three addresses.
Warning: This wallet only supports up to 2 addresses, you have 3 addresses
And:
Sync Status: Syncing..

**Comment by lufa23** [comment]
it works now!

**Comment by lufa23** [comment]
closing the issue, as it works
Thanks

**Comment by PLombi100** [comment]
I'm still having this exact same error.
