### ISSUE TITLE
Rename gas limit constants in rusk wallet

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#2603]
The gas limit constants should be renamed to `DEFAULT_LIMIT_TRANSACTION` 
since its used for transactions and `DEFAULT_LIMIT_STAKE` to `DEFAULT_LIMIT_CONTRACT_CALL` or `DEFAULT_LIMIT_CALL` mentioned in this comment in this PR https://github.com/dusk-network/rusk/pull/2563#discussion_r1787671068

**Comment by moCello** [comment]
Will be handled in #2563
