### ISSUE TITLE
Faucet issue

### ISSUE THREAD

**Issue by Rikkie82** [dusk-network/rusk#2604]
**Describe the bug**
Moonlight address that got a faucet payout on the 2nd of october gives error today. Also if you hit an error you cannot retry right away like error message indicates but have to wait 24h.

**To Reproduce**
with a moonlight address that had a successful faucet withdrawal and gives an error now, try again after 24h cool-down has passed.

**Expected behaviour**
Faucet should keep working for addresses that were successful before.
Also if you do hit an error you should be able to retry right away without the 24h cooldown

**Logs/Screenshot**

![faucet success!](https://github.com/user-attachments/assets/d0f5a7e5-bc98-471c-9f32-9a37f52738be)
![faucet error](https://github.com/user-attachments/assets/26620de9-4a17-4e3a-bbc0-c872ba684a67)

**Platform**
Discord - dusk faucet app/bot

**Additional context**
Hein was able earlier to submit some dusk to this address, then also faucet worked for me.

**Comment by Rikkie82** [comment]
![IMG_2536](https://github.com/user-attachments/assets/9e2c808e-527c-46a5-b51b-65aafe1f6c9e)

screenshot from another community member

**Comment by Rikkie82** [comment]
@autholykos @HDauven please also fix faucet that if you hit an error it will not stop you for 24h but you are actually able to retry (like error message indicates)🤗

**Comment by Rikkie82** [comment]
![8F2E271B-B705-4606-8D15-1E7E2822B806](https://github.com/user-attachments/assets/567cabe3-a830-4413-8c52-1c2fcbc3cb72)

Since this morning the faucet doesn’t even reply anymore with the final status, waiting for an hour on tx-Id or failure message now.

**Comment by HDauven** [comment]
This should be resolved now @Rikkie82. Please close the issue if it is indeed the case.

**Comment by Rikkie82** [comment]
Still issues but guess due to network congestion right?
