### ISSUE TITLE
Show Moonlight <-> Phoenix convert history in CLI-Wallet transaction history

### ISSUE THREAD

**Issue by Rikkie82** [dusk-network/rusk#2606]
#### Summary

Would be nice to not only inbound and outbound transactions in your transaction history but also the convert TX's

#### Possible solution design or implementation

Via Archival node retrieve all TX types and show then in transaction history

**Comment by HDauven** [comment]
Closing this as it's part of #2271. For the archiver, Moonlight transactions are bundled together, regardless if it's a convert, contract call, deploy or a regular transfer.
