### ISSUE TITLE
node: Improve mempool TX retrieval performance

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2618]
#### Summary
Currently requesting transactions from the mempool takes a relatively long time with a large amount of transactions in the mempool. This is not a problem right now, nor should it be a breaking change.

#### Possible solution design or implementation
Optimize the way RocksDB calls are made to retrieve transactions from the mempool.

Possible culprit could be in [get_txs_sorted_by_fee](https://github.com/dusk-network/rusk/blob/9d2969bf4cb74b8af1c91e8b1d34198a6d04e006/node/src/database/rocksdb.rs#L809) or [get_tx](https://github.com/dusk-network/rusk/blob/9d2969bf4cb74b8af1c91e8b1d34198a6d04e006/node/src/database/rocksdb.rs#L756).

**Comment by herr-seppia** [comment]
mempool was already fast, it took 12secs because the mempool were full
