### ISSUE TITLE
CLI-Wallet version 0.3.1 installer - multiple addresses visualization

### ISSUE THREAD

**Issue by Rikkie82** [dusk-network/rusk#2637]
#### Summary
The new way of displaying multiple addresses is less user friendly as it was before. Can we revert back to show the actual phoenix addresses?

#### Possible solution design or implementation
 from this: 
![image](https://github.com/user-attachments/assets/29679c68-da4b-4ef2-9374-8c96b0a7e522)
back to
![addresses](https://github.com/user-attachments/assets/b8344261-f364-4cb5-9927-4b1a9e56a177)

**Comment by moCello** [comment]
The old way of displaying the addresses only displayed the phoenix-addresses, which means that even when making a moonlight transaction, the user would need to pick a phoenix address. To me this was very confusing.
With the new way, the user can chose between address profiles to generate a transaction and the wallet will pick the correct (phoenix or moonlight) address depending on whether the user wants to generate a phoenix or moonlight transaction.
Can you explain what exactly you find is not user friendly?

**Comment by Rikkie82** [comment]
What I find not that friendly is the "default address" and "address no 1" visuals. Specially if you dont use it often in CLI might not remember after a while what is what. So extra clicks needed to find out. Liked it that it showed a recognizable address as choice option. Other alternative is to allow a rename of the labels, then users can choose what they prefer to see.

**Comment by moCello** [comment]
> What I find not that friendly is the "default address" and "address no 1" visuals. Specially if you dont use it often in CLI might not remember after a while what is what.

What I don't understand is where in the flow of using the wallet is it necessary for you to need to remember your own address?

**Comment by nekonimous** [comment]
Agree, showing the address is way more useful than just an index.

> What I don't understand is where in the flow of using the wallet is it necessary for you to need to remember your own address?

I don't think we talk about whether it's necessary or not. We just mean that the previous UX was better.

**Comment by nekonimous** [comment]
I just want to quickly identify what address(es) I'm looking at. Ideally, it would also include the moonlight address somewhere next/below/wherever to it. But all in one screen is just nice.

Something like this works for me:

 ```
 -- Addressess --
 0 - (Phoenix: abcv...sdff |  Moonlight: hghgh...ghfhhh )
 1 - (Phoenix: hghr...were |  Moonlight: nbbvb...a2eee6 )
 ```

Fwiw. I also modified my local rusk-wallet to print both Phoenix and Moonlight when using `rusk-wallet addresses`, but I guess that's another topic.

```diff
diff --git a/rusk-wallet/src/bin/command.rs b/rusk-wallet/src/bin/command.rs
index ef1aec0d..c0c0c107 100644
--- a/rusk-wallet/src/bin/command.rs
+++ b/rusk-wallet/src/bin/command.rs
@@ -509,7 +509,15 @@ impl Command {
                         .addresses()
                         .iter()
                         .enumerate()
-                        .map(|(_index, (phoenix_pk, _bls_pk))| {
+                        .map(|(_index, (phoenix_pk, bls_pk))| {
+                            println!(
+                                "{}\n{}",
+                                format!(
+                                    "{}",
+                                    Address::Phoenix { pk: *phoenix_pk }
+                                ),
+                                format!("{}", Address::Bls { pk: *bls_pk }),
+                            );
                             Address::Phoenix { pk: *phoenix_pk }
                         })
                         .collect();
```

**Comment by moCello** [comment]
The issue is a bit trickier than that because the bls-keys are not only used for moonlight addresses but also for the staking operations.
This is also why I really want to understand why you find the previous layout better when it only showed a preview of phoenix-keys.

**Comment by Rikkie82** [comment]
Being used to crypto wallets always do a quick recognition on addresses. Maybe it's just me.
Also noticed in cli commands, the 2nd wallet is addr-idx 1 (guess first is 0). My first instinct i typed addr-idx 2 for 2nd address.
