### ISSUE TITLE
explorer: Footer layout and rendering is incorrect

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2640]
**Describe the bug**

The footer of the explorer has a number of issues that need to be addressed:

1. The logo disappears on small screen sizes
2. The layout doesn't follow a mobile-first approach

**Expected behaviour**
The footer should look and behave as it is described [in Figma](https://www.figma.com/design/INYlGpXEc8tIHCEPNlPyfd/Explorer-2.0?node-id=2059-40821&node-type=frame&m=dev).

**Comment by kieranhall** [comment]
More points raised by @nortonandreev here: https://github.com/dusk-network/rusk/pull/2638#issuecomment-2409075108

**Comment by nortonandreev** [comment]
<img width="746" alt="Screenshot_2024-10-14_at_11 33 03" src="https://github.com/user-attachments/assets/f640435d-d4f5-42d2-9ff3-426202c79b5b">
<img width="663" alt="Screenshot_2024-10-14_at_11 40 07" src="https://github.com/user-attachments/assets/c6bcf95f-bf44-4a30-97be-31f4478ac114">
