### ISSUE TITLE
rusk-wallet version information

### ISSUE THREAD

**Issue by mcf-rocks** [dusk-network/rusk#2647]
Would it be possible to automatically update the rusk-wallet version information on build, in the same way it is done for rusk node?

currently it is always this:
```
# ./rusk-wallet -V
Dusk Wallet CLI 0.1.0
```

**Comment by HDauven** [comment]
We haven't released the "new" Rusk wallet yet since moving it into this repository. With the move, we've decided to start from version `0.1.0` again.
