### ISSUE TITLE
rusk-wallet: Rename Phoenix and Moonlight to Shielded and Public

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#2684]
#### Summary
Phoenix and Moonlight are internal technical names that do not say much about what these addresses do. In the web wallet we decided to hide these technical names from the user in the UI by referring to privacy-preserving accounts as shielded accounts and Moonlight to public accounts.

#### Possible solution design or implementation
The internal representation can change, but can still be considered addresses where valid. The primary goal of this issue is to provide simple and consistent naming for end-users in the UI.

**Comment by moCello** [comment]
closed by #2676
