### ISSUE TITLE
rusk-wallet: Support offline mode

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#2698]
To support offline mode in rusk-wallet we need to figure out how to create a `Transaction` using `wallet-core` and give the bytes serialized to the user then being able to serialize it later to prove or propogate the transaction

Some items might need to be cached to complete this functionality which includes
1. Storing the moonlight nonce in the rocksdb cache and using that as the nonce
2. Storing the contract deploy nonce? 
3. Anything else that needs to be stored

**Comment by moCello** [comment]
solved by #2719
