### ISSUE TITLE
Compile error from source code

### ISSUE THREAD

**Issue by COLUD4** [dusk-network/rusk#2699]
version: 0.7.0
rustc 1.75.0 (82e1608df 2023-12-21)

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/msgpacker-0.4.3/src/lib.rs:3:5
  |
3 |     iter_array_chunks,
  |     ^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/msgpacker-0.4.3/src/lib.rs:4:5
  |
4 |     maybe_uninit_array_assume_init,
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/msgpacker-0.4.3/src/lib.rs:5:5
  |
5 |     maybe_uninit_uninit_array
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^

   Compiling regex-syntax v0.8.5
   Compiling cc v1.1.30
For more information about this error, try `rustc --explain E0554`.
error: could not compile `msgpacker` (lib) due to 3 previous errors

**Comment by HDauven** [comment]
Please see the [README Rust installation](https://github.com/dusk-network/rusk?tab=readme-ov-file#rust-installation) instructions. 

You need to have Rust nightly installed and set for this project to run. You can also navigate to the Rusk folder and set a nightly override:
```bash
rustup override set nightly
```
