### ISSUE TITLE
Flickering while showing receive QR code

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#2725]
**Describe the bug**
We have a regression in the layout calculation made by the QR code component in the "receive" section.

An example is in the attached video, but I experienced situations where the visual bug is even more annoying.

https://github.com/user-attachments/assets/9dd54fab-d7b0-4a1c-b53e-098aa8d098cd

**Comment by nortonandreev** [comment]
I get a slightly different behavior on Safari, but still looks like a bug.


https://github.com/user-attachments/assets/d90fba74-8240-4231-8f64-a4f5941356ad
