### ISSUE TITLE
CLI  wallet unwanted  'this transaction is invalid Value spent larger than account holds'

### ISSUE THREAD

**Issue by sanderdms** [dusk-network/rusk#2783]
**Describe the bug**
When generating a transaction via CLI wallet the wallet seems to pro actively determine if transaction might fail or not.
I do not like this behavior because it is limiting me during development to quickly test certain scenario's 

(For example I was preparing to make a point around dealing with bigInts in REUS and GraphQL vs  w3sper)

**To Reproduce**
Execute command on wallet holding 10 000 tDUSK:
`rusk-wallet transfer --amt 1 --gas-price 1 --gas-limit 10000000000000000 --rcvr tSgKDULgpBT3AhnsWZM1KAmhBha1aEL5wgHh4bpvytjMTw5DLSCEFf3e8xpUfA3VAGn6RqmQGjMmZPuTtRDDySYbrBYZXo9dipF6Y5kGmo5K7cbeLp3UzmyrBNGBm83hD2t`

```
 Rusk error occurred: 500 Internal Server Error: this transaction is invalid Value spent larger than account holds
```

**Expected behaviour**
The transaction gets propagated to the network. 
I can use the CLI as a devtool and provoke mistakes / errors. 

**Logs/Screenshot**
If applicable, add damning logs

**Platform**
Fill as appropriate
 - Architecture: [ARM, 8086]
 - OS: [e.g. iOS, Linux]

**Additional context**

**Comment by HDauven** [comment]
Feel free to modify the CLI code base locally to create faulty transactions, this is what we do as well for testing. It doesn't make sense for us to deliver a faulty application to end-users.
