### ISSUE TITLE
web-wallet:  Add a label indicating gas fee payer for allocation transactions

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/rusk#2809]
Add a label that clearly states who is paying for gas while we change the shielded / unshielded allocation (if we release after next w3sper, otherwise move it to "next things").

**Comment by kieranhall** [comment]
Possibly add an info message to indicate which account will pay the gas fee.

**Comment by kieranhall** [comment]
Also display messaging in the review step.

**Comment by nortonandreev** [comment]
Updated Figma:

![Image](https://github.com/user-attachments/assets/e4c4e595-31d4-4534-9c2c-15cba4502787)

**Comment by nortonandreev** [comment]
I think here we should be dynamic – if from shielded to unshielded, the from should be the shielded with the proper icon, and vice-versa.

Is the fee then always paid from the "from" account?

cc: @ascartabelli @ZER0

**Comment by ascartabelli** [comment]
The fee is always paid by the "from" account.

**Comment by nortonandreev** [comment]
> The fee is always paid by the "from" account.

Yeah, that's my understanding too! Coolio!
