### ISSUE TITLE
Web-Wallet - transaction fails + migrate contract already available?

### ISSUE THREAD

**Issue by Rikkie82** [dusk-network/rusk#2871]
**Describe the bug**
trying to make a phoenix transactions results in error

**To Reproduce**
follow the workflow in web-wallet

**Expected behaviour**
TX is send to chain and funds are transferred

**Logs/Screenshot**
![send error](https://github.com/user-attachments/assets/0c72c2ba-5fcd-4d13-9d81-f89bdcfb64a8)

**Platform**
Windows 11 Home 23H2
Chrome - Versie 129.0.6668.90 (Officiële build) (64-bits)

**Additional context**

**Comment by Rikkie82** [comment]
![migration contract](https://github.com/user-attachments/assets/d4dbae07-c9e3-4c66-8501-ea8810895a4d)
also migration contract is available already, any risk for people to loose funds if they try it?

**Comment by nortonandreev** [comment]
Hey man – on the first point – this should now be fixed. Could you please try again?

Thanks!

**Comment by nortonandreev** [comment]
On the second one – indeed. We have disabled this now.

Thanks for bringing it up! 🙏

**Comment by Rikkie82** [comment]
> Hey man – on the first point – this should now be fixed. Could you please try again?
> 
> Thanks!

works fine now, slight waiting time to have it included in block, when you click show explorer it first gives error (guess explorer needs to update in background), after few refreshes it shows the page (however timestamp shows 3-minutes ago), while it did not take that long...

**Comment by nortonandreev** [comment]
> > Hey man – on the first point – this should now be fixed. Could you please try again?
> > Thanks!
> 
> when you click show explorer it first gives error

Yeah, we will update the explorer to improve the experience around this. The problem is that the explorer doesn't show the transactions in the mempool – so it takes some time until it's available on the Explorer.

**Comment by ascartabelli** [comment]
@Rikkie82
As @nortonandreev said we are working on having the explorer check the mempool when you visit a transaction link (https://github.com/dusk-network/rusk/issues/2877).
If you don't have problems anymore can we consider this closed?

**Comment by Rikkie82** [comment]
yeah can be closed imo

**Comment by Rikkie82** [comment]
fixed and/or explained
