### ISSUE TITLE
Add checks before considering a tx link broken

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#2877]
When a transaction is created both the web-wallet and the wallet-cli will create a link to see the transaction in the explorer using its hash, but when the link is created the transaction can, for example, still be in the mempool and currently the explorer shows the link as broken.

The explorer should check the mempool and see if the transaction's hash is there and warn the user that the transaction isn't available yet, but it will soon.

If the transaction isn't in the mempool (yet) the error message should convey to the user the possibility that the link could be valid (especially if he just made a transaction), but he has to retry in a few moments.

**Comment by kieranhall** [comment]
Would it make sense to pick this up after w3sper is integrated in the explorer?

**Comment by ascartabelli** [comment]
> Would it make sense to pick this up after w3sper is integrated in the explorer?

I would pick it up even before, but then with w3sper we can improve the UX of course.
