### ISSUE TITLE
Set up an auto-sync every 5 minutes

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#2880]
#### Summary

Right now we can't reliably use events to trigger a sync when we receive money, so as a temporary measure we should set up an auto-sync feature every 5 minutes.

In the near future if the situation remain as above we can add a setting so that the user can pick his favourite auto-sync interval.

**Comment by nortonandreev** [comment]
<img width="269" alt="Screenshot 2024-11-06 at 12 33 35" src="https://github.com/user-attachments/assets/ff9e543b-84ec-43d8-bb88-7bf0dd2c3563">

I am wondering if we can't do something with this status indicator and have it act as a refresh trigger, similarly to how we have it if the sync fails? So then users can trigger a sync on-demand.
