### ISSUE TITLE
Wallet said 'mainnet' while its on testnet

### ISSUE THREAD

**Issue by sanderdms** [dusk-network/rusk#2900]
**Describe the bug**

**To Reproduce**
if applicable add a *minimum reproducible example*

```
// Be exhaustive
// 
```

**Expected behaviour**

**Logs/Screenshot**
If applicable, add damning logs

**Platform**
Fill as appropriate
 - Architecture: [ARM, 8086]
 - OS: [e.g. iOS, Linux]

**Additional context**

**Comment by ascartabelli** [comment]
The wallet right now uses the URL is served from to deduce the network, instead of the node it's connected to: this will be fixed by https://github.com/dusk-network/rusk/issues/2870
