### ISSUE TITLE
web-wallet: unexpected screen order when using the 'shield more' and 'back' button

### ISSUE THREAD

**Issue by UglyDuskling** [dusk-network/rusk#2941]
I think this can be considered pretty annoying:

1. Go to send screen
2. Put in an address to send to
3. Get curious about the `SHIELD MORE DUSK` button and press it
4. Press `BACK`
5. You're back at the home screen

I would expect it to go back to the send screen where I had already done the hard work of inserting the address. The back button is not really functioning like a back button in this scenario.

---

Personally I'm not convinced on the `SHIELD MORE DUSK` button workflow, because the information at the top of the screen is the same on both the home screen and the send screen, so you should have already made your decision (a single button press) before reaching this point.

**Comment by nortonandreev** [comment]
That's now resolved, as we have decided to move the Shield More Dusk CTA so as to resolve usability concerns like this one.
