### ISSUE TITLE
web-wallet: Phoenix balance goes to zero after send and unshield operations on iOS 18.x+

### ISSUE THREAD

**Issue by Fulviuus** [dusk-network/rusk#2966]
**Describe the bug**
On Apple devices on iOS 18+, unshielding or sending Phoenix transactions causes the balance to show zero.
A subsequent sync brings back the balance to the correct value.

**To Reproduce**
Load the wallet on an iOS device running iOS 18+, unshield Dusk or send a Phoenix TX out.

**Expected behaviour**
The balance should not drop to zero after sending a Phoenix transaction, or unshielding Dusk.

**Logs/Screenshot**

https://github.com/user-attachments/assets/e6e48ea2-b3cb-4702-926e-0262bb293277

**Platform**
Fill as appropriate

 - OS: iOS 18+
 - Browser: Safari

**Comment by ascartabelli** [comment]
Hopefully fixed by https://github.com/dusk-network/rusk/pull/2973, but waiting for more confirmations before closing this one.
