### ISSUE TITLE
Broken link in the stake warning

### ISSUE THREAD

**Issue by ascartabelli** [dusk-network/rusk#2990]
**Describe the bug**
Before staking the web-wallet warns the user and suggests a link on how to setup a node.

The suggested link (https://docs.dusk.network/getting-started/node-setup/overview/) is broken, and should probably point to: https://docs.dusk.network/operator/overview/

**Comment by nortonandreev** [comment]
Should we go with what you have suggested (which has outdated links, btw, have opened an issue here https://github.com/dusk-network/docs/issues/188) or should we go with https://docs.dusk.network/operator/guides/01-nocturne-node/?


Which one would you suggest using, @HDauven? 
For context, this is a warning in the stake flow, and asks users to set up a node before proceeding with the stake. I guess, both local and as a DO droplet would do the job – so potentially either links can be used. But the DO droplet one seems less involved and also is a direct step-by-step tutorial.

**Comment by ascartabelli** [comment]
> Should we go with what you have suggested (which has outdated links, btw, have opened an issue here [dusk-network/docs#188](https://github.com/dusk-network/docs/issues/188)) or should we go with https://docs.dusk.network/operator/guides/01-nocturne-node/?

Don't know, really I just made a quick guess: probably @HDauven knows best.

**Comment by HDauven** [comment]
@ascartabelli @nortonandreev this is the best resource to use if we're talking about staking in general: https://docs.dusk.network/operator/02-provisioner/

It links to the guide detailing how to run a node on Nocturne
