### ISSUE TITLE
web-wallet: Use w3sper's minStake Amount Instead of Client-Side Environment Variable

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#3010]
### Description

Currently, the web app relies on a client-side environment variable to determine the minimum stake amount. However, we can now leverage w3sper's `minStake` value directly, ensuring consistency and reducing reliance on hardcoded values in the client.

### Proposed Solution
- Replace the usage of the client-side environment variable with the `minStake` value provided by `w3sper`.
- Update any logic, validations, or UI elements that reference the minimum stake amount to use the `w3sper` value.
- Add error handling to manage cases where the minStake value is unavailable or returns an invalid value.

### Additional Context
This change will help maintain alignment between the client and backend, improving the overall reliability of the staking process. Any dependencies on the environment variable should be identified and updated.

**Comment by ascartabelli** [comment]
See also https://github.com/dusk-network/rusk/issues/3017
