### ISSUE TITLE
Create a fixed size list for BlsScalar

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#316]
A list of `BlsScalar` where adding a new element will automatically discard the oldest one, once the capacity is reached. 

(see `root_list` of Transfer Contract)

> Note: ask @khovratovich

**Comment by ZER0** [comment]
This now can be very easily implemented using a `Vec` in Piecrust once it will be merged.

**Comment by herr-seppia** [comment]
This is required to transfer-contract in order to retain the last _N_ anchors, resulting in autoexpiring transactions
