### ISSUE TITLE
web-wallet: Stake transaction fails

### ISSUE THREAD

**Issue by dusktestoor** [dusk-network/rusk#3175]
**Describe the bug**
Stake transaction generated by web wallet fails.

**To Reproduce**
if applicable add a *minimum reproducible example*

1. Have a wallet with above 1002.9 moonlight dusk
2. Go in stake panel
3. Click stake
4. Agree to terms
5. Set amount to 1000 dusk (default)
6. Set gas limit to 2.9 dusk (default)
7. Set gas price to 1 lux (default)
8. Click next and wait for transaction processing

**Be exhaustive**
Staking flow in the web wallet doesn't indicate any issues. Refers to explorer to check on transaction.
When checking transaction we see that it failed with following reason 'Panic: Argument should correctly deserialize: CheckBytesError(StructCheckError { field_name: "keys", inner: StructCheckError { field_name: "owner", inner: InvalidTag(233) } })'

**Expected behaviour**
Transaction doesn't fail

**Logs/Screenshot**
If applicable, add damning logs

Config:
![image](https://github.com/user-attachments/assets/1c6a37f6-082b-4483-8ab3-be6eb057c069)

Payload:
{
  "type": "moonlight",
  "sender": "pQpp6ctzgcmWobvPY3ykq9XfxcGeDnnmSiAWSBtobXoBB53LXhnBsQJxPLUGQi5Uk83AmNXKpx65oZFEmUsgS9kXrMx8cDfvmFcNenzpJrfgTnv6enhndZkkV9RbDn3PjUu",
  "receiver": null,
  "value": 0,
  "nonce": 5,
  "deposit": 1000000000000,
  "fee": {
    "gas_limit": "2900000000",
    "gas_price": "1",
    "refund_address": "pQpp6ctzgcmWobvPY3ykq9XfxcGeDnnmSiAWSBtobXoBB53LXhnBsQJxPLUGQi5Uk83AmNXKpx65oZFEmUsgS9kXrMx8cDfvmFcNenzpJrfgTnv6enhndZkkV9RbDn3PjUu"
  },
  "call": {
    "fn_name": "stake",
    "contract": "0200000000000000000000000000000000000000000000000000000000000000",
    "fn_args": "6U3t3dezaW6AouxSa5RaMVONpu3NScEW4/PC4Tmd+IoDquB02i2qwCcFLoWsrd8VeWoe4wo8ouds8QNw2AlXkwwy1Ql05HWgBPJ9P9/AZSpLvx2Yv3RVb4uAvM/P76oCxPe602mH4fl4EiXlU6qhLNLA+uopBAEFw4j7yAi7WBGXokEHDMJ/zAyfMdprtKsNCdHedUB+PpcsX1h7a63OKx3hY1LmgRgTRKxtI9E/Of+WPYVEGjLlGJHEOJVskqgXAAAAAAAAAADpTe3d17NpboCi7FJrlFoxU42m7c1JwRbj88LhOZ34igOq4HTaLarAJwUuhayt3xV5ah7jCjyi52zxA3DYCVeTDDLVCXTkdaAE8n0/38BlKku/HZi/dFVvi4C8z8/vqgLE97rTaYfh+XgSJeVTqqEs0sD66ikEAQXDiPvICLtYEZeiQQcMwn/MDJ8x2mu0qw0J0d51QH4+lyxfWHtrrc4rHeFjUuaBGBNErG0j0T85/5Y9hUQaMuUYkcQ4lWySqBcAAAAAAAAAAHXOfyoqGCwHvn35OQBPEJQZIGPNoRXZAvBZ33qKhjJ7Qjm+4ei7i+AIj3MDasCqBJsQWLdvtkHASWn77kl96LQ7obHACMv752u+miK3ufj4iVq8O73W7/F36kcBiIYyDAAAAAAAAAAAdc5/KioYLAe+ffk5AE8QlBkgY82hFdkC8FnfeoqGMntCOb7h6LuL4AiPcwNqwKoEmxBYt2+2QcBJafvuSX3otDuhscAIy/vna76aIre5+PiJWrw7vdbv8XfqRwGIhjIMAAAAAAAAAAAAEKXU6AAAAAEAAAAAAAAAAgAAAAAAAAA="
  },
  "is_deploy": false,
  "memo": null
}

Error:
![image](https://github.com/user-attachments/assets/57572ca1-df8c-47b2-8840-fba887021974)
![image](https://github.com/user-attachments/assets/681cdcd9-0edf-4bbf-bcaf-632f36b7320c)

**Platform**
Web wallet version v0.9.0
Browser - Mozilla

**Additional context**

I saw reports of other users having the same issue.
People also reported that staking works properly from cli wallet

**Comment by borjasdee** [comment]
Hi there,

I attempted to reproduce your issue and was unable to do so.

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Dusk Network Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can also search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by HLeach-Tech** [comment]
> **Describe the bug** Stake transaction generated by web wallet fails.
> 
> **To Reproduce** if applicable add a _minimum reproducible example_
> 
> 1. Have a wallet with above 1002.9 moonlight dusk
> 2. Go in stake panel
> 3. Click stake
> 4. Agree to terms
> 5. Set amount to 1000 dusk (default)
> 6. Set gas limit to 2.9 dusk (default)
> 7. Click next and wait for transaction processing
> 
> **Be exhaustive** Staking flow in the web wallet doesn't indicate any issues. Refers to explorer to check on transaction. When checking transaction we see that it failed with following reason 'Panic: Argument should correctly deserialize: CheckBytesError(StructCheckError { field_name: "keys", inner: StructCheckError { field_name: "owner", inner: InvalidTag(233) } })'
> 
> **Expected behaviour** A clear and concise description of what you expected to happen. Transaction doesn't fail
> 
> **Logs/Screenshot** If applicable, add damning logs
> 
> including payload: { "type": "moonlight", "sender": "pQpp6ctzgcmWobvPY3ykq9XfxcGeDnnmSiAWSBtobXoBB53LXhnBsQJxPLUGQi5Uk83AmNXKpx65oZFEmUsgS9kXrMx8cDfvmFcNenzpJrfgTnv6enhndZkkV9RbDn3PjUu", "receiver": null, "value": 0, "nonce": 5, "deposit": 1000000000000, "fee": { "gas_limit": "2900000000", "gas_price": "1", "refund_address": "pQpp6ctzgcmWobvPY3ykq9XfxcGeDnnmSiAWSBtobXoBB53LXhnBsQJxPLUGQi5Uk83AmNXKpx65oZFEmUsgS9kXrMx8cDfvmFcNenzpJrfgTnv6enhndZkkV9RbDn3PjUu" }, "call": { "fn_name": "stake", "contract": "0200000000000000000000000000000000000000000000000000000000000000", "fn_args": "6U3t3dezaW6AouxSa5RaMVONpu3NScEW4/PC4Tmd+IoDquB02i2qwCcFLoWsrd8VeWoe4wo8ouds8QNw2AlXkwwy1Ql05HWgBPJ9P9/AZSpLvx2Yv3RVb4uAvM/P76oCxPe602mH4fl4EiXlU6qhLNLA+uopBAEFw4j7yAi7WBGXokEHDMJ/zAyfMdprtKsNCdHedUB+PpcsX1h7a63OKx3hY1LmgRgTRKxtI9E/Of+WPYVEGjLlGJHEOJVskqgXAAAAAAAAAADpTe3d17NpboCi7FJrlFoxU42m7c1JwRbj88LhOZ34igOq4HTaLarAJwUuhayt3xV5ah7jCjyi52zxA3DYCVeTDDLVCXTkdaAE8n0/38BlKku/HZi/dFVvi4C8z8/vqgLE97rTaYfh+XgSJeVTqqEs0sD66ikEAQXDiPvICLtYEZeiQQcMwn/MDJ8x2mu0qw0J0d51QH4+lyxfWHtrrc4rHeFjUuaBGBNErG0j0T85/5Y9hUQaMuUYkcQ4lWySqBcAAAAAAAAAAHXOfyoqGCwHvn35OQBPEJQZIGPNoRXZAvBZ33qKhjJ7Qjm+4ei7i+AIj3MDasCqBJsQWLdvtkHASWn77kl96LQ7obHACMv752u+miK3ufj4iVq8O73W7/F36kcBiIYyDAAAAAAAAAAAdc5/KioYLAe+ffk5AE8QlBkgY82hFdkC8FnfeoqGMntCOb7h6LuL4AiPcwNqwKoEmxBYt2+2QcBJafvuSX3otDuhscAIy/vna76aIre5+PiJWrw7vdbv8XfqRwGIhjIMAAAAAAAAAAAAEKXU6AAAAAEAAAAAAAAAAgAAAAAAAAA=" }, "is_deploy": false, "memo": null }
> 
> ![image](https://private-user-images.githubusercontent.com/190636690/395279521-57572ca1-df8c-47b2-8840-fba887021974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjc1MTEsIm5iZiI6MTczNDAyNzIxMSwicGF0aCI6Ii8xOTA2MzY2OTAvMzk1Mjc5NTIxLTU3NTcyY2ExLWRmOGMtNDdiMi04ODQwLWZiYTg4NzAyMTk3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxODEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZWRkYzU3MmJiMTg2MGYyNjM5M2VmMDdmMGI5NWFhNTA4YjhjNTBkMzRjNTFjODQwNzU5YTRhNDQyN2Q1M2Q3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L_mk_Lz9HIXfEDb9V6nw_jLbLdOlFBRUmNxYjVckxVg) ![image](https://private-user-images.githubusercontent.com/190636690/395279669-681cdcd9-0edf-4bbf-bcaf-632f36b7320c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjc1MTEsIm5iZiI6MTczNDAyNzIxMSwicGF0aCI6Ii8xOTA2MzY2OTAvMzk1Mjc5NjY5LTY4MWNkY2Q5LTBlZGYtNGJiZi1iY2FmLTYzMmYzNmI3MzIwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMlQxODEzMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MmM4MTI5NmIwNjcwYTNiZmY1ZDU3ZmVmYzczNmY3MTkyMzZlYTBjZTA3ZTEyYTZlYTRhYWE0YmIyYjczNzk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nZU_cuz8CQhypkHiZWNbVNe9XnUj253Uq0QSOzlNs_M)
> 
> **Platform** Web wallet version v0.9.0 Browser - Mozilla
> 
> **Additional context** Add any other context about the problem here.
> 
> I saw reports of other users having the same issue. People also reported that staking works properly from cli wallet

Hello @dusktestoor 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID DUS120964 for rectification guidelines. 
Please use the following link to access our dedicated support line: 
[Web Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by borjasdee** [comment]
@HLeach-Tech
Kindly delete your post to avoid multiple requests. Thanks

**Comment by ascartabelli** [comment]
@dusktestoor can you please verify that on the wallet home page your build hash is `0efa2267`?
Right now I'm suspecting a cache problem as that error is the same you would get with an outdated wasm.

<img width="730" alt="Screenshot 2024-12-13 alle 07 00 03" src="https://github.com/user-attachments/assets/6dd21d5e-544c-4fe1-bb34-6c2ad755646e" />

**Comment by ascartabelli** [comment]
(and if the hash matches the one above, can you please try staking again?)

**Comment by ascartabelli** [comment]
@dusktestoor nevermind: it's not a cache problem.
99% you were accessing https://apps.dusk.network/wallet/ which wasn't deployed as a mirror of https://apps.testnet.dusk.network/wallet/ .

It is now, so please check that everything is fine: the new build hash is `418c4b65`.

**Comment by dusktestoor** [comment]
Thats correct i was accessing  https://apps.dusk.network/wallet/. The build is 418c4b65, retested now and it is successful.

**Comment by ascartabelli** [comment]
Ok, great, sorry for the inconvenience and thanks for the test.
