### ISSUE TITLE
rusk: Consider adjusting the deploy cost

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#3177]
#### Summary
Currently, deployment transactions have a minimal gas price set at 2000, and a gas per byte set at 100. Due to the substantial difference in gas cost between Moonlight and Phoenix transactions, Phoenix deployments are proportionally much more expensive. Where an empty contract deploy for Moonlight would cost 0.2 DUSK, a Phoenix transaction can easily cost 3 DUSK.

#### Possible solution design or implementation
To decrease the impact of the transaction type baseline cost, we can choose to shift the minimal gas price and gas per byte cost to a better optimum.

For example:
```rusk
const DEFAULT_GAS_PER_DEPLOY_BYTE: u64 = 1000;
const DEFAULT_MIN_DEPLOYMENT_GAS_PRICE: u64 = 200;
```

**Comment by miloszm** [comment]
I'd suggest:
```
const DEFAULT_MIN_DEPLOYMENT_GAS_PRICE: u64 = 400;
```
We cannot go too low with the limit because of the block gas limit.

**Comment by HDauven** [comment]
After discussions with @miloszm and @herr-seppia, and the introduction of #3210, we can keep the numbers as they are.
