### ISSUE TITLE
web-wallet: Align gas limit defaults with Rusk wallet

### ISSUE THREAD

**Issue by HDauven** [dusk-network/rusk#3178]
#### Summary
Currently the Web wallet sets a very high gas limit for any transaction of 2.9 DUSK. In the past, when staking operations were quite expensive, these numbers made sense. But since cost were [dramatically reduced](https://github.com/dusk-network/rusk/pull/2678), and we got more data on the cost of Phoenix and Moonlight transactions, we should lower the default to a more appropriate value. 

Why should we do this? Because it will reduce the minimal balance users need and if a transaction fails they will lose less funds, as all failed transactions incur the full gas limit provided. 

#### Possible solution design or implementation
Either align the gas limit defaults to what is being used in Rusk wallet: https://github.com/dusk-network/rusk/blob/master/rusk-wallet/src/gas.rs#L14L27

Or set a safe default, like 50M LUX.

**Comment by ascartabelli** [comment]
@HDauven Updated the defaults as discussed in my PR linked to this issue and changed env variables in all our apps online.

Created this one to fully tackle the issue you reported: https://github.com/dusk-network/rusk/issues/3201

**Comment by HDauven** [comment]
> @HDauven Updated the defaults as discussed in my PR linked to this issue and changed env variables in all our apps online.
> 
> Created this one to fully tackle the issue you reported: #3201

Awesome, thank you!
