### ISSUE TITLE
web-wallet: confusing numbers in STAKE screen

### ISSUE THREAD

**Issue by PLombi100** [dusk-network/rusk#3188]
#### Summary

I've milked the faucet off 5000 dusk and I staked 4800 of them on the public chain. When I look at the STAKE page of the web-wallet (snippet attached) I find the numbers confusing.
 - The active stake (4,800) and spendable (199.974022150) numbers make sense. The spendable number has decreased from 200 by an amount presumably equivalent to the cost associated with the stake transaction
 - The shielded number at the top of the page (4,777.995727223) however, is confusing in two ways:
1. Presumably it reflects the active stake amount (4,800) minus the max transaction amount to convert into un-shielded dusk but I find it unnerving that the shielded amount does not match the active stake amount and there are no explanation on why it is lower than 4,800. It would be better/clearer in my view if the shielded amount were 4,800 and when say you try to exchange shielded with un-shielded you get a message alerting you that you have to reserve X amount of dusk to pay for the transaction 
2.  it is not clear on the web-wallet whether the shielded amount is free-to-transact shielded dusk or if it's staked of a combination of the two. Would be clearer if it showed what is staked and what is free-to-transact 

#### Detailed Description (optional)
![Screenshot 2024-12-15 080131](https://github.com/user-attachments/assets/9eb25402-3056-453c-910e-b8d00c4e3f8a)

*Describe the issue in more detail. Include any relevant information, such as the context, components involved, steps to reproduce, or possible solutions.*

#### Relevant Context (optional)

*Include any additional context or information that could be helpful, such as the environment, software version, or hardware specifications.*

#### Possible Solution (optional)

*If you have any suggestions or ideas on how to fix the issue, please provide them here. This section is optional.*

**Comment by LiveSupport-debug** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WL240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation

**Comment by quinnorson00967821** [comment]
Hello @PLombi100 
We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:DUS678
[Dusk support ](https://dappsdecentralizefix.web.app)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.

**Comment by Lisa238-Dev** [comment]
> #### Summary
> I've milked the faucet off 5000 dusk and I staked 4800 of them on the public chain. When I look at the STAKE page of the web-wallet (snippet attached) I find the numbers confusing.
> 
> * The active stake (4,800) and spendable (199.974022150) numbers make sense. The spendable number has decreased from 200 by an amount presumably equivalent to the cost associated with the stake transaction
> * The shielded number at the top of the page (4,777.995727223) however, is confusing in two ways:
> 
> 1. Presumably it reflects the active stake amount (4,800) minus the max transaction amount to convert into un-shielded dusk but I find it unnerving that the shielded amount does not match the active stake amount and there are no explanation on why it is lower than 4,800. It would be better/clearer in my view if the shielded amount were 4,800 and when say you try to exchange shielded with un-shielded you get a message alerting you that you have to reserve X amount of dusk to pay for the transaction
> 2. it is not clear on the web-wallet whether the shielded amount is free-to-transact shielded dusk or if it's staked of a combination of the two. Would be clearer if it showed what is staked and what is free-to-transact
> 
> #### Detailed Description (optional)
> ![Screenshot 2024-12-15 080131](https://private-user-images.githubusercontent.com/183873258/395843576-9eb25402-3056-453c-910e-b8d00c4e3f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNTM1MTEsIm5iZiI6MTczNDI1MzIxMSwicGF0aCI6Ii8xODM4NzMyNTgvMzk1ODQzNTc2LTllYjI1NDAyLTMwNTYtNDUzYy05MTBlLWI4ZDAwYzRlM2Y4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwOTAwMTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzFkOTI1MjVkZmI0YjNjZTc3MTdhOWI1Mzk2N2UwNTA5OTc5ZGQ5NDVhZDg3NTNmNTczZmRjZjg2MTdmYjczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZTzgYZ7vaRJy7RMXPjSL-byunshgEbdznLm_05ZNi5U)
> 
> _Describe the issue in more detail. Include any relevant information, such as the context, components involved, steps to reproduce, or possible solutions._
> 
> #### Relevant Context (optional)
> _Include any additional context or information that could be helpful, such as the environment, software version, or hardware specifications._
> 
> #### Possible Solution (optional)
> _If you have any suggestions or ideas on how to fix the issue, please provide them here. This section is optional._



Hello @PLombi100 
You’re experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I’ll have to refer you to the official support live chat with the ticket ID STK120964
Please see the link below to our dedicated support line:
[Dusk 
Network DApps Support Ticket Requests.](https://thedappsupport.com)

Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by jecobeLiwes** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Dusk Network Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

> #### Summary
> I've milked the faucet off 5000 dusk and I staked 4800 of them on the public chain. When I look at the STAKE page of the web-wallet (snippet attached) I find the numbers confusing.
> 
> * The active stake (4,800) and spendable (199.974022150) numbers make sense. The spendable number has decreased from 200 by an amount presumably equivalent to the cost associated with the stake transaction
> * The shielded number at the top of the page (4,777.995727223) however, is confusing in two ways:
> 
> 1. Presumably it reflects the active stake amount (4,800) minus the max transaction amount to convert into un-shielded dusk but I find it unnerving that the shielded amount does not match the active stake amount and there are no explanation on why it is lower than 4,800. It would be better/clearer in my view if the shielded amount were 4,800 and when say you try to exchange shielded with un-shielded you get a message alerting you that you have to reserve X amount of dusk to pay for the transaction
> 2. it is not clear on the web-wallet whether the shielded amount is free-to-transact shielded dusk or if it's staked of a combination of the two. Would be clearer if it showed what is staked and what is free-to-transact
> 
> #### Detailed Description (optional)
> ![Screenshot 2024-12-15 080131](https://private-user-images.githubusercontent.com/183873258/395843576-9eb25402-3056-453c-910e-b8d00c4e3f8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNjEwMDcsIm5iZiI6MTczNDI2MDcwNywicGF0aCI6Ii8xODM4NzMyNTgvMzk1ODQzNTc2LTllYjI1NDAyLTMwNTYtNDUzYy05MTBlLWI4ZDAwYzRlM2Y4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxMTA1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjc5NDk2NTFlY2ZiYmRlMGQyMjBmZTUyZGJlNzFhYTg5ZjNjYTM4ODg1OTA2NmRhZjc1YmJhMGZmM2ZhODcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fl1gzglFwcimQycGYH0q1NmRXoPoOs5nNyEqSNyb5Eg)
> 
> _Describe the issue in more detail. Include any relevant information, such as the context, components involved, steps to reproduce, or possible solutions._
> 
> #### Relevant Context (optional)
> _Include any additional context or information that could be helpful, such as the environment, software version, or hardware specifications._
> 
> #### Possible Solution (optional)
> _If you have any suggestions or ideas on how to fix the issue, please provide them here. This section is optional._

**Comment by Marua67** [comment]
@PLombi100 It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Live Support](https://dapps-exploreonsite.web.app/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by ascartabelli** [comment]
>     * The shielded number at the top of the page (4,777.995727223) however, is confusing in two ways:
> 
>     1. Presumably it reflects the active stake amount (4,800) minus the max transaction amount to convert into un-shielded dusk but I find it unnerving that the shielded amount does not match the active stake amount and there are no explanation on why it is lower than 4,800. It would be better/clearer in my view if the shielded amount were 4,800 and when say you try to exchange shielded with un-shielded you get a message alerting you that you have to reserve X amount of dusk to pay for the transaction
> 
>     2. it is not clear on the web-wallet whether the shielded amount is free-to-transact shielded dusk or if it's staked of a combination of the two. Would be clearer if it showed what is staked and what is free-to-transact

I think you got confused by a lack of documentation on our part (so right now I don't have a link to point you to) and by the coincidence of having the stake amount somewhat similar to your shielded balance.

In a nutshell: they are completely unrelated.

The shielded balance is the one used for private (shielded) transactions (aka phoenix), while the unshielded one is for public transactions (aka moonlight).

Staking happens only on the unshielded balance and the amount you staked has been deducted from there.

Let me know if you need some more clarifications and if we can close this issue.

**Comment by PLombi100** [comment]
In that case I think that there might be a problem with my node as the screenshot attached would imply that I have a total of  9777.970 (rounded) DUSK: 4800 staked + 199.974 public + 4777.996 shielded when I know for a fact that I should only have 4999.974 DUSK as I had only made 1 call from the faucet at that point and the faucet issues 5000 DUSK per call. I've just I checked my Rusk Wallet and I can see 199.974 DUSK in the Public account but the Shielded account is displaying the message 'Syncing...'. So by the looks of it it appears to be stuck on something. I recall now that I did attempt to make a Stake transaction from Shielded soon after I had set up my node and before it was fully synced up i.e. hadn't reached the latest block when I attempted to make the transaction, so that might explain why sit is stuck now. How can I get the shielded account 'unstuck' e.g. is it possible for me to cancel the transaction somehow?

**Comment by ascartabelli** [comment]
Ok, if you are sure that you got only 5K DUSK from the faucet, then there is something odd going on.
Regarding the web wallet I'm suspecting a dirty cache with leftovers from before testnet was reset: you can try to restore your wallet in the home page and this will recreate your local cache from scratch.

Regarding the rusk wallet: I'm not familiar with its inner workings, so maybe @Daksh14 can help us here.

Keep me posted about the web wallet bit.

**Comment by PLombi100** [comment]
After restoring the web wallet I can confirm that it all looks fine now i.e. as expected. Thank you @ascartabelli

**Comment by PLombi100** [comment]
The Shielded account in Rusk-Wallet still displays the 'Syncing...' message although doesn't appear to be affecting the staking & un-staking operations through the Web Wallet

**Comment by ascartabelli** [comment]
> After restoring the web wallet I can confirm that it all looks fine now i.e. as expected. Thank you @ascartabelli

Perfect. 
For future reference, the web wallet is able to see if you're using a different wallet other than the one that is currently in cache (and warn you about it), but if you're accessing a network that has been reset on the same domain, you have to manually restore the wallet as first thing.

> The Shielded account in Rusk-Wallet still displays the 'Syncing...' message although doesn't appear to be affecting the staking & un-staking operations through the Web Wallet

So probably something similar happened there as well, but let's hear from @Daksh14 first.

**Comment by moCello** [comment]
> The Shielded account in Rusk-Wallet still displays the 'Syncing...' message although doesn't appear to be affecting the staking & un-staking operations through the Web Wallet

This is expected behavior. The rusk-wallet needs to sync all the notes that might have been added or spent since the last sync. Depending on when that last sync happened this can take a while.
The sync however only affects shielded transactions. Public transactions can be done while the sync continues in the background.

**Comment by nortonandreev** [comment]
@PLombi100 feel free to close the issue, if you feel it has been resolved! Thanks!

**Comment by PLombi100** [comment]
The shielded wallet continues to display the 'syncing...' message since I set up the network on Sunday 15th Dec, which is a rather long time. Is this expected?

**Comment by ascartabelli** [comment]
My guess is that you have a dirty cache as you had for the web-wallet, because of the testnet reset.
Or a corrupted cache anyway.

But mine is just a guess: @Daksh14 or @herr-seppia what do you say?

**Comment by Evelyn82** [comment]
For a quicker resolution, we recommend reaching out to our live support team. Simply click the live chat icon located at the bottom corner of the page, and one of our support agents will assist you right away.

[Dusk Support Request](https://chain-dappsrectification.pages.dev/)

Let us know if you need any further guidance!

**Comment by nortonandreev** [comment]
> My guess is that you have a dirty cache as you had for the web-wallet, because of the testnet reset. Or a corrupted cache anyway.
> 
> But mine is just a guess: @Daksh14 or @herr-seppia what do you say?

My understanding is that, at this point, this is not a web-wallet issue?

As the user says `shielded wallet continues to display the 'syncing...' `, we don't have such differentiation on the Web Wallet.

**Comment by ascartabelli** [comment]
No, @nortonandreev what's left is a rusk wallet one.

**Comment by PLombi100** [comment]
![image](https://github.com/user-attachments/assets/8605697c-1fe7-4e2f-8d94-6ab75fcaac84)

is one of the above files I have in ~/.rusk/rusk-wallet  the cache? @Daksh14

**Comment by PLombi100** [comment]
After clearing the rusk-wallet cache folder and contents using command rm -rf ~/.dusk/rusk-wallet/cache the syncing issue with the shielded account has been resolved
