### ISSUE TITLE
Question: Interested in developing smart-contract for Dusk using Rust

### ISSUE THREAD

**Issue by FrankC01** [dusk-network/rusk#321]
Very recently made aware of Dusk and I'm looking for any documentation that can help me get going writing smart contracts in Rust as well as details (constraints, costs, etc.) I need to be aware of to deploy/run contracts.

Secondly - Is it feasible to use Dusk/Rusk as a platform for NFTs?

cc @arthurgreef

**Comment by HDauven** [comment]
Not yet. You can track issue #870 for this.

On your second question, yes.
