### ISSUE TITLE
Add minimum deployment gas points setting

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#3210]
#### Summary
We need protection against a possibility of deploying a large number of very small contracts while spending a relatively small amount of DUSK. There should be a minimum expense for deploying a contract, even if size of the contract is very small.
Suggested threshold is minimum 10 DUSK per any deployment.

#### Possible solution design or implementation
Introduce a new system setting MIN_DEPLOY_POINTS and DEFAULT_MIN_DEPLOY_POINTS, the latter set to 5000000 (5 million) gas points. This will induce a minimum deployment cost of 10 DUSK. Rename other deployment settings so that they are consistent, meaning, use a word `deploy` rather than deployment` in their names.
A deployment charge ought to be is calculated as:
```
max(size_of_contract_in_bytes * gas_per_deploy_byte, min_deploy_points)
```

#### Additional context
This issue is a top priority

**Comment by herr-seppia** [comment]
Resolved by #3210
