### ISSUE TITLE
Web wallet failed sync - Invalid mnemonic phrase

### ISSUE THREAD

**Issue by voidsculptorart** [dusk-network/rusk#3226]
**Description**
When the user tries to log into a web wallet when the web wallet can't sync with the node and gets an internal server error from the node, the wrong error message "Invalid mnemonic phrase" is shown to the user (even though the mnemonic did previously work).

**Steps To Reproduce**
When a user tries to log into a web wallet with the mnemonic (without a password), the node must return an internal server error to the web wallet, when the wallet tries to sync.

**Error Screenshots**
The internal server error popped up after the log in was successful but before the sync was performed:
![image](https://github.com/user-attachments/assets/c235b832-671c-406b-acd1-3821c66af285)

After trying to log in again, a wrong "Invalid mnemonic phrase" error is shown:
![image](https://github.com/user-attachments/assets/9c99bb41-107a-4384-a60c-2b01a6205ee6)

If the dev console is open when trying to log in, the error below pops up. After continuing, the invalid mnemonic error pops up again, so they seem linked:
![image](https://github.com/user-attachments/assets/30282337-b9e1-482b-b28b-31718b4cddfa)

**Expected Behaviour**
The user should be able to log in without the node working, see the cached balance, but the "Failed sync" error message should be shown at the bottom of the main page:
![image](https://github.com/user-attachments/assets/8b930232-de6a-433c-a76b-129079229598)

If it's too difficult to let the user log in without the node, the error should say something like "Can't connect to blockchain":
![image](https://github.com/user-attachments/assets/93b61a42-8651-4671-913e-42aba11eb3b4)

**Platform**
Brave desktop browser (normal tab, not private)

**Comment by hanKah37De** [comment]
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[DuskNetwork Support Request](https://chain-dappsrectification.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by ascartabelli** [comment]
@voidsculptorart The "offline wallet" is in our plans, and I'll open a PR soon to show the correct error instead of the "invalid mnemonic" one.
We're still investigating the error about the protocol driver not being loaded you experienced instead.

**Comment by ascartabelli** [comment]
The error about the protocol driver not being loaded has been addressed here https://github.com/dusk-network/rusk/pull/3240
