### ISSUE TITLE
Web wallet failed sync - Failed MANUAL sync doesn't show error

### ISSUE THREAD

**Issue by voidsculptorart** [dusk-network/rusk#3260]
Not applicable since fix for previous issue wasn't deployed.

**Comment by voidsculptorart** [comment]
The wallet started to behave differently, so I thought that a fix was deployed, but it looks like there wasn't any. It seems that the issue has slightly different behaviors at various times.

I'll just added the new information as a comment to https://github.com/dusk-network/rusk/issues/3227

This issue can be deleted / closed.

**Comment by ascartabelli** [comment]
Duplicate of https://github.com/dusk-network/rusk/issues/3227
