### ISSUE TITLE
web-wallet: Remove margin from Welcome Layout (Loading/Error States)

### ISSUE THREAD

**Issue by nortonandreev** [dusk-network/rusk#3271]
<img width="835" alt="Screenshot 2024-12-21 at 20 35 39" src="https://github.com/user-attachments/assets/6d2e424a-3774-44c9-839c-1af2691f2b40" />

<img width="734" alt="Screenshot 2024-12-21 at 18 19 22" src="https://github.com/user-attachments/assets/fa487483-3168-48bf-8c60-1c5d8eefd034" />

No need for these to be `10dvh` from top – in the middle of nowhere. Either vertically-centered or top aligned positioning makes more sense.

**Comment by Troy674** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/github)

Ticket ID: WT240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
