### ISSUE TITLE
Deliver Genesis Contracts for Consensus

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#33]
Create the following contracts:

- Bid
- Stake
- Transfer

# About Transfer contract's circuits

_Transfer contract's circuits are a bit different since we need to provide all the possible permutation of the inputs._

As it was stated in the meeting: https://app.gitbook.com/@dusk-network/s/specs/~/drafts/-M9xtH8OPWUsiJtqSif1/rfc/minutes/phoenix-architecture-notes#circuit-set-for-phoenix-tx-model-and-dusk-token-vs-regular-tokens

>Phoenix related circuits will be stored in the Phoenix Lib. And we will open a low-prio issue in respect of implementing the logic to choose the appropriate circuit depending on the amount of Notes and the type of Token.

This includes:
- 5 unique circuits with 8 variants each for Dusk Token
- 4 unique circuits with 8 variants each for Regular Tokens

This would be addressed in different PRs
## Dusk Token
- Previous gadgets refactoring to work with PLONK_v0.1.0
- Gadgets coded and tested for the 5 unique circuits with a test for a particular circuit (doesn't matter which variant)
- Generation of the variants for all the 5 unique circuits with a Macro or a similar technique that allows us to not re-write code. (I envision this as a macro that iterates over the gadgets X ammount of times depending on the amount of Notes that the Tx contains). 
- Generation of the serialized `PreProcessedCircuit`s for each variant of each unique circuit.
- Implement a method (that has to be in consensus with the SC platform team and the VM team) that allows to pick a circuit according to the Note number in order to **elaborate a proof** or **validate a proof**.

### Regular Dusk Token.
- Gadgets coded and tested for the 5 unique circuits with a test for a particular circuit (doesn't matter which variant)
- Generation of the variants for all the 5 unique circuits with a Macro or a similar technique that allows us to not re-write code. (I envision this as a macro that iterates over the gadgets X ammount of times depending on the amount of Notes that the Tx contains). 
- Generation of the serialized `PreProcessedCircuit`s for each variant of each unique circuit.
- Implement a method (that has to be in consensus with the SC platform team and the VM team) that allows to pick a circuit according to the Note number in order to **elaborate a proof** or **validate a proof**.

We should be able to share a lot of gadgets between Regular Tokens and Dusk Tokens even they will not be effectively the same and will not have the same final circuits. But I do think that the gadgets will be capable of be re-used a lot of times.

**Comment by ZER0** [comment]
Closing because this Epic was split in more atomic epics:

- https://github.com/dusk-network/rusk-vm/issues/92
- https://github.com/dusk-network/rusk/issues/167
- https://github.com/dusk-network/rusk/issues/168
