### ISSUE TITLE
transfer-contract: ensure some operation cannot be done to address `0x0`

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#331]
We shouldn't be allow to transfer from `0x0`, a simple `assert_eq` at the beginning of all methods that are not allowed would suffice: the method will panic, returning to the execute, and the gas consumed.

**Comment by herr-seppia** [comment]
@ZER0 Is this still relevant? We never check the "from" part, so we cannot check if "from=0x0"

**Comment by HDauven** [comment]
No longer considered relevant
