### ISSUE TITLE
Implement Bid Contract as 3rd party contract

### ISSUE THREAD

**Issue by ZER0** [dusk-network/rusk#370]
**Describe what you want implemented** 
The Bid Contract (and circuit) as 3rd party contract (instead of genesis contract).

**Describe "Why" this is needed**
With #366 we remove the bid contract from rusk repository. However, it's still a good candidate since it has the proper complexity, to see how a 3rd party contract could work and deployed on rusk. Hence, after the release of the VM 2 (with rkyv), we should try to implement again as 3rd party contract; it will be extremely helpful to test as developers our stack.

**Describe alternatives you've considered**
N/A

**Additional context**
The last version of bid contract and circuit can be found in [rusk v0.4](https://github.com/dusk-network/rusk/releases/tag/v0.4.0).

**Comment by carriercore** [comment]
hello, 
is there any team developers slack channel?

**Comment by ZER0** [comment]
Closing this issue since we're not using bid contract anyway.
