### ISSUE TITLE
Create a wallet abstraction

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#384]
**Describe what you want implemented** 
An implementation of a wallet that is abstract on the storage backend.

**Describe "Why" this is needed**
A wallet implementation is necessary for all platforms that should support cryptographic operations. This means, in this case, `rusk`, a `CLI` and the browser extension.

**Describe alternatives you've considered**
We considered 2 different options.
- One implementation for all - requiring FFI to be performed between WASM and the extension.
- Different implementations for all the different supported platforms. The amount of code here would make this unfeasible and make the interface brittle.

**Additional context**
This cuts through the entire stack - from UX to node, and VM to the CLI.

**Comment by herr-seppia** [comment]
@ureeves Is this fully resolved by dusk-network/wallet-core#5
