### ISSUE TITLE
schema: Add "go_package" option in .proto source files for Go generated code

### ISSUE THREAD

**Issue by t00ts** [dusk-network/rusk#386]
#### Describe what you want implemented
Add `go_package` option in every `.proto` schema source file.

#### Describe "Why" this is needed
With the latest (ever-changing) `protoc` spec and tool/plugin/addon suite, I've stumbled across the issue shown below. Essentially, when building for Go, protoc needs help to figure out the import paths and, consequently, package names.
```
protoc-gen-go: unable to determine Go import path for "echo.proto"

Please specify either:
        • a "go_package" option in the .proto source file, or
        • a "M" argument on the command line.

See https://developers.google.com/protocol-buffers/docs/reference/go-generated#package for more information.
```

#### Describe alternatives you've considered
We can ignore this and just keep using older versions of the toolkit, but we'll eventually have to update. Might as well do it now.

#### Additional context
Protoc:
```
% protoc --version
libprotoc 3.17.3
```

Addons for Go gRPC generation:
```
% go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.26
% go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.1
```

**Comment by herr-seppia** [comment]
Resolved using `-M` arg in command
https://github.com/dusk-network/dusk-protobuf/blob/9c0dc515d6d3169550b9deefbce3cc596a911d83/Makefile#L57-L66
