### ISSUE TITLE
Award gas fees to the block generator

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#428]
**Describe what you want implemented** 
`NetworkState` in `rusk-vm` gets a passed `GasMeter` allowing for a measurement of the gas consumed by each transaction. The amount consumed should be awarded to the block generator and possibly Dusk network.

**Describe "Why" this is needed**
This is part of the incentive mechanism to run a generator.

**Describe alternatives you've considered**
We considered appending new notes directly to the state after the transactions in the block are applied.

**Additional context**
We can use `get_contract_mut` to get the state of the transfer contract and mutate it in place.

**Comment by ureeves** [comment]
I'm of the opinion that this is closed by [PR #477- Add coinbase transactions](#477). Specifically one can take a look at the [lines in] `master`:

https://github.com/dusk-network/rusk/blob/77be09209a2f87b7e3b4d68b590baca48eb9ee45/rusk/src/lib/services/state.rs#L157-L161 

This mutates the state of the contract by appending two notes: one for the generator and one for the Dusk foundation, according to the [economic paper's](https://github.com/dusk-network/papers/blob/main/economic_paper/Dusk_Network_Economic_Paper.pdf) reward distribution.

I think one thing that remains that is related to this is the emission's schedule. We need to modify the [mint](https://github.com/dusk-network/rusk/blob/77be09209a2f87b7e3b4d68b590baca48eb9ee45/contracts/transfer/src/transfer/host.rs#L33-L38) function to emit notes of larger value according to the `block_height.

**Comment by vlopes11** [comment]
@ureeves can you clarify thy this part of the code will work for nodes that are not provisioners and are executing the state transition?

https://github.com/dusk-network/rusk/blob/77be09209a2f87b7e3b4d68b590baca48eb9ee45/rusk/src/lib/services/state.rs#L160

**Comment by ureeves** [comment]
@vlopes11 `ExecuteStateTransition` is called by the block generator to return execute transactions + coinbase transactions, not by anyone else. To ingest these transactions as a provisioner that is not the generator or any other node one can call `VerifyStateTransition`, `Accept`, or `Finalize`, where the transaction list already contains the coinbase.

**Comment by ureeves** [comment]
> @vlopes11 `ExecuteStateTransition` is called by the block generator to return execute transactions + coinbase transactions, not by anyone else. To ingest these transactions as a provisioner that is not the generator or any other node one can call `VerifyStateTransition`, `Accept`, or `Finalize`, where the transaction list already contains the coinbase.

This does mean that currently there's no real verification of the amount of the coinbase. This is a problem. I'll open an issue.

**Comment by vlopes11** [comment]
@ureeves I'm checking, and we shouldn't generate a deterministic RNG because that way the stealth address is compromised. As suggested in the calls, the `mint` should take a note generated by the block generator.

The problem is here: https://github.com/dusk-network/phoenix-core/blob/ffec0b6893e223fd64b40485294d61d8106762d5/src/note.rs#L87-L104

The `r` that composes the stealth address is generated with this RNG
