### ISSUE TITLE
Full Node API should be able to propagate transactions to the network

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#438]
**Describe what you want implemented** 
The full node API should be able to propagate the full transactions, with the PLONK proof, to the network

**Describe "Why" this is needed**
It is the whole point of the Full Node API

**Describe alternatives you've considered**
A suitable alternative would be for the Full Node API to return the proof+transaction to the requestor (web-wallet, cli-wallet, etc) and let them propagate the transaction to the network. This approach is roughly equal to the proposed implementation, but since it includes more work, it will be considered later on

**Comment by herr-seppia** [comment]
We decided to split the ProveAndPropagate in rusk to 2 different services
Prove is from ProverService and receive an UnprovenTransaction returning a Transaction
Propagate is a new method from NetworkService that send the tx to the network and to the node connected to rusk

The wallet API shall not change, they will continue to expose ProveAndPropagate to the clients. The wallet impl will take care to glue the 2 methods
