### ISSUE TITLE
Expose a pre-verification of a transaction

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#458]
**Describe what you want implemented** 
Expose a method that can be called by the node (e.g. gRPC) that will perform a preliminary verification on a transaction.

This preliminary verification will, using the components of the transaction:

- verify the `transfer/execute` ZK proof.
- assert none of the provided nullifiers already exists in the state of the transfer contract.

**Describe "Why" this is needed**
Before the transaction is added to the mempool and repropagated to the network, the node needs to verify that the transaction is valid. These two verifications will guarantee the transaction provider is able to pay for the runtime gas consumption of the transaction.

**Describe alternatives you've considered**
Not implementing this preliminary verification will allow attackers to flood the network with invalid transactions without paying any gas.

**Additional context**
N/A

**Comment by ZER0** [comment]
See also: #453 for the nullifiers implementation.

**Comment by autholykos** [comment]
See also #459
