### ISSUE TITLE
Avoid to use `map_err` to handle different errors

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#460]
**Describe what you want implemented** 
Using our own method in a struct, allows to return Result<WHATEVER> and then use the `?` to increase the code readability 

**Describe "Why" this is needed**
Ideally our code should deal directly with only one error in rusk, and it's crate::error::Error.

**Additional context**
Originally posted https://github.com/dusk-network/rusk/pull/451#discussion_r790814725 , https://github.com/dusk-network/rusk/pull/451#discussion_r790827331 and https://github.com/dusk-network/rusk/pull/451#discussion_r790833394

**Comment by OsDusk** [comment]
Unclear. `map_err()` is simplest way to transform from different original error types to one common target error type, in order to support `?` operator. How else to transform different errors into common target type?

**Comment by Daksh14** [comment]
@OsDusk I think they handling errors a little better. For example, https://github.com/dusk-network/rusk/pull/451/files/07eb895eaacb46a9ef007f7be28af85c20d123f8#diff-d8f809c0edf7d04ca5fd180735e4363d6cbfe10994736208dedce21a65eab114 

`map_err()` Usually is used when you want to ignore the `E` in `Result<_, E>` and replace it with something else.

**Comment by HDauven** [comment]
Outdated
