### ISSUE TITLE
Avoid generic `Null` stuff in proto

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#461]
We shouldn't have generic `Null` stuff in proto (you could use btw, the `Empty` from google if you really want to, but you shouldn't), since every method should have it's own arguments and return type, because if you decided to add return values or arguments we're not breaking the interface.
The only exception to this is if we have methods that are "alias" or "proxy" of other methods.

_Originally posted by @ZER0 in https://github.com/dusk-network/rusk/pull/451#discussion_r790819958_

**Comment by HDauven** [comment]
No longer relevant given we got rid of gRPC.
