### ISSUE TITLE
Make `NetworkState` thread safe

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#463]
**Describe what you want implemented** 
I want `NetworkState` to be safe to pass between threads.

**Describe "Why" this is needed**
`rusk` is currently doing some ad-hoc things that ensure the structure can be used in an  `async` context.

**Describe alternatives you've considered**
Using `Arc<Mutex<NetworkState>>` with `Arc` and `Mutex` from `std::sync` is likely to not be enough to make the structure performant, in a read heavy context.

Likely the best solution would be something similar to `tokio::sync::RwLock`.

**Additional context**
Since this is likely to require a lot of the functions of network state to be made `async` for anything but the most naive implementations, this is a major change unlikely to land on the short term.

**Comment by ZER0** [comment]
Non applicable anymore.
