### ISSUE TITLE
Stake state RPC

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#464]
**Describe what you want implemented** 
The stake value and expiration need to be exposed from the state. 

**Describe "Why" this is needed**
We need this to for the wallet to be able to perform stake transactions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by autholykos** [comment]
The state of the stake contract is a mapping of BLS public keys with the stake amount

**Comment by autholykos** [comment]
The verification of the stake transaction should check that the payload is a correct BLS public key

**Comment by herr-seppia** [comment]
https://github.com/dusk-network/bls12_381-sign/blob/8f07dad9fb56630e08672781017d39a44bd3e99e/rust/bls12_381-sign/src/keys/public.rs#L51
