### ISSUE TITLE
Bid Contract 

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#49]
As we know, one of the Genesis contracts is the `Bid Contract`.

It is in charge of placing the bids of the `bidders` inside of it's storage validating only the ones which are legitimate. 
It also verifies the proofs of correctness of the `Bids` and is in charge of allowing the extension of them.

Therefore, the Bid contract functional implementation does not imply only the Contract implementation "per se" but also the implementation of the helpers/features it will need to function within Rusk.

This Epic will encapsulate all of the issues that take part into that.

**Comment by ZER0** [comment]
Closing during triage round since redundant.
