### ISSUE TITLE
Allow the user to force a state reset

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#518]
Should we allow the user to force a state reset? I think this can be useful in dev environment and in cluster deployments too

Something like a `--force` flag to always delete (if exists) the previous state and build/download it according to the other flags passed

_Originally posted by @herr-seppia in https://github.com/dusk-network/rusk/pull/517#discussion_r797696206_

**Comment by ZER0** [comment]
This was already supposed to be implemented in the `rusk-recovery` tool (the `--overwrite` flag) so if we don't have a way anymore to do so it's a regression.
