### ISSUE TITLE
Implement all of the gadgets required by the Regular Token 4 unique circuits

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#56]
This issue lives inside the epic dusk-network/rusk#55.

We need to have all of the Gadgets required by the Regular Token 4 unique & different circuits in order to be able to generate the `PreProcessedCircuits` for each of these circuits.

My suggestions are:

- Start with the shorter gadgets and implement tests for them.
- Have 1 gadget per unique circuit which inside calls all of the "shorter gadgets" that needs to. And have tests for every one of these.
- Implement a test for the five gadgets of each circuit. It doesn't matter which of the 8 variants is done.

This implies that at the end, we will have a gadget for each Regular Token unique circuit. And then we will be able to obtain all of the `PreProcessedCircuits` for each one of the variants of those.
This last thing will be done in another issue.

**Comment by Bounce23** [comment]
Closing because this now lives in #57.
