### ISSUE TITLE
Stake results in `Out of gas` with almost `u64::MAX`

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#560]
**Describe the bug**
A stake transaction seems to result in an `Out of gas` even when the amount allotted is near `u64::MAX`. This is an problem since apparently no amount of Dusk can pay a stake transaction.

**To Reproduce**

Check out the [`stake-test`](https://github.com/dusk-network/rusk/tree/stake-test) branch and run the test from the root with `--nocapture`.

```sh
source .env
cd rusk
cargo t --release stake -- --nocapture
```

The result is printed in these lines in `execute_transactions`:

https://github.com/dusk-network/rusk/blob/da3d7573ddc4705324d533daf960af50f455d510/rusk/src/lib/services/state.rs#L133-L140

**Expected behaviour**
It should be expected that at least some amount of `gas < u64::MAX` will allow the transactor to stake.

**Logs/Screenshot**
N/A

**Platform**
N/A

**Additional context**
N/A

**Comment by autholykos** [comment]
This might be related to #551

**Comment by ureeves** [comment]
After further investigation I've found the culprit to be decoding the state from the given memory page in the stake contract.

https://github.com/dusk-network/rusk/blob/0a73b78e1cce3ecf532ddcf206727ecb4e3e7296/contracts/stake/src/wasm/bridge.rs#L43-L46

The `panic!` in line 46 is never reached, and we get knocked off the call with an `Out of gas`.

This seems to imply the contract is kept in the state in a corrupted way, or is loaded from the state wrong.

**Comment by ureeves** [comment]
Found the issue. `dusk-wallet-core` is not sending the correct arguments for the call. I'll create an issue there.
