### ISSUE TITLE
Allow for a Provisioner to have multiple stakes

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#579]
**Describe what you want implemented** 
A 1:N relationship between Provisioner (i.e. BLSPublicKey) and stake

**Describe "Why" this is needed**
With the current 1:1 relationship, a `Provisioner` willing to increase its stake is forced to unstake and restake

**Describe alternatives you've considered**
Leaving it as is

**Additional context**
See dusk-network/dusk-blockchain#1299

**Comment by herr-seppia** [comment]
Can we consider this obsolete?
