### ISSUE TITLE
Staking - Invalid coinbase in the block

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#589]
**Describe the bug**
`Invalid coinbase in the block` is raised processing a VST containing a skaking tx in the cluster

**To Reproduce**
Send a stake tx

**Expected behaviour**
It should not raise the error.

**Platform**

**Additional context**
Once the staking tx is in the mempool (pass the preverify) dusk-blockchain try to execute always, leading in a stale of the blockchain (No VSTs pass --> No blocks are created)
The tx is created/proved/broadcasted by a different nodes from the one who call the EST/VST

**Comment by ureeves** [comment]
After investigating this together with @herr-seppia and @ZER0, it turns out we were setting the block gas limit wrong, preventing some transactions from passing. We opened #591 to address part of this, the other is in [dusk-blockchain](https://github.com/dusk-network/dusk-blockchain/issues/1306)
