### ISSUE TITLE
Refer user to the proper block explorer's page after submitting a transaction successfully

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#598]
**Describe "Why" this is needed**
When a user submits a valid transaction, it should be presented with the mean to track said transaction in the explorer. The best way would be to return the block explorer's link to that transaction directly as output

**Describe alternatives you've considered**
A cool alternative would be to open the browser at the transaction link

**Additional context**
Depends on #597

**Comment by kieranhall** [comment]
FYI, to construct a link to the explorer, only the transaction ID is needed.
