### ISSUE TITLE
Implement a way to choose the appropiate circuit to use depending on the Token type and the Notes amount

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/rusk#60]
That has to be in consensus with the SC platform team and the VM team. This allows to pick a circuit according to the Note number in order to elaborate a proof or validate a proof.

@ZER0 had some ideas in order on how to implement that. Might be a good idea to check which solution to choose with him.

**Comment by Bounce23** [comment]
IIUC, this has been done. As in the number of input notes and ouput notes will match only to one of the hardcoded variations @CPerezz

**Comment by CPerezz** [comment]
I think this also pends on the `rusk-profile` tool that @ZER0 created. So I'll wait to see if he considers that solved.

**Comment by ZER0** [comment]
@CPerezz this looks like potential duplicate (or at least related to) of https://github.com/dusk-network/rusk/issues/162

**Comment by CPerezz** [comment]
And indeed it is. So can be closed @ZER0
