### ISSUE TITLE
Add confirmation before sending transaction

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#602]
**Describe what you want implemented** 
Prompt the user with a confirmation for the transaction with the following recap:
- DUSK about to be sent
- max fee calculated from gas price and gas limit
- Recipient's address

**Describe "Why" this is needed**
Improved user experience

**Additional context**
In the future, `wallet-core` should expose a minimum gas amount required by each different contracts, so to be able to report to the user potential _out of gas_ failures when preparing the transaction

**Comment by t00ts** [comment]
`max fee = gas_limit * gas_price`
