### ISSUE TITLE
High gas limit transactions take longer to process

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#605]
**Describe what you want implemented** 
Transactions with a high gas limit should be given the same chance of being executed.

**Describe "Why" this is needed**
Transactions shouldn't be penalized due to a high gas limit.

**Describe alternatives you've considered**
Keeping it as it is, while not a critical problem, will artificially lower the probability of a high gas limit transaction being processed - effectively penalizing the user for allowing more of their Dusk to be used for a transaction.

**Additional context**
Transactions that have a high gas limit, while containing a theoretically high amount of Dusk available to be spent, don't necessarily result in a high gas spent. While this means that the gas limit should **not** be used to prioritize a transaction, it also does **not** mean that it should be used to de-prioritize a transaction. The latter is effectively what happens, since, with the current implementation, transactions with a high gas limit can only be included earlier in the block.

https://github.com/dusk-network/rusk/blob/8fcc220f1a0410d56eeb9fdae4b2ebf657882da4/rusk/src/lib/services/state.rs#L184-L195

**Comment by herr-seppia** [comment]
Additional context:
The real priority is calculated using `GasLimit * GasPrice`
This means that a tx with lower GasLimit can have higher priority than a tx with higher GasLimit

This doesn't solve the issue you raised, but at least allows the user to play with the GasPrice to adjust his priority (_"and here is where the gasPrice war began"_)

**Comment by ureeves** [comment]
I'm not suggesting `rusk` should care about the priority. In fact all of the code in `rusk` is completely oblivious to transaction ordering or which transactions come in. I'm saying that given the current state of the code, transactions with a high gas limit have a lower change of being included in the block - making them de-facto de-prioritized. This is not something we want, ergo this issue.
