### ISSUE TITLE
Implement BLS signing and verification through Phoenix

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/rusk#61]
As key management moves from `dusk-blockchain` to Phoenix, we run into a bit of a scattered setup. The consensus keys (BLS) are still generated on the Golang side, while the wallet keys are done on the Rust side. In order to prevent having to pass keys between processes (and possibly making room for attacks), Phoenix should be entirely responsible for all key management and utility.

**Comment by autholykos** [comment]
Consensus will keep using bn256 internally, but operations on Rusk will be carried out using `JubJubPoints` (keys) fetched through `dusk-pki`. Closing
