### ISSUE TITLE
Memory leaks at proof creation

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#610]
**Describe the bug**

**To Reproduce**
if applicable add a *minimum reproducible example*

```
// Be exhaustive
// 
```

**Expected behaviour**

**Logs/Screenshot**
If applicable, add damning logs

**Platform**
Fill as appropriate
 - Architecture: [ARM, 8086]
 - OS: [e.g. iOS, Linux]

**Additional context**

**Comment by herr-seppia** [comment]
Closing as further tests shown no memory leak
