### ISSUE TITLE
No logs are written during the configuration load

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#613]
**Describe the bug**
If any error happen during the loading of rusk configuration, they are not logged anywhere

**To Reproduce**
`target/release/rusk --generator IwillFAIL`

**Expected behaviour**
It should log this line
`WARN rusk::config::wallet: Failed parsing <generator>. Defaulting to Dusk's key`

**Additional context**
The logger doesn't exists yet because it is instantiated using the configuration itself

**Comment by ZER0** [comment]
@OsDusk talk with @herr-seppia to check if it's still valid, and how to proceed in case.

**Comment by OsDusk** [comment]
Obsolete by now according to @herr-seppia
