### ISSUE TITLE
Proposal for changing the mint function

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#614]
**Describe what you want implemented** 
* Change the minted notes to be saved in the `stake` contract state.
* `UnlockStakeReward`
* `WithdrawStakeReward`

**Describe "Why" this is needed**
The minted notes should not affect the `transfer` state until explicitly withdrawn.
Such notes should reside in the `stake` state until withdrawal, after which, a single note shall be minted and added to the `transfer` state. 
This should help to mitigate the needs of a "merging notes" circuit.

**Describe alternatives you've considered**
Stick with the actual implementations.

**Additional context**
To avoid unbalance in the consensus, the minted notes saved in the stake shall not affect the amount of "staked dusk" (basically there is no compound effect).
If a user want to use them, it will have to "Unlock" the rewards, wait an optional cooldown period, and then withdraw the unlocked amount.
This is similar to how the actual pre-staking is working.

**Comment by ureeves** [comment]
We had a meeting on this and have frozen the issue for now. There was a decision to go with a strategy of accumulating rewards in the stake contract, as long as the condition for said withdrawal is that the user also withdraw the stake. This way the user would need to pass through the maturity period, as such avoiding compound stakes within the reasonable range.

Withdrawal of the stake would also mean a withdrawal of the reward - meaning during the same transaction. This can be achieved by using either a host call or an inter-contract call that mints a note - with the current value of the reward - belonging to a (stealth) address of the caller's choosing.

There is a work in progress branch for this issue [here](https://github.com/dusk-network/rusk/tree/accumulating-stake-614). We should pick it up when we deem it appropriate to do so.
