### ISSUE TITLE
wallet: configuration should be created if it does not exist

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#647]
**Describe what you want implemented** 
During the first run of the wallet, if the configuration `.toml` does not exist, it should be generated on behalf of the user and placed in the default folder. 
**Describe "Why" this is needed**
A user should be able to change configuration parameters.

**Describe alternatives you've considered**
The generation could be interactive (e.g. through a wizard process) or it can be as simple as telling the user where the configuration gets created (so she can twick it by herself).

**Comment by t00ts** [comment]
As per yesterday's conversation, the wallet was going to be shipped with a valid configuration file pointing to a running cluster. That was the sole reason as to why this (rather large) refactor was done.

Is this no longer the case? 

cc @Fulviuus
