### ISSUE TITLE
Research about MPC protocols and come up with the best options we currently have to make one.

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/rusk#65]
A malicious prover can manipulate the public parameters, ck, and domain to generate a proof that contains a false statement but can be verified correctly by the verifier, provided the malicious prover knows the domain and vk of the verifier.

To prevent that, there should be a ceremony

**Comment by HDauven** [comment]
This can be closed as duplicate, given research is tracking this issue [here](https://github.com/dusk-network/research-internals/issues/151).
