### ISSUE TITLE
Create `Dusk` denomination struct

### ISSUE THREAD

**Issue by t00ts** [dusk-network/rusk#675]
**Describe what you want implemented** 
Create `Dusk` and `Lux` structs that can be used across the whole stack.

- Can be `Deref`'ed into a `u64` 
- Handle conversions from user-inputed `f64`s
- Handle displaying as currency measure
- Implement the normal arithmetic and conversion operations between them

The goal is to have a single source of truth for anything related to the DUSK denomination that's accessible to the whole stack. This is relevant not only for the wallet, but also for anything related to our economic model or the SDK we offer for smart contract development.

**Describe "Why" this is needed**
Right now we're using a few type aliases within `rusk-abi` (which itself makes little sense)

To work with these types, we're using arbitrary conversion methods wherever necessary. This can be clearly observed in the `rusk-wallet` crate, where we're doing things like parsing user input as DUSK, displaying amounts in DUSK, calculating fees in DUSK... yet we're using nanoDUSK as the underlying safe type for obvious reasons. This results in a rather messy approach that will eventually have to be solved.

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/dusk-network/rusk/pull/673

**Comment by herr-seppia** [comment]
Done in `rusk-abi`
