### ISSUE TITLE
Preverify requires prover keys

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#685]
**Describe the bug**
Preverify fails if no `.pk` is found

**To Reproduce**
Call preverify on a node where `*.pk` are removed

**Expected behaviour**
Preverify should pass without *.pk

**Logs/Screenshot**
```
==> /var/log/dusk_rusk.log <==
2022-03-31T08:36:53.218605Z  INFO rusk::services::state: Received Preverify request

==> /var/log/dusk.log <==
{"duration":19403,"error":"rpc error: code = Internal desc = IO Error: keys not found","kad_h":124,"level":"error","msg":"failed to accept transaction","process":"mempool","time":"2022-03-31T08:36:53Z","txid":"","txsize":2191,"txtype":1}
{"cs":"0ccd8728","error":"error while processing: rpc error: code = Internal desc = IO Error: keys not found - topic tx","level":"error","msg":"failed to process message","process":"kadcast","time":"2022-03-31T08:36:53Z","topic":"tx"}
```

**Platform**
N/A

**Additional context**
Preverify should pass even without `.vd` stored on filesystem

**Comment by ZER0** [comment]
I'm going to approve the PR connected, but about the additional context, I'm not sure how the preverify could pass without the `vd` stored on the file system – unless you wan to call the contract for that; and it wouldn't be a good idea at the moment.
