### ISSUE TITLE
Allow to include an arbitrary state within rusk-recovery

### ISSUE THREAD

**Issue by autholykos** [dusk-network/rusk#711]
**Describe "Why" this is needed**
We need to handle different versions of the global state in order to allow for multi-cluster selection, and bootstrap different networks with different genesis state.

**Describe alternatives you've considered**
The state should no longer be created or downloaded at runtime (i.e. when launching rusk-recovery tool), but it needs to be created or downloaded at build time and included in the recovery tool.

**Comment by herr-seppia** [comment]
Closed as obsolete
