### ISSUE TITLE
Enable gRPC tracing logs

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#722]
**Describe "Why" this is needed**
To properly time the execution of each request by the dusk-blockchain.
Furthermore this is useful to investigate block time issues related to the new lock mechanism introduced by #716 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ZER0** [comment]
@OsDusk talk with @herr-seppia about this issue, if it's still valid and how to proceed.

**Comment by herr-seppia** [comment]
Closing as not required anymore
