### ISSUE TITLE
Convert "rust-toolchain" file to TOML and add wasm32 target 

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#751]
#### Summary
> 💡 Add a clear and concise description of **the reason why** this needs to be worked on. Focus on the big picture rather than implementation details. What use case does it support? What is the expected outcome?

As per the readme right now, `make test` doesn't compile out of the box if the user doesn't have the `wasm32-unknown-unknown` target installed. This can be solved by `rustup toolchain add wasm32-unknown-unknown` but since there's a rust-toolchain file already in the project root, we just need to specify this target there and `make test` would compile without running the rustup toolchain command.

#### Possible solution design or implementation
> 💡 Add clear and concise description of concrete solutions you've considered. Include possible drawbacks. Add diagrams, pictures, description, code-snippets, or anything else that might help solving the issue. Consider adding different implementation alternatives with tradeoffs.

Rename rust-toolchain (legacy) to rust-toolchain.toml and add the toolchain there
```toml
[toolchain]
channel = "nightly-2022-08-28"
targets = ["wasm32-unknown-unknown"]
```

#### Additional context
> 💡 Add any other context information about the feature request here. Add related issues/PRs this issue is related to (i.e. depends-on/is-blocking/helps contextualize). **Consider creating an RFC (possibly in the project's wiki) if the issue is about assessment or investigations.**

**⚠️ Important:** _Log any information, decision making, and discussion as comments to this issue, so they don't get lost. Also, open up a `Draft PR` as soon as possible to resolve the issue, and commit frequently. See [the contribution guidelines](https://github.com/dusk-network/.github/blob/main/.github/CONTRIBUTING.md#resolving-issues) for more information._

**Comment by ZER0** [comment]
Hey @Daksh14 I saw the PR closed, but I didn't understand why. I assign this issue to @OsDusk since your priority is working to the pilot and this issue looks like a good first bug. Maybe you can mention here or contact @OsDusk on discord about why the PR was closed.

**Comment by Daksh14** [comment]
I closed it because it was in active and I thought the change isn't required but we can always open it again and get it in. @ZER0
