### ISSUE TITLE
Port the Rusk Test Infrastructure to use Piecrust

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#773]
Summary
Migrate rusk test infrastructure to make use of piecrust instead of rusk-vm. This will allow rusk to be faster at executing contracts, and use less disk space - together with a number of other improvements, i.e. less gas per TX.

Possible solution design or implementation
Remove rusk-vm dependency, add piecrust dependency, and port Rusk's test infrastructure to use the new API, new rkyv serialisation, new Plonk and all the remaining dependencies.

Additional context
This is a part of a larger effort to migrate the entirety of rusk to use piecrust. This issue is dependent on issue #759 being implemented first

**Comment by ureeves** [comment]
Effectively closed by #783 since it removes the transfer wrapper
