### ISSUE TITLE
Update CI so it can read rust-toolchain.toml file

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#792]
**Describe the bug**
Use of unmaintained org [`actions-rs` ](https://github.com/actions-rs/toolchain/issues/216)actions.

**To Reproduce**
Currently cannot detect `rust-toolchain.toml` files.  Look at #788 

**Expected behaviour**
`rust-toolchain.toml` file should work

## Solution:

Easy, use [`dtolnay/rust-toolchain`](https://github.com/dtolnay/rust-toolchain) and forget about it 🙃

**Comment by HDauven** [comment]
The current `runs-on` configuration in the CI for this repository is wrong. `core` is not an option. Given that we primarily target Linux, it makes sense to default to `ubuntu-latest`.

The current `actions/checkout` version is `v3`, which comes with Node 16, versus the Node 12 that is currently being used.

`dtolnay/rust-toolchain` comes with the [minimal profile by default](https://github.com/dtolnay/rust-toolchain/issues/41), and targeting the nightly is as simple as tagging `@nightly` after the `uses` step.
