### ISSUE TITLE
governance-contract: Perform signature verification for unit tests 

### ISSUE THREAD

**Issue by Daksh14** [dusk-network/rusk#814]
#### Summary
> 💡 Add a clear and concise description of **the reason why** this needs to be worked on. Focus on the big picture rather than implementation details. What use case does it support? What is the expected outcome?

Context: https://github.com/dusk-network/rusk/pull/813#discussion_r1086985000

#### Possible solution design or implementation
> 💡 Add clear and concise description of concrete solutions you've considered. Include possible drawbacks. Add diagrams, pictures, description, code-snippets, or anything else that might help solving the issue. Consider adding different implementation alternatives with tradeoffs.

Do the signature verification in the unit test.

#### Additional context
> 💡 Add any other context information about the feature request here. Add related issues/PRs this issue is related to (i.e. depends-on/is-blocking/helps contextualize). **Consider creating an RFC (possibly in the project's wiki) if the issue is about assessment or investigations.**

**⚠️ Important:** _Log any information, decision making, and discussion as comments to this issue, so they don't get lost. Also, open up a `Draft PR` as soon as possible to resolve the issue, and commit frequently. See [the contribution guidelines](https://github.com/dusk-network/.github/blob/main/.github/CONTRIBUTING.md#resolving-issues) for more information._

**Comment by herr-seppia** [comment]
Obsolete
