### ISSUE TITLE
Remove `enc`, `nonce` and `R` from the hash of a note

### ISSUE THREAD

**Issue by xevisalle** [dusk-network/rusk#815]
Currently, when we compute the hash of a note (in the circuit and in the Merkle tree of notes), we include the parameters named `enc`, `nonce`, and `R` (where R is a part of the stealth address). We figured that these three elements are not needed in this computation. Hence, they can be removed from the circuit. This change will affect the circuit and the storage of notes in the Merkle tree of notes.

**Comment by herr-seppia** [comment]
@xevisalle is this issue solved by https://github.com/dusk-network/phoenix-core/pull/124 right?

**Comment by xevisalle** [comment]
@herr-seppia no, both issues need to be tackled. Phoenix was already updated, and now in Rusk we should use that version with the changes that are already done in the PR.

**Comment by herr-seppia** [comment]
@xevisalle Isn't already tackled by this? https://github.com/dusk-network/rusk/pull/942

**Comment by xevisalle** [comment]
@herr-seppia YES! Wasn't aware of that PR. I'm closing this issue then.
