### ISSUE TITLE
Create example contract utilising ZK-functions provided by host

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk#851]
#### Summary
Dusk virtual machine supports privacy yet we do not have an example contract that would utilise ZK proof facility provided by the host. Such example contract would showcase this feature of our protocol.

#### Possible solution design or implementation
Implement a simple yet convincing real life example business case of cooperation of two contracts which do not trust each other and which perform a business interaction in a zero-knowledge manner, utilising the power of provided by the host ZK proving function(s).

#### Additional context
Business case should be understandable for everyone without the need to have a business background.

**Comment by HDauven** [comment]
@miloszm @ureeves can we state that this issue is resolved by [Add zk proof verification test](https://github.com/dusk-network/piecrust/pull/256) in Piecrust or do we want something more extensive?

**Comment by HDauven** [comment]
Already done here: https://github.com/dusk-network/piecrust/pull/256
