### ISSUE TITLE
Contracts should be able to comp their caller's fee

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#882]
#### Summary
In the context of the [fee market](https://github.com/dusk-network/rusk/issues/880) we should allow the contract to comp the gas cost of running one of its functions.

Since someone should still pay the contract's execution, the owner of the contract must have a wallet that can be depleted to pay gas costs.

#### Possible solution design or implementation
These changes, since they affect the way fees are paid, will touch the transfer contract. The transfer contract will have to be aware of the contracts that comp their gas fees and deplete their owner's wallet of the appropriate amount. 

Gas metering is implemented in [`piecrust`](https://github.com/dusk-network/piecrust), so it may be necessary to make changes there are well.

#### Additional context
In some sense this is the opposite feature to [allowing contracts to levy fees](#881). It allows contract owners to, for example, offer periods of execution for free.

**Comment by autholykos** [comment]
This issue should be re-evaluated in light of the recent decision taken about the economic protocol (in particular the obsolescence of scenario 2: contract charges fee, contract pays for gas)

**Comment by autholykos** [comment]
Re-evaluation complete: Obsolete
