### ISSUE TITLE
Dependency loop with `wallet-core`

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#886]
#### Problem

Currently, `wallet-core` depends or `rusk-abi` - which is in this repository. However, `rusk` - which is also in this repository - depends on `wallet-core`.

This generates a really nasty release loop, where we have to release `rusk-abi` before we might like to, in the hopes of merging PRs that target `rusk`.

#### Possible Solution

I suggest we use [`git-filter-repo`](https://github.com/newren/git-filter-repo) to graft the histories of the two repositories together, under a subdirectory.

**Comment by HDauven** [comment]
@moCello can we have a chat about this? I'm not sure if it's resolved already or not.

**Comment by moCello** [comment]
Yes please! This issue is making any dependency update a nightmare

**Comment by autholykos** [comment]
Closed in favor of #1853
