### ISSUE TITLE
Update consensus nomenclature

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#905]
**DESCRIPTION**
Following discussions in the past months, we should update several names in the consensus protocol.

**DETAILS**
Following what decided with @autholykos, the following phases should be renamed:
- Selection -> Attestation
- Agreement -> Ratification

Following discussion on Committee Size, the following attributes should be renamed:
- Committee Size -> Voting credits

**Comment by herr-seppia** [comment]
> Any ideas?

What about "Voting Pool"?

**Comment by fed-franz** [comment]
I think it should give the idea of "size" somehow, or at least of a number.
If we used pool, it should be Pool Size... but it could generate ambiguity as well.

We could also simply use "credits" for both. We would have committee credits (e.g. 64), and member credits (e.g. 3).
But I was wondering if we could find a different term giving the same idea.

**Comment by fed-franz** [comment]
Superseded by #1178
