### ISSUE TITLE
OoM in `get_provisioners` RPC

### ISSUE THREAD

**Issue by ureeves** [dusk-network/rusk#908]
**Describe the bug**
When there are enough stakes managed by the transfer contract, the `get_provisioners` will fail due to the argument buffer being too small to hold all of them at the same time.

**To Reproduce**
Insert a large number of stakes into the stake contract and do a `get_provisioners` call. It will error with OoM.

**Expected behaviour**
The RPC shouldn't error even with that many provisioners in the state.

**Comment by herr-seppia** [comment]
### To Reproduce
```
git checkout origin/piecrust-provisioners
cargo test --release --package rusk --test tests -- services::state_service::test_get_provisioners --exact --nocapture
```

ps: To be fair we are not getting `OoM`, but a `VM Error: Cannot allocate memory (os error 12)` (it's slightly different)
