### ISSUE TITLE
Replace gas_price with gas_limit in get_txs_sorted_by_fee

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#911]
**Describe the bug**
In [`get_txs_sorted_by_fee`](https://github.com/dusk-network/rusk/blob/master/node/src/database/rocksdb.rs#L451), `total_gas` should add tx's `gas_limit` instead of `gas_price`.

Also, when exceeding `slippage_gas_limit`, loop should `continue` instead `break`, so to fetch another tx.

**Comment by herr-seppia** [comment]
I believe the greediest way is to sort them by gas_price.

**Comment by fed-franz** [comment]
> I believe the greediest way is to sort them by gas_price.

Isnt' that already the case?
