### ISSUE TITLE
Implement greedy transaction inclusion for new blocks

### ISSUE THREAD

**Issue by fed-franz** [dusk-network/rusk#912]
### Issue
Currently, when creating a new candidate block, we follow this strategy:

1. We include txs summing their gas limit until the sum reaches the block limit + 10% (slippage_gas_limit).

Pseudocode:
```
    mempool_txs = get_txs_by_gas_price()
    total_gas = 0 ; txs_list = []
    for tx in mempool_txs:
      if total_gas + tx.gas_limit < slippage_gas_limit
        txs_list.push(tx)
 ```
2. We execute the state transition with these txs, and exclude txs that were not executed by the vm.

This approach has the advantage of speeding up block creation, but includes transactions only based on their gas_limit. This might produce situations like the following one:

 - suppose we had a block limit of 1000 and a mempool with 100 transaction with gas_limit=100, but which actually spend 10; in this case we would only include 10 transactions, instead of 100, because we consider the gas_limit instead of the actually spent gas;

### New Approach
A better approach would be to execute transactions at the time they are included in the list.
This approach would allow to fill the block based on what transactions actually spend.

This should be feasibile with the new integration of consensus in rusk, and the use of the new piecrust vm.

Example pseudocode:
 ```
    let mut session = vm.session().start();
    let mut executed_txs = vec![];
    let txs_todiscard = vec![];
    for tx in mempool.iter_by_price().next() {
        match session.try_add(tx) {
            Ok(tx) => executed_txs.push(tx),
            Err(Discarded(tx)) => txs_todiscard(tx),
            Err(BlockOOG) => break,
        }
    }
    session.commit();
        let root = session.root();
```

**Comment by herr-seppia** [comment]
Implemented by #995
