### ISSUE TITLE
Resolve any incompatibility issues between rusk and golang node implementations

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/rusk#921]
#### Summary
We're wrapping up the full migration of  dusk-blockchain into rusk repository (golang -> rust). Before moving on, we need to ensure that both developments are the same implementation of the protocol without any breaking change.

#### Detailed Description (optional)

This should cover the comparison of the following structures and procedures:

- Wire message encoding/decoding
- Consensus messaging and state
- Sortition
- Block Certificate verification
- Block Header verification
- Sync-up procedure

In case a major incompatibility is found, another issue should be filed. For anything minor, we can address it within this issue.

#### Relevant Context (optional)

One can utilize the sync-up procedure to allow a rusk node to join golang-driven network and vice versa. Ideally,  a rusk node should be capable of catching up a golang-driven test-harness and participate in consensus as an eligible provisioner.

**Comment by fed-franz** [comment]
The Documentation Issue on Succinct Attestation (https://github.com/dusk-network/dusk-protocol/issues/3) includes the revision and comparison of both codebases, so it should cover at least part of this.

**Comment by goshawk-3** [comment]
Obsolete issue
