### ISSUE TITLE
Replace `rusk.persist()` method

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#924]
#### Summary
With the land of piecrust, the `rusk.persist()` method is now a noop, since every accept/finalize is always persisted.
Unluckily, all the dusk-blockchain sync was incepted around that method.
(See also: dusk-network/dusk-blockchain#1530 and dusk-network/dusk-blockchain#1532)

Said that, current dusk-blockchain implementation is not usable with a piecrust version of rusk.

#### Possible solution design or implementation
To avoid completely wasting time on upgrading grpcAPI just to fit only dusk-blockchain need, we should at least upgrade those API with a logic that is reusable by the rusk full node.
So, I'm for changing the current state grpcAPI with the following

* Execute(from_root, txs[]) -> new_root, executed_txs[], invalid_txs[] //forget session
* Verify(from_root, txs[], expected_root) -> bool //forget session
* Persist(from_root, txs[], expected_root) -> () // Replace the previous Accept/Finalize calls. It executes txs and updates the current commit only if root is equal to the expected
* Finalize(from, to) --> () // Squash commits and update `base_root` to `to` if `base_root==from`
* Revert(to) -> () //remove all inner.commits between `to` and `current_commit` and replace `current_commit` with `to`

**Comment by goshawk-3** [comment]
> Unluckily, all the dusk-blockchain sync was incepted around that method

I'm not certain this is true: 

For the record, Persist grpc API was added as an optimization. (see also https://github.com/dusk-network/rusk/issues/572).

If we now are back to the strategy  where we persist on each `accept/finalize` call, there should be no issue with dusk-blockchain sync if we always call `StoreBlock(block, persisted = true)`.
