### ISSUE TITLE
Remove txs from mempool after being included in a block

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#935]
#### Summary
Transactions included in an accepted block must be removed from the mempool.
In a more generic way: Remove accepted nullifiers from the mempool

#### Additional context
N/A

**Comment by goshawk-3** [comment]
This is already done in `try_accept_block` after successful block acceptance. Do you mean anything more specific? @herr-seppia 

```rust
 pub(crate) async fn try_accept_block(
        &self,
        blk: &Block,
        enable_consensus: bool,
    ) -> anyhow::Result<()> {

... 

// Delete from mempool any transaction already included in the block
        self.db.read().await.update(|update| {
            for tx in blk.txs.iter() {
                database::Mempool::delete_tx(update, tx.hash());
            }
            Ok(())
        })?;

```

**Comment by herr-seppia** [comment]
Yes,
current `delete_tx` impl remove nullifiers of a given tx **only** if the tx hash is present.

We should cover the more generic use case that is:
```
for tx in txs {
  for input in tx.inputs {
    delete tx where input in tx.inputs
  }
}
```

**Comment by fed-franz** [comment]
IIUC, you're talking about removing multiple txs spending the same output.
(I'm not sure, because you talk about removing nullifiers)

If so,
IMHO, such transactions shouldn't be in the mempool at all, as this typically gives space to flooding attacks, where the network with is spammed with double-spending transactions to fill up nodes mempools.

**Comment by herr-seppia** [comment]
You're right
And indeed, node avoid to insert those txs in the mempool

However, depending on how the tx is propagated, it still can happen to accept a block containing a tx which the node is not aware of. 
And that tx can use nullifiers belonging to one of the txs in the node's mempool.

So the scenario must be handled properly

**Comment by fed-franz** [comment]
Ok, that makes sense
