### ISSUE TITLE
Change `finalize` to only squash commits

### ISSUE THREAD

**Issue by herr-seppia** [dusk-network/rusk#967]
#### Summary
Currently, if the state root returned by the `finalize` operation mismatch, it's impossible to revert

#### Possible solution design or implementation

Since accept and finalize are the same operations except for the squashing strategy, we should change the node in order to always call "accept" and, if the state hash match, call finalize to squash previous commits (if the block is finalizable).
This requires that `finalize` must not process transactions, but just squash commits between `from` and `to` (at the beginning, we can omit to explicitly pass those variables, since they are known by rusk)

#### Additional context
In addition, it would be useful to change the `Accept` method in order to receive the `expected` state root. If that is not matching the effective result, the vm should not commit

>  Persist block should be done only after ensure that state_root returned by `accept`/`finalize` is the same of the block header
See also #924

_Originally posted by @herr-seppia in https://github.com/dusk-network/rusk/pull/902#discussion_r1229560408_

**Comment by goshawk-3** [comment]
As the ultimate resolution, we concluded to implement a consistency_check in both the accept and finalize calls. This validation enables a caller to ensure the commitment of a VM state change only when a valid state_root is returned.
