### ISSUE TITLE
Verify agreement message before its re-broadcast 

### ISSUE THREAD

**Issue by goshawk-3** [dusk-network/rusk#982]
#### Summary
Due to recent improvements (aggregateUncompressedPks impl,  removal of Cgo overhead ) we may expect to see a significant improvement in the algorithm of full agreement verification. This to be proved a benchmark (unit) test should be provided that measures the verification of agreement signed by maximum number of extracted provisioners.

Nevertheless, to fully guarantee a neutral or positive effect of the verification on both consensus time and occurrences of consensus splits, we could implement the alteration in the rusk node and carry out the end-to-end (E2E) process in a devnet comprising 64 provisioners.

#### Additional context
 This change can be considered for merging to master once the consensus time is satisfactory.

**Comment by fed-franz** [comment]
Do we have any meaningful statistics on the average amount of provisioners in a committee?
It could be worth benchmarking the overhead with such an amount as well, apart from the worst-case scenario of 64 committee members.

**Comment by goshawk-3** [comment]
> Do we have any meaningful statistics on the average amount of provisioners in a committee? It could be worth benchmarking the overhead with such an amount as well, apart from the worst-case scenario of 64 committee members.

Not sure any stats on that would have any meaning. In a network with more than 64 provisioners (as it should be), this depends on how many times a provisioner is extracted. In other words, depends on the amounts staked.

**Comment by fed-franz** [comment]
> > Do we have any meaningful statistics on the average amount of provisioners in a committee? It could be worth benchmarking the overhead with such an amount as well, apart from the worst-case scenario of 64 committee members.
> 
> Not sure any stats on that would have any meaning. In a network with more than 64 provisioners (as it should be), this depends on how many times a provisioner is extracted. In other words, depends on the amounts staked.

Precisely for that reason (that provisioners are extracted multiple times, proportionally to their stake), I think it would be interesting to empirically see the average committee size. 
For instance, let's say that with more than X stake (likely a percentage of the total stake), a provisioner is likely to be extracted more than once. It would be possible to have a situation in which the average committee size is, say, 30 provisioners. 
I'm just thinking out loud here, but I think we should have this kind of information, regardless of this benchmarking.

**Comment by goshawk-3** [comment]
The issue is not relevant to the current version of Consensus protocol.
